### ISSUE TITLE
WISH: allow Arc input into "Reference Point at Length" node

### ISSUE THREAD

**Issue by Oobbuuky** [DynamoDS/Dynamo#1003]
I am getting errors when trying to feed an Arc into the "curve" input on the "Reference Point at Length" node.  The error says it can't cast an Arc to type CurveElement.  Is it possible to allow this node to work with Arcs vs. CurveElements?
Thank you.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
