### ISSUE TITLE
Watch Image is not consistent with other watch nodes

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1005]
Unlike the other watch nodes it does not pass the image through but instead passes a function? Tooltip is "success?"

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
