### ISSUE TITLE
'Run Automatically' is checked. then clicking on certain nodes crashes Dynamo...

### ISSUE THREAD

**Issue by chander20101981** [DynamoDS/Dynamo#1006]

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
