### ISSUE TITLE
If Statement inside of custom node extremely slow to create and copy/paste

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1012]
making an if statement inside a custom node is extremely slow, the node goes red on creation even through the graph is not being run with error ' test input must be connected'

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
