### ISSUE TITLE
Dynamo Search for Packages shows no results

### ISSUE THREAD

**Issue by abhipalit** [DynamoDS/Dynamo#10249]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 2.0.3

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Architect

## What did you expect to see?

(Fill in here)

## What did you see instead?

Package Search showing no results
![image](https://user-images.githubusercontent.com/59023280/71523483-4e0d2300-28ef-11ea-8eb5-9dbd4446f341.png)

**Comment by QilongTang** [comment]
@abhipalit Hi, were you able to reproduce this consistently? Although it happens rarely, search term and results list could be out of sync, from your picture, it seems you have not entered anything yet but the server returned no package list, can you confirm if this is the case because our team could not reproduce what seemed happened..

**Comment by mjkkirschner** [comment]
please see this thread:
