### ISSUE TITLE
Improvement: Cartesian Product error message not helpful

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1027]
Not sure should handle this automatically but would be nice to get a clearer error.
![screen shot 2014-01-21 at 2 47 04 pm](https://f.cloud.github.com/assets/508936/1967416/1e2dbc4c-82d5-11e3-9754-22db07fea190.png)

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
