### ISSUE TITLE
BoundingBox.ByGeometry returns incorrect results when given an empty list.

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#10309]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.1

## Operating system

windows 10

## What did you do? 

attempted to pull a bounding box from an empty list using a BoundingBox.ByGeometry node.

## What did you expect to see?

an empty list, null, or a type error.

## What did you see instead?

A large bounding box, with a min point at 1,1,1, and a max point at 0,0,0 which makes it an incorrect geometry (see the max point (blue) and min point (red) in the screenshot). Oddly enough the Geometry.BoundingBox node works correctly. Perhaps deprecating the BoundingBox.ByGeometry node would be a good idea, but checking with D4R to see if that is a requirement.

![image](https://user-images.githubusercontent.com/29869395/72767621-9a801180-3bc2-11ea-80ff-ebca8275667b.png)

**Comment by mjkkirschner** [comment]
tracked with :https://jira.autodesk.com/browse/DYN-2399

**Comment by Amoursol** [comment]
Change regarding the BoundingBox.ByGeometry node:

The BoundingBox.ByGeometry node used to incorrectly return a default size bounding box when an empty list of geometries was provided. This behaviour was unintended and has now been fixed to correctly return null. As this change is not backwards compatible with previous versions of Dynamo we wanted to make you all aware so that you can amend any graph that may have built in a workaround to this behaviour.

While technically a breaking change under semantic versioning, we believe that this behaviour causes more harm than good and merits fixing prior to a future major release of Dynamo. Please do check any graphs you may have created that use this node to check the graph still functions appropriately.

**Comment by Amoursol** [comment]
Fixed and in-product.
