### ISSUE TITLE
List box, Combo box, Drop-Down list box nodes for custom lists

### ISSUE THREAD

**Issue by m-danm** [DynamoDS/Dynamo#10571]
let's say I filter a list of random elements, not family types, or categories or thing already defined in the 
 dynamo/Revit environment and I want to be able to pick an item or several items from that list how can I do this?

of course, I can use data shapes, but that means I have to restart the script every time I want to change something.

drop-down list box functionality already exists in dynamo but just for predefined elements.

**Comment by Amoursol** [comment]
Hello @m-danm ,

Are you talking about building **pop-up windows**, or wanting to integrate into the **dynamo player**, or something else? 😄

**Comment by m-danm** [comment]
let's say that bellow is the Categories node 
______________
|  Categories |
~~~~~~~~~   
when you are trying to choose a category a "Drop-down List Box" opens and lets you choose one element from the list, and the list contains all the categories in the Revit database.
______________
|  categories              |
- Air systems           -
- Air terminals         -
- Structural Systems-
- Walls                     -
~~~~~~~~~~~~~~

Now, this list is predefined - what some of us need is a node with this kind of looks and behavior but with a custom data list, a list one can populate with one's own data.

You know like the ones you can find in accounting programs like excel, access... :))) and like in the _"Value List"_ Node from Rhinoceros - Grasshopper... don't know if you are familiar with app...

pop-up windows already exist thanks to the author of Data-Shapes.

ps. it is never wrong to check what is the competition doing...no pun intended.

**Comment by m-danm** [comment]
![DropDown Box](https://user-images.githubusercontent.com/61791976/79602238-cc860e80-80f2-11ea-9344-2c98898b8668.png)
something like the node above but with custom lists.

Like the Value List - node in Grasshopper.

**Comment by m-danm** [comment]
I hope now it's easier to understand.... a node with a behavior like the behavior of categories node.

**Comment by Amoursol** [comment]
Ah, understood. Thanks for the explanation @m-danm. Out-of-the-box we currently do not offer this functionality as all drop-downs are currently first order Nodes with no inputs.

You are right to mention **Data-Shapes** which is the package I have used in the past for these kind of behaviours.

If you are into C# and/or Python then you can take a look at creating your own node, similar to how @johnpierson does. In fact, he's recently released a WPF code sample for this here: https://github.com/johnpierson/DynamoSampleWPFWindow

Otherwise I would suggest looking to the [Dynamo Forums](https://forum.dynamobim.com/) for help on this.
