### ISSUE TITLE
Wishlist: Read 2D/3D DWG

### ISSUE THREAD

**Issue by gschleusner** [DynamoDS/Dynamo#1073]
There are a bunch of workflows for which we'd like to import 1 or more 2D DWG's that represent floor plans that we'd then like to convert to Revit walls. I don't know if you actually need the districtiong between 2D and 3D dwg but it might help with some workflows.  We'd most likely want a "Filter by Layer" option that would seem to make sense as well.  Given that Dynamo is moving to be less Revit Speciic this seems to be a need in the future.  Writing would obviously be on someone's list as well.

**Comment by ikeough** [comment]
DWG import is now available in Dynamo Studio.

I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!

**Comment by ThomasMahon** [comment]
I know this is closed, but in case anyone stumbles across this thread and wants the ability to filter curves from CAD links or imports via layer name in Dynamo for Revit, I've created a package called Bimorph Nodes which includes a `CurveFromCADLayers` node. It does exactly what it says on the tin and it can output Dynamo curves or Revit Model curves. There is also a node for creating Detail Lines from CAD links or imports with the same functionality:

![image](https://cloud.githubusercontent.com/assets/18601851/24377334/ffa61238-1336-11e7-983e-e069488fc444.png)
