### ISSUE TITLE
Possible Bug- recursive graph slowdown when opening custom node

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1101]
I get on average a 2x slowdown in run of recursive graph when I have the custom node that is the recursive call open in a tab.  Hard to be sure because I'm uncertain how many times the node will be called, but it definitely seems slower in speed of console logs.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
