### ISSUE TITLE
Collecting PlanView also collects View Template

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#1131]
I try to place views on sheets. I first want only Plan views, so I filter out all other view types. Big surprise: more views in the list than in the project! I got view templates too. Weird?

**Comment by ksobon** [comment]
Well, I think that All Elements of Category node works fine for what is being asked of it. Andreas does mention that a View Template is a View Plan so it should be returned in this particular case. The only solution that I can offer here is adding a View.IsViewTemplate node so that you can build a filter like this: 

![image](https://cloud.githubusercontent.com/assets/529781/20034417/e4c4dc64-a393-11e6-963e-23b6be051bcc.png)

This was added to this PR: https://github.com/DynamoDS/DynamoRevit/pull/1378

**Comment by ksobon** [comment]
@jbenoit44 @kronz can we close this issue. What Julien was asking for was perfectly normal behavior. Since then we also enhanced View class so that it offers better View Template handling.
