### ISSUE TITLE
你好，寻求LibG类的帮助

### ISSUE THREAD

**Issue by mingzhao240** [DynamoDS/Dynamo#1151]
我在使用新版的Dynamo的时候关注着这个LibG类的创建，我发现了好多点
1、他好像是特例独行的，没办法直接与原有的电池直接连接
2、他拥有导入SAT的功能，但是却没办法直接导入到Revit/VAsari
3、功能上还比较少，甚至我想到的，都没有

以及，能否提供一点关于导出导入SAT源代码的资料呢？

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
