### ISSUE TITLE
Feature Request: Automatic dependency calculation for *.dyn files

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1171]
It would be really helpful if Dynamo could automatically determine the dependencies of a _.dyn file *and_ offer to install the required packages. 
(When sharing larger graphs with a lot of custom nodes, it can become quite tedious to go through the whole graph and find all the custom nodes.)

**Comment by Amoursol** [comment]
+2 Brilliant idea.

**Comment by ikeough** [comment]
@andydandy74 I finally got fed up enough with opening other people's workspaces and having them be "broken" because I didn't have the right packages. I think I'm going to fix this. Here's what I propose.

We add a section to the .dyn file called `<dependencies>`, which would have dependencies listed like so:
```xml
<depedencies>
  <depedency name="Clockwork" version="0.9.0" />
</dependencies>
```

The dependencies would be calculated during save, by finding the set of packages which contain the assemblies which are referenced by nodes in the workspace. As this would happen the first time on the originating author's machine, the dependencies would be correctly calculated. 

If someone receives a workspace without a `<dependencies>` block, we won't attempt to look for the packages, and we'll continue to let the workspace "break".

When someone receives a workspace with a `<dependencies>` block, Dynamo would check the existing packages to see what was missing, and provide a prompt to the effect of "Several packages that are required by this workspace are unavailable. Would you like to load them?"

This could run into problems where the workspace's author is using packages that are on a network share. In this case, Dynamo will need to check not only for missing packages, but whether those packages are available to the user.

@kronz What do you think of this proposal?
@Racel Are there any UX gotchas that jump out at you?

**Comment by mjkkirschner** [comment]
@ikeough I'm not sure I understand the final paragraph here - otherwise sounds good.

I also think it might be time to expose a local zip download of the entire graph... ala `workspace dependencies` -> zip.

**Comment by ikeough** [comment]
@mjkkirschner You are understandable confused. We don't allow a network share to be used as the package manager source. I was getting ahead of myself :) I've struck that part.

**Comment by ksobon** [comment]
If someone receives a workspace without a <dependencies> block, we won't attempt to look for the packages, and we'll continue to let the workspace "break".

I am not sure i follow this. Can you elaborate a little? How would that even be possible if dependencies are calculated and added on every save event?

**Comment by gregmarr** [comment]
@ksobon Existing workspaces that were saved before this data was added.

**Comment by ikeough** [comment]
@ksobon If someone sends you a workspace from a previous version of Dynamo, that doesn't have this functionality, you'll have this problem.

**Comment by ksobon** [comment]
@ikeough makes sense. Yes, that would be a much needed feature and a welcome addition to HudraShare https://github.com/HydraShare/hydra-dynamo

**Comment by Racel** [comment]
@ikeough - Overall the strategy makes sense to me and agree with everyone else in thinking that this would be a great addition. A few thoughts/questions:
- What is the "sequence of interaction"? When will the user see the prompt? Will it be like this: Load Graph in View -> Execute Graph -> User sees warnings/errors -> Prompt Appears
- Which leads me to ask "what do you think of adding a 'recommended' nodes/packages section to the library?" We have some designs which may already work for this.
- Will local packages be added to this "dependencies" section? What if their name collides with an online package? Are we going to use GUIDs to track packages?
- If we use a prompt, should users be asked which dependencies they want to install or are you thinking that we just go ahead and install them automatically?
- What if after checking for a dependency that we find that it has been deprecated or updated? What will we do? Grab the latest? Provide a new warning on the node?

After writing these down, it seems to me that adding this might need a little bit of design work to get the interactions right. Would love to hear what you think about the questions/thoughts above.

**Comment by ksobon** [comment]
@Racel @ikeough sorry to hijack your question here but:

- I like what Grasshopper is doing. When you opening a definition that is missing some packages you get a prompt with a list of all missing custom components or packages (custom Python components get listed individually if they don't belong to a larger package). There is no option to install them automatically, just a list. It's up to user to make sure that he goes out and gets the packages. You click "OK" and prompt goes away, canvas opens up and its missing bunch of stuff. Technically the prompt happens before the graph executes (it doesn't have to since XML markup will contain all of the info already: installed packages vs dependencies)
- I don't think its necessary to shove any packages (no matter how popular they are) down user's throat. let them decide what they need and they will soon find their way to packages like Clockwork or SpringNodes etc. 
- Yes, local packages should be included. Example: a locally curated package might have had an update and user would be delighted to find out about it. Using GUID's seems like a good idea. 
- I would really not worry about whether these packages were deprecated etc. Just give us a name and a version and I would let users familiarize themselves with Package Manager and what it means to get the right version etc. 

-

**Comment by gregmarr** [comment]
>There is no option to install them automatically, just a list. It's up to user to make sure that he goes out and gets the packages. You click "OK" and prompt goes away, canvas opens up and its missing bunch of stuff.
>Just give us a name and a version and I would let users familiarize themselves with Package Manager and what it means to get the right version etc.

In my experience, users don't like it when programs make them do something manually that it is fully capable of doing by itself, as long as it asks for permission first.

Having to write down, copy and paste, or take a screen capture of the list of modules, and then going to another interface to find each of those modules individually is too much work when the program can handle it automatically.

**Comment by andydandy74** [comment]
First of all. great that this feature request is receiving some attention.

@ikeough - I wonder if perhaps the dependency calculation could also be performed on older files as well that do not yet have a dependencies section. If all dependencies can be resolved, Dynamo can write the dependencies section to the file - otherwise it can leave the file as it is.

Regarding the issues that @Racel brought up, some additions to @ksobon 's comments:
- I'd prefer to get notified of missing dependencies directly after opening the file, too (i.e. before execution). 
- I would like it if Dynamo could install the missing packages for me - but I think this would need to be an optional feature that I can opt out of on a case-by-case basis. (When thinking about central deployments, it would actually be really important to be able to disable this autio-download thing completely - so if it's too much work to achieve this, I'd rather have to download missing packages manually every time rather than having to clean up after my users...)
- Regarding deprecated packages, please see #484 & #1923

**Comment by tatlin** [comment]
The new package manager backend we are working on will support dependency
tracking between packages so this could tie in nicely to storing some
'top-level' dependency info in the dyn. Will need to think about how these
concepts get integrated.

-matt

On Mon, Aug 29, 2016 at 3:06 AM, Andreas Dieckmann <notifications@github.com

**Comment by mjkkirschner** [comment]
this has now been added to master - theres definitely still work to do for all node dep types, but I'm going to close this as the original request for "packages" has been accomplished.

**Comment by johnpierson** [comment]
Woohoo! :grin:
