### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by QuimMoya** [DynamoDS/Dynamo#11833]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Add a folder path in "Manage node and package paths"

### What did you expect to see?
I just hope it to finish

### What did you see instead?
An error

### What packages or external references (if any) were used?
none

### Stack Trace
```
It crasehd so badly i can't open it again and i must restart revit (yes, revit also crashed)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by Amoursol** [comment]
@mjkkirschner do you think this is resolved by the work you and the team are doing right now?

**Comment by QilongTang** [comment]
@jasonstratton Can you follow up with this?

**Comment by aparajit-pratap** [comment]
@QuimMoya could you give more specific steps on what you were trying to do exactly:
- what was the folder path you were adding - was it on your local machine or was it a network location?
- what did the path contain - what Dynamo packages, were there other files that were not meant to be loaded into Dynamo?
- what was the error you saw, was there a stack trace (call stack)?

This information will help us reproduce the issue in order to fix it. Thank you.
