### ISSUE TITLE
DynamoDS – Possible bug related to associative behavior

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#1221]
It seems that moving a existing point from a 2D array is making the application to stop working 
![01](https://f.cloud.github.com/assets/6596042/2343744/0a66d4d0-a514-11e3-8cdd-9c90b7ff062d.jpg)
![02](https://f.cloud.github.com/assets/6596042/2343746/1af27bd8-a514-11e3-915a-b5017f3f0771.jpg)
Notice how the connection out of A  disappear.

It seems that with 1D arrays is less of a problem, even when the connections of the 1D arrays disappear too and we get the same errors messages
![03](https://f.cloud.github.com/assets/6596042/2343787/f63b2b0e-a514-11e3-86d9-d411697c1480.jpg)

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
