### ISSUE TITLE
Ternary receiving list from function

### ISSUE THREAD

**Issue by Curty102** [DynamoDS/Dynamo#12822]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.12.0.5650
Dynamo Revit 2.12.0.5740

## Operating system

Windows 10

## What did you do? 

Code block using ternary syntax.

## What did you expect to see?

return variable "a"

## What did you see instead?

return variable "b"
![TernaryReceiving_2022-04-22_03-51-09](https://user-images.githubusercontent.com/13457861/164791997-054b6afc-add3-4341-8f1c-ee40569458d9.png)

**Comment by mjkkirschner** [comment]
I think this is likely expected when replicating - shortest lacing is used by default - you can force longest lacing to be used by using replication syntax, or you can use the same statement in an imperative block, or use the new if node.

note in the image that in shortest lacing mode the return value of less rank controls the size of the output list.

I believe this is because internally the `?` operator is compiled to a function call in the associative scope - (replication) 

![Screen Shot 2022-05-11 at 4 16 42 PM](https://user-images.githubusercontent.com/508936/167940370-40e74875-98f9-4166-9e0b-8731fb075c7b.png)
![Screen Shot 2022-05-11 at 4 17 11 PM](https://user-images.githubusercontent.com/508936/167940375-b21bd113-2d2d-44f1-b003-f27fd317b8fc.png)

@aparajit-pratap please correct me If I am wrong.

closing for now.
