### ISSUE TITLE
Write to excel node corrupt on one of my computers. 

### ISSUE THREAD

**Issue by Concepts-TC** [DynamoDS/Dynamo#12833]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version 

- Dynamo core: 2.10.1.3976
- Dynamo Revit 2.10.1.4002

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

- Windows 10 pro

## What did you do? 

(Fill in here)
I was building a script meant to write MTO data from my model to Excel using the Data.ExportExcel node. 

## What did you expect to see?

I expected the script to push the parameter values to excel from dynamo 

(Fill in here)

## What did you see instead?

When I run the script, it fails to write to excel and does not give a good reason why it cannot do so. When I check the script on another computer using the same build of Dynamo but a different version of windows, the script runs properly.

(Fill in here)

**Comment by Amoursol** [comment]
Hello @Concepts-TC - Due to the way Microsoft updates Excel, there are situations where a single machine's install may differ from another's and cause issues. If you were to get the same version of Excel on your machine as the one that works this should resolve.

Knowing that this is difficult to manage, we have released new nodes to help that are not as tightly tethered to Excel and it's versions, called **OpenXML** nodes. They essentially do the same thing as Excel, but shouldn't have the same problems. 

If you are in Dynamo 2.12 or higher you will have access to them, and you can read more about it here: https://dynamobim.org/dynamo-core-2-12-release-part-1-2/ 

If you are in an earlier version, then I suggest looking at the "Sheppard Robson" package by Kevin Fielding, who has taken the same approach as us and made it into a package. 

![image](https://user-images.githubusercontent.com/12857357/165624085-3ece52a4-bd1f-4a60-8c84-3005948c230d.png)

If this doesn't work for you, please reopen the ticket.
