### ISSUE TITLE
German characters are missing

### ISSUE THREAD

**Issue by denizmaral** [DynamoDS/Dynamo#12889]
https://github.com/DynamoDS/Dynamo/blob/3c700d9c571d06353862093c23ab100e73690813/src/Libraries/CoreNodes/FileSystem.cs#L70

Without Encoding it causes problems to read text file those contains German charakters.
![grafik](https://user-images.githubusercontent.com/55183821/168826234-727744c1-22bd-4971-9e7d-4a2f82064ac4.png)

**Comment by QilongTang** [comment]
@denizmaral Thanks for reporting! Tracked as https://jira.autodesk.com/browse/DYN-4968

**Comment by denizmaral** [comment]
> 

In Dynamo 2.3

**Comment by zeusongit** [comment]
Ok, thanks @denizmaral, unfortunately we were still not able to reproduce this issue, can you send us the DYN file for the graph you are running? Make sure to remove any confidential information from it before. Also let us know what other packages you have installed.

**Comment by QilongTang** [comment]
hi @denizmaral Since we have not heard back from you and we could not reproduce this issue on our end.
![image](https://user-images.githubusercontent.com/3942418/174112469-1c409b42-819f-4d92-8b22-02a6a3c17e3e.png)

We will stop tracking it for now until we get help from you or other users who encounter this. Cheers!

**Comment by andydandy74** [comment]
@QilongTang This was a Type catalog of a Column family. We'll try to dig it up next week.
