### ISSUE TITLE
Does Dynamo works only in the conceptual mass environment in Revit?

### ISSUE THREAD

**Issue by afcanavera** [DynamoDS/Dynamo#1348]
Hi I'm learning Dynamo for some time ago, 

I realized that the programming environment always occurs in the conceptual mass or adaptive component creation process. Is there any option for using Dynamo in the project environment?

Thanks,

Andrés.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
