### ISSUE TITLE
Metric/Imperial

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#1393]
Newbie here, and don't know whether this is the correct channel to address this issue or not, but it says in the dev log that "Application level settings for Imperial and Metric Units" is added. But where do I control the settings? I've tried with a metric file, but it still comes in feet.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
