### ISSUE TITLE
String to Number - Possible Regression

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1437]
I'm pretty sure this used to work once:
![stringtonumber](https://cloud.githubusercontent.com/assets/3014437/2593083/6ec02b98-ba7c-11e3-9e86-559a19129c15.PNG)
Expected result: 19.9267
Build 0.6.3.7375

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
