### ISSUE TITLE
Crash report from Dynamo 2.18.1.5096

### ISSUE THREAD

**Issue by juhalasa** [DynamoDS/Dynamo#14464]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.18.1.5096`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
I was working with lists of strings. Some of the strings only contain numbers and some numbers and coommas. 

## What did you expect to see?
I expected Dynamo to display for example the string "1" as 1 and "54,2" as 54,2

## What did you see instead?
Instead Dynamo displays strings that only contain numbers with 3 trailing zeros. String "1" is displayed as "1.000". Strings that contain numbers and commas the commas are not visible and trailing zeros are displayed. For example "54,2" is displayed as "542.000". Dynamo does not seem actually change the strings but they are displayed wrong as you can see in my screenshot.

## What packages or external references (if any) were used?
No external packages used.

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`
![strings_with_numbers](https://github.com/DynamoDS/Dynamo/assets/146930229/e7e36491-6174-4de3-85e3-60b2e2a5ec9a)

**Comment by mjkkirschner** [comment]
Hi thanks for reporting this is fixed in 2.19On Oct 4, 2023, at 4:38 AM, juhalasa ***@***.***> wrote:﻿
Issue Description
Please fill in the following information to help us reproduce the issue:
Dynamo version
Dynamo: 2.18.1.5096
Operating system
OS: Microsoft Windows NT 10.0.19045.0
What did you do?
I was working with lists of strings. Some of the strings only contain numbers and some numbers and coommas.
What did you expect to see?
I expected Dynamo to display for example the string "1" as 1 and "54,2" as 54,2
What did you see instead?
Instead Dynamo displays strings that only contain numbers with 3 trailing zeros. String "1" is displayed as "1.000". Strings that contain numbers and commas the commas are not visible and trailing zeros are displayed. For example "54,2" is displayed as "542.000". Dynamo does not seem actually change the strings but they are displayed wrong as you can see in my screenshot.
What packages or external references (if any) were used?
No external packages used.
Stack Trace
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)


CLR: 4.0.30319.42000
