### ISSUE TITLE
Watch node doesnt work in Revit 2013

### ISSUE THREAD

**Issue by zaristamus** [DynamoDS/Dynamo#1479]
The watch node doesnt work in revit 2013. It won't show anything after hitting run.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
