### ISSUE TITLE
Excel.ReadExcelFile node isn't working in 0.7

### ISSUE THREAD

**Issue by soam93** [DynamoDS/Dynamo#1492]
I'm just trying the 'spreadsheet' sample script and that doesn't work.  I've tried other excel-based scripts and getting the same result.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
