### ISSUE TITLE
Data.OpenXMLExportExcel not working in Dynamo 3.0.3

### ISSUE THREAD

**Issue by chrizzrott77** [DynamoDS/Dynamo#15346]
### Dynamo Version

Dynamo Core 3.0.3.7597
Dynamo Revit 3.0.3.4605

### Host

Revit

### Operating System

Windows 11

### What did you do?

Trying to export data using the Data.OpenXMLExportExcel node.

### What did you expect to see?

the output "true" of the node

### What did you see instead?

Output = "null", Error: "Could not load file or assembly 'DocumentFormat.OpenXml, Version 2.12.3.0, Culture = neutral,....."
![image](https://github.com/DynamoDS/Dynamo/assets/65215267/70186833-0385-44f8-996a-7934578a9b5f)

### What packages or external references (if any) were used?

none

**Comment by emru-y** [comment]
Hello @chrizzrott77, 

Thank you very much for your feedback. I tested the node with the same version of Dynamo but couldnt encounter the similar problem. Is it possible for you to share your files or screenshots so that we can try to reproduce the same situation?
![image](https://github.com/DynamoDS/Dynamo/assets/99256363/e7c887d0-edf8-4271-afc6-4214af602c38)

**Comment by chrizzrott77** [comment]
Hi @emru-y,
thanks for the fast reply. It is as spimple as this:
![image](https://github.com/DynamoDS/Dynamo/assets/65215267/4c364169-29d3-49a1-9fc8-da028507f039)
I have tried the same node in Revit 2023 -> Dynamo 2.16.2 and Revit 2024 -> Dynamo 2.17.0 without any issues.

**Comment by chrizzrott77** [comment]
Hi again, 
I have now uninstalled all packages and now it works fine.
