### ISSUE TITLE
Migration issue: How to get Revit face?

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1704]
Prior to 0.7.x selecting a face would give me the Revit Face. Now I get a DS Surface. How do I get the Revit Face if I want to access its properties? Is there a node that I have overlooked? Another thing: Element.Faces is categorized under Revit in the node browser - if it doesn't get me a Revit element or Revit geometry, shouldn't it be categorized under Geometry?
![howtogetrevitface](https://cloud.githubusercontent.com/assets/3014437/3145410/f45534ea-ea35-11e3-9e4f-0a7b4c5cd557.PNG)

**Comment by dronovdmitry** [comment]
Hi andy. 
Sorry, but where i can find this custom node?

**Comment by andydandy74** [comment]
@dronovdmitry - This code is being used in thre custom nodes in package Clockwork: RevitFaceReference.FromDynamoSurface, RevitFace.FromDynamoSurface & Element.FromDynamoSurface. 
Apparently there are some element types that seem incompatible with this code, though: #3821

**Comment by dronovdmitry** [comment]
Ok. But how i can convert dynamo geom to revit geom now?
If this roole https://github.com/DynamoDS/Dynamo/wiki/Python-0.6.3-to-0.7.x-Migration
not work http://joxi.ru/KAxVNV7fQKygm8?d=1
Script: http://joxi.ru/brRLGLpI1OKe21?d=1

**Comment by dronovdmitry** [comment]
Ok. I understand. But i try to set Paint method to geometry in dynamo and i cant do this..... Because dynamo node "Select face" break away geometry face from element and all his parameter.... such as Id... How can i take element ID from surface? http://joxi.ru/KAxVNV7fQVqYm8?d=1 
Thanks

**Comment by moethu** [comment]
Hi there,... some years later another question about this. I need to get the Revit Face because the U,V space of the Dynamo Faces are not correct. So I tried all the mentioned ways but none of them worked out. Do you have any suggestion for Dynamo 0.8?

**Comment by moethu** [comment]
Using GetRevitType gives me a Mesh, maybe there is a way to get from the Mesh to a Revit Face?

**Comment by andydandy74** [comment]
@moethu - the UV coordinates are a known problem: #3423
Follow the link for a workaround...

**Comment by moethu** [comment]
that's one issue, but I was wondering if there is a way to map the U,V coordinates to the surface because right now the U,V coordinates are only on the surface if it is a rectangle.
![2015-07-23_08h47_01](https://cloud.githubusercontent.com/assets/8201465/8845519/d557a440-3117-11e5-8346-5ce5813b7406.png)
I assumed the U,V coordinates would be mapped to odd shaped surfaces as well. So I am up to implement a rescaled U,V Space but therefore I would need the original Revit Face to evaluate if the point is actually on the surface or not. Another solution would be to evaluate points along the edges of the surface and then evaluate a point along this line. But this wouldn't cover curved surfaces or various number of edges... any idea?

**Comment by moethu** [comment]
Never mind, I implemented a Surface wrapper allowing for parametrization on odd shaped surfaces within the boundaries. Code will be public soon. Thanks.
![2015-07-23_11h47_31](https://cloud.githubusercontent.com/assets/8201465/8848660/e43d2354-3130-11e5-88db-ee597e1b3354.png)
