### ISSUE TITLE
0.7 daily: Map.List broken//incorrect behavior

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#1711]
two pictures of definitions from 0.6.3 and 0.7. Works fine in 0.6.3 and doesn't work in 0.7.
![image](https://cloud.githubusercontent.com/assets/4572196/3153384/b468c40e-ea9a-11e3-9021-daceb9d58b5b.png)

![image](https://cloud.githubusercontent.com/assets/4572196/3153387/b8a7d3c0-ea9a-11e3-8426-030f57a40713.png)

I tried to feed the second ListMap node with a list provided by ListCreate, same result.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
