### ISSUE TITLE
imperial - metric wrong results in parameters

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1720]
copying the system parameter "Unconnected Height" to user defined parameter "Wandhoehe" using getparameter and setparameter  should deliver the same value.
But have to multiply with 3.2808 to get correct result.
daily builds from 03.06.
revit 2015 english
![metric-issue](https://cloud.githubusercontent.com/assets/6928491/3171092/b0d6b1fc-ebc1-11e3-8b3d-ef221b5ca9b6.png)

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
