### ISSUE TITLE
Dynamo stucks in Revit 2014

### ISSUE THREAD

**Issue by jechtma** [DynamoDS/Dynamo#1730]
Hi, there,
I have dynamo(v6&v7) installed both on Rvt 2013 & 2014 (English); it works well on the former, but stucks on the latter, shown below:  
![image](https://cloud.githubusercontent.com/assets/7802534/3184332/338883d0-ec82-11e3-8190-722142f3a613.png)

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
