### ISSUE TITLE
6.3 crashes in 2013 when closing

### ISSUE THREAD

**Issue by jmcouffin** [DynamoDS/Dynamo#1754]
"Méthode introuvable : 'Autodesk.Revit.UI.RevitCommandId Autodesk.Revit.UI.RevitCommandId.LookupPostableCommandId(Autodesk.Revit.UI.PostableCommand)'.

   à Dynamo.DynamoController_Revit.ShutDown(Boolean shutDownHost)
   à System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)"

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
