### ISSUE TITLE
Solid to Faces to edges?

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1803]
![screen shot 2014-06-24 at 12 38 27 pm](https://cloud.githubusercontent.com/assets/508936/3374446/4c415640-fbbe-11e3-8c40-d6a98c5c5b43.png)

Selecting a rectangular extrusion in Revit, produces a solid in Dynamo, with no way to get faces, and exploding the solid produces the same solid in a nested list.  Is it possible to get edges and shared surfaces from surfaces.

**Comment by kronz** [comment]
Explode is now working as described 
![2015-05-18_1424](https://cloud.githubusercontent.com/assets/3456818/7687221/9aa1a238-fd69-11e4-983f-9d059b9a0295.png)
But sounds like we still have some work to do with topology

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
