### ISSUE TITLE
Watch3D node does not draw surface geometry automatically from face object

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1808]
![screen shot 2014-06-25 at 8 25 32 am](https://cloud.githubusercontent.com/assets/508936/3384976/e4fc8d64-fc63-11e3-83b4-d364a2e4a256.png)

**Comment by ikeough** [comment]
@sharadkjaiswal @mjkkirschner Still an issue?

**Comment by johnpierson** [comment]
Persists in 2.0.1

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future. 

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap). 

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
