### ISSUE TITLE
Opening 0.6.3 .dyn files in Dynamo 0.7.0

### ISSUE THREAD

**Issue by MarkThorley** [DynamoDS/Dynamo#1849]
I have seen this mentioned before but do we have a definitive answer as to when we will be able to open 0.6.3 dyn files within the new Dynamo 0.7.0? If not I will have to reinstall the old dynamo to get back my scripts.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
