### ISSUE TITLE
Copying nodes removes lacing 

### ISSUE THREAD

**Issue by ekatzenstein** [DynamoDS/Dynamo#1900]
Noticed this with the Surface Point at Parameter node.  When setting the lacing to Cartesian Product, after copying and pasting the node, the lacing returns to Smallest List on the copy.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
