### ISSUE TITLE
How can i get surface from lots of point??

### ISSUE THREAD

**Issue by parkyongil** [DynamoDS/Dynamo#1957]
I have lots of point, and it will make nurbs(?) surface. How can i make surface??
Plz,, help me ~

**Comment by CongzhengZOU** [comment]
> Why you want to make Surface, what kind of operations you want to perform on Surface?
> It would be good if you provide more details on your end goal.
> 
> Thanks,
> Ritesh

I am trying to create a topo from a list of irregular points, and then put a set of objects (with X, Y but no Z) on the topo. 
To get the Z value, I try to create a list of points with X, Y then make projection and calculate the distance. 
The issue is that in Dynamo, Point.Project only accept surface, and if I create topo in revit, i gives me a mesh. If I do Mesh to Surface with Clockwork plugin, revit crashes.
![Sondage_Projection01](https://user-images.githubusercontent.com/70321029/110639262-d0f66280-81af-11eb-9359-9460d83c7931.jpg)

**Comment by ececorlu** [comment]
@CongzhengZOU hey! Could you create a topo from those points?
