### ISSUE TITLE
running tesselation.dyn on multiple faces of a form simultaneously

### ISSUE THREAD

**Issue by afaqsandroid** [DynamoDS/Dynamo#196]
Folks,

I am new to Dynamo.  I just opened up the tesselation.dyn sample file.  The 'select face' node only allows me to pick one face at a time.  Is there a way run the tesselation simultaneously on multiple faces?

Thanks

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
