### ISSUE TITLE
Dynamo Notes Wish list

### ISSUE THREAD

**Issue by Crashnorun** [DynamoDS/Dynamo#204]
When placing a component on to the canvas, it appears in the center. When creating a note, it always appears on the left of the canvas. If you have a large definition file, you will always have to navigate to the left to get the note and navigate back to where you were in the file to place it accordingly. 
1) It would be nice if the note appeared in the center of the canvas just like the other components. 
2) It would be nice to change the font type and font size of the note. When dealing with a large file and you're zoomed out, it becomes tricky to read the notes.
3) Double click to edit notes, in conjunction with the right click option.

Thanks,

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
