### ISSUE TITLE
"Cameras" Categories showing null when using "All Elements of Category" Node

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#2081]
"Cameras" Categories showing null when using "All Elements of Category" Node

My model has many cameras but when I use the Revit-Selection-Categories node and wire it to the "All Elements of Category" node I get a "Null" value in the watch node

**Comment by ksobon** [comment]
@marcellosgamb so a Camera in Revit is really a Perspective View which is a subset of a View3D. Cameras as a class doesn't really exists so I am not sure what its doing in a list of Categories in revit DB. It must be some legacy thing. Anyways here's how to get all perspective views: 

![image](https://cloud.githubusercontent.com/assets/529781/20034693/a315c0d0-a39d-11e6-81b4-c5ff3212279b.png)

I pushed a small change in this PR https://github.com/DynamoDS/DynamoRevit/pull/1378 that will prevent Cameras from showing up in the dropdown since there is nothing that we can do with it.

**Comment by ksobon** [comment]
@marcellosgamb so actually my change was spanked by @mjkkirschner based on the fact that `Cameras` is an obsolete category anyways. We can't just remove it from the list, we shall wait for Autodesk to remove it from the Categories collection altogether. Until then, it stays. Here's the conversation: 
https://github.com/DynamoDS/DynamoRevit/pull/1378/commits/0c9fd0ff4c10d00f5187e8c94e901d6a0b1c5d08

@kronz can we close this issue?
