### ISSUE TITLE
Calling Nodes within Code Block Prompt

### ISSUE THREAD

**Issue by MarkThorley** [DynamoDS/Dynamo#2107]
It would be good if when calling nodes through code blocks that it prompts you when you begin to type to ensure you type in the correct name. So beginning to type Lis....brings up the common list nodes in a drop down, possibly based on user usage.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
