### ISSUE TITLE
Point.PruneDuplicates

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#2163]
While other nodes seem to give a null result and carry on, Point.PruneDuplicates seems to highlight the failure and turns the node yellow

![pointprune](https://cloud.githubusercontent.com/assets/5621624/3929989/ee8e66ea-2431-11e4-9c5f-6c955a1be7f1.jpg)

Regards,
Vikram Subbaiah

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
