### ISSUE TITLE
Surface.PointAtParameter

### ISSUE THREAD

**Issue by gschleusner** [DynamoDS/Dynamo#2210]
I have been trying to use a bunch of quad nodes to give me points when I was finding they never matched the underlying surface if it wasn't rectangular.  So I tested the builtin Surface.PointAtParameter node that they are all based on and it seems to be the culprit...  

Seems like a big one so it might be something specific to me or my environment?

I tested with 7.1 and the latest daily.

![surface pointatparameter](https://cloud.githubusercontent.com/assets/6507154/4011023/8ee0b3c4-29fe-11e4-9cde-bf42519fdf1e.JPG)

![dynamobuild](https://cloud.githubusercontent.com/assets/6507154/4011027/95684e8c-29fe-11e4-9490-f4c7614d6928.JPG)

**Comment by ikeough** [comment]
@aparajit-pratap Do you know if we ever implemented this?

**Comment by aparajit-pratap** [comment]
Will need to do some investigation to see if we can come up with a solution: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9967

**Comment by aparajit-pratap** [comment]
This maybe related to: https://github.com/DynamoDS/Dynamo/issues/5475

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current Dynamo Public Roadmap.

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
