### ISSUE TITLE
wish list item : would like to give names to lists ... instead of (0) list could be renamed to (0) xyz points similar to rename on node names

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#2211]
wish list item : 
would like to give names to lists ... instead of (0) list could be renamed to (0) xyz points for example similar to rename on node names

![untitledlist](https://cloud.githubusercontent.com/assets/6132497/4013555/931d0d8e-2a17-11e4-9c74-470633d5a331.png)

**Comment by ikeough** [comment]
@Racel I know this is being covered in the updates to preview bubbles. Can we link an internal task here?

**Comment by Racel** [comment]
@ikeough - We do not have any tasks around this particular task yet. 

@marcellosgamb - Can you tell us why you would like to rename the individual lists? Is it for documentation purposes so that you/others reading your graph later can easily understand it? Or, do you eventually want to be able to call different lists or list items with particular names?

**Comment by johnpierson** [comment]
This seems doable with the new Dictionary functionality in 2.0.x
![image](https://user-images.githubusercontent.com/15744724/46736805-3187bb00-cc57-11e8-8db0-2ad3b18c472c.png)
