### ISSUE TITLE
Unit inconsistency in trig functions

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2315]
In the Formula node Sin() expects radians, but Dynamo's Math.Sin() expects degrees. This is likely to cause trouble and/or confusion, especially for new users.

**Comment by Racel** [comment]
This is still a problem, but I do not see us having bandwidth to put more work into the "Formula" or "Math.Sin" node to add a units setting. Both nodes are unclear about what unit they require. One quick fix I could see us doing is at least specifying the unit in the tooltip of the "Math.Sin" node. This is a quick one line fix, so adding it to UX Love.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current Dynamo Public Roadmap.

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
