### ISSUE TITLE
CBN Error: ')' expected - Incomplete Closure

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2396]
Entering the following code in a CBN will produce the error given in the issue title:
![parentheses not okay](https://cloud.githubusercontent.com/assets/3014437/4263459/45496ef8-3be8-11e4-954a-a5d3d1ba57f6.PNG)
However, if the last line is transferred to a separate CBN, everything's fine:
![parentheses okay](https://cloud.githubusercontent.com/assets/3014437/4263458/432f6cc6-3be8-11e4-88d2-18e8127b6ee5.PNG)
My gut feeling says this has something to do with the backslashes but I might very well be wrong.
DynamoInstall0.7.2.20140912T2235

**Comment by ksobon** [comment]
@andydandy74 you can use just a single quotation mark in this case to make it work. I think Code Block has gotten confused on syntax because normally when you place a \" it means that you want to indicate that " is a string so to print: konrad says "hello" you would do print("konrad says \"hello\""). It has something to do with string literals and escaping....anyways this works: 
![capture](https://cloud.githubusercontent.com/assets/529781/10328789/b2e5575e-6c86-11e5-8897-b0f1aff7bab2.PNG)

**Comment by ksobon** [comment]
Can we close this issue, or you still think that it should be addressed? It definitely messes up syntax highlighting but that might be another issue.

**Comment by andydandy74** [comment]
@ksobon - This was the workaround I ended up with eventually (another alternative is feeding the backslash from a ```String``` node). But I'd like to keep this open as there are definitely some issues with backslashes - even when escaping them:
![escaping](https://cloud.githubusercontent.com/assets/3014437/10329122/fa9d5dea-6cbc-11e5-808e-62300aca5732.PNG)
Since backslashes are regularly being used when construction file paths I think it's an important enough issue.

**Comment by aparajit-pratap** [comment]
@monikaprabhu could you log this. Thanks.

**Comment by ikeough** [comment]
@monikaprabhu @aparajit-pratap Was this ever logged? Is it still a bug?

**Comment by aparajit-pratap** [comment]
Fixed.
