### ISSUE TITLE
rescursion node doesn't run

### ISSUE THREAD

**Issue by PaulusPresent** [DynamoDS/Dynamo#2411]
Hey all,

I am trying to recreate the model in image attached using a recursion node. Each progression would generate another ring of beams attached to the previous ring = a reciprocal beam system.

The node structure as it is now doesn't run. Any help is greatly appreciated.

Kind regards

PS: How do I attach the dynamo file?

![knipsel](https://cloud.githubusercontent.com/assets/8777130/4269834/8c497224-3cc1-11e4-8b83-0a0537bfcfc0.PNG)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current Dynamo Public Roadmap.

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
