### ISSUE TITLE
Watch node not working - Revit 2014

### ISSUE THREAD

**Issue by pedmarco** [DynamoDS/Dynamo#2521]
Hi everyone, I'm using Revit 2014 and with both the 0.7.1 and the daily version of Dynamo I'm not able to see data inside any watch component.
![2014-09-24 14_12_58-dynamo](https://cloud.githubusercontent.com/assets/8898440/4387957/7547300a-43e4-11e4-8f16-cce37fe71ece.png)

I'm using an example to show you the problem.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
