### ISSUE TITLE
DSStackValue(sp?) Type leaking into Dynamo

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#2567]
I found this behavior after modifying a custom node to have multiple inputs, then duplicating another copy of the custom node and mapping it over a list.  One of the values of the custom node in the aggregated list was DSStackValue instead of a solid.

I have the file and custom node, but after rebooting Dynamo the problem is gone, so I think this bug was related to modifying a custom node that had more than one instance in the file.  Curious if anyone has seen before / has repro steps - will track internally.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
