### ISSUE TITLE
Watch 3d and Preview Background Grid should not contribute to Zoom to Fit

### ISSUE THREAD

**Issue by kronz** [DynamoDS/Dynamo#274]
If geometry is far from 0,0,0,  all geometry will be very tiny with Zoom to Fit
![2013-07-10_1332](https://f.cloud.github.com/assets/3456818/776475/f197e69a-e986-11e2-837e-33c037aef293.png)

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
