### ISSUE TITLE
Background Preview should Zoom to Fit on initial run

### ISSUE THREAD

**Issue by kronz** [DynamoDS/Dynamo#275]
When a user first activates Background Preview, it should execute a Zoom to Fit

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
