### ISSUE TITLE
dynamo won't open

### ISSUE THREAD

**Issue by minismore** [DynamoDS/Dynamo#2810]
Hello, 
After a single restart/reboot of my computer, dynamo will not open or load. It won't load as a standalone or through revit add-in. 

I have unistalled/reinstalled Dynamo 0.7.2 several times. The .exe shows up and takes up my memory under processes in windows task manager, but it doesn't continue to open. 

I've also tried to isolate the DynamoCore.dll file and delete it (read from an earlier blog about it causing issues when it is within Revit Installer folder) 

Within Revit, it shows that the Dynamo is running (it is grayed out) but it is not. It does not show up on the taskbar ribbon 

Any help or tips on dynamo install issues will be very helpful! 

Many thanks ahead!

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
