### ISSUE TITLE
Placing Legend Views on Sheets

### ISSUE THREAD

**Issue by ralvarez76** [DynamoDS/Dynamo#2985]
This does not seem to work with the "Sheet.ByNameNumberTitleBlockAndViews" method. Regular floor plans see to work just fine.

**Comment by rainesb** [comment]
Sheet.Views similarly breaks, returns 'null' if a legend is on a sheet with other (valid) views removing the legend from the sheet fixes the problem. Likely 'Legends' are not handled the same as 'Views' at some underlying layer in revit that Dynamo doesn't quite adress.
 Wish I knew enough to adress the problem better rather than just raising my hand. 
Oddly enough Dynamo would be a great way to consistently place legends on sheets since the basic Revit interface doesn't allow copy-paste in place to multiple views.

**Comment by ksobon** [comment]
This will be fixed here: https://github.com/DynamoDS/DynamoRevit/pull/1711 cc: @kronz

**Comment by ksobon** [comment]
@johnpierson this was actually fixed here if I am not mistaken. https://github.com/DynamoDS/DynamoRevit/pull/1909 Thanks for losing this.

**Comment by johnpierson** [comment]
Very cool. Thanks for referencing the PR @ksobon
