### ISSUE TITLE
Search Performance in 0.7 versions

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#3016]
I did a brief check to see if this had been reported at all...  if this is a duplicate, I apologize.  This is an issue I have noticed in 0.7 and it does not seem to have had any improvement in the latest builds (0.7.3 and 0.7.4 builds)

Search within Dynamo seems quite slow and cumbersome at the moment.  As a type queries in the search bar, there is almost always a delay in returning a list of possible nodes.  Sometimes this is up to a second or more (esp. when a node is being searched for the first time.)

Is search performance being addressed at the moment?  This seems to weigh heavily on the user experience.

-Nate

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
