### ISSUE TITLE
UDP Listener is not working?

### ISSUE THREAD

**Issue by s-overall** [DynamoDS/Dynamo#306]
I'm a little uncertain about this particular issue, it isn't something I have much experience with, but I can't seem to get the UDP listener node to receive any data.

You can see below that I am trying to send data out from Grasshopper via a UDP Sender into Dynamo using the loopback address.  The UDP Listener inside of Grasshopper is able to listen to the data as expected, but the Dynamo node is not picking up any data.  Is this an issue with the way I have the listener set up or a bug?

![udp interface](https://f.cloud.github.com/assets/4680004/842137/330ce45e-f3a5-11e2-9941-055ac1e585a1.JPG)

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
