### ISSUE TITLE
Namespace Collisions with 3rd Party Packages (e.g. Rhynamo)

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3208]
I noticed this when wanting to create points. Autocomplete behaviour before installing Rhynamo:
![ac1](https://cloud.githubusercontent.com/assets/3014437/5136488/3b24e792-7129-11e4-9b2d-c2ffe426743f.PNG)
And after:
![ac2](https://cloud.githubusercontent.com/assets/3014437/5136490/3b27c9a8-7129-11e4-936a-9416c6a0375a.PNG)
So ```Point``` now needs to be called as ```Autodesk.DesignScript.Geometry.Point```. Which is not good at all because it means existing scripts won't execute:
![acwarning](https://cloud.githubusercontent.com/assets/3014437/5136489/3b261f4a-7129-11e4-8357-501d094ddbad.PNG)
I find it odd (and actually a bit disconcerting) that third party DLLs can have that kind of effect on Dynamo core functionality.
CC @archinate

**Comment by andydandy74** [comment]
Glad to see that this is partially fixed in 0.8 RC.
Here's a description of the new behaviour:
1. Entering ```Point``` in a CBN for the first time will still yield the following result in autocomplete:
![point-autocomplete](https://cloud.githubusercontent.com/assets/3014437/6884216/a44913bc-d5e5-11e4-81a7-d7e41a4de9fb.PNG)
(So at that point it still *looks* broken...)
2. Entering ```Point.``` will make Dynamo autocomplete this to ```PointAnalysisData.``` - not quite what I was after.
3. Manually correcting this again to ```Point.``` will bring up the following message in the console:
```Failed to perform code block autocomplete with exception:
Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Dynamo.DSEngine.CodeCompletion.CodeCompletionServices.GetCompletionsOnType(String code, String stringToComplete, ElementResolver resolver)
   at Dynamo.UI.Controls.CodeBlockEditor.GetCompletionData(String code, String stringToComplete)
   at Dynamo.UI.Controls.CodeBlockEditor.OnTextAreaTextEntered(Object sender, TextCompositionEventArgs e)```
4. I can manually complete the statement like so: ```Point.ByCoordinates(0,0,0);``` and it will execute. Nice!
5. And now it gets really strange: After having typed in the command manually once, it will appear in the autocomplete suggestions without ```Autodesk.DesignScript.Geometry.``` in front of it:
![point-autocomplete2](https://cloud.githubusercontent.com/assets/3014437/6884247/626fe3b0-d5e7-11e4-9396-9a2e037e9c78.PNG)

Expected behaviour: Autocomplete for ```Point``` (and not ```Autodesk.DesignScript.Geometry.Point```) should be available right away without having to jump through these hoops.

**Comment by aparajit-pratap** [comment]
@andydandy74 thanks for pointing out this discrepancy. The first auto-complete list where all the conflicting namespaces are displayed on typing `Point` is expected. The system cannot automatically differentiate between classes with name `Point` that occur in different libraries (in this case Dynamo itself and Rhino both have classes `Point`). Autocomplete therefore has to display the fully qualified names to the user so that the user can explicitly specify which of these `Point` classes he intends to use when he simply says `Point`. 

Secondly if autocomplete displays multiple options for `Point`, it means that the code block cannot resolve just `Point` as a class name. It needs to know additionally which namespace it comes from - `Autodesk` or `Rhino`. Therefore, I agree with you that the fact that `Point.ByCoordinates(0,0,0);` executed successfully, is actually confusing because in reality it should have failed. There is a discrepancy in the engine core, which is being tracked as a bug here and will be resolved soon: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6838

**Comment by aparajit-pratap** [comment]
Also conflicting namespaces are now shortened into shortest names that can be uniquely resolved. For example, `Autodesk.DesignScript.Geometry.Point` and `Rhino.Geometry.Point` will now be shortened and displayed as 'Autodesk.Point` and 'Rhino.Point` resp. You may see this in the latest daily build: https://github.com/DynamoDS/Dynamo/pull/4060

**Comment by andydandy74** [comment]
From a user perspective (or you might as well call it my personal bias) I would say that it would make a lot of sense to find a solution where Dynamo's own library *always* takes precedence. Imagine what would happen if somebody made a package for, lets say geometry conversion to another software / file format that had a lot of commands with names of generic geometric entities like ```Point```, ```Vector```, ```Curve```, ```Surface``` etc. In that case I as a user would have to choose between:
a) Explicitly calling the Dynamo methods each time I use a code block,
b) not using code blocks any more for operations like that because they've become a nuisance or
c) uninstalling the 3rd party package.
I know that I, for one, would *not* pick option a). 
@aparajit-pratap - If I understood you correctly, you're saying that after the resolution of the "discrepancy" in the engine, a statement like ```Point.ByCoordinates(0,0,0)``` would not execute any longer in the scenario I described in my previous post. Please consider the following scenario and its ramifications:
Person A uses code blocks in custom nodes without explicitly calling ```Autodesk.DesignScript.Geometry.Point``` (because he has no "interfering" 3rd party package installed). He then publishes it to package X. Person B installs package X and also another package like Rhynamo that adds a second ```Point``` class. This would effectively render the affected nodes in package X useless.

**Comment by aparajit-pratap** [comment]
Yes that's right, resolution of the engine issue will no longer execute the statement `Point.ByCoordinates();` in the above scenario. You will have to specify `Autodesk.Point.ByCoordinates();` or the fully qualified `Autodesk.DesignScript.Geometry.Point.ByCoordinates();` for it to work. We did consider giving a preference to all Dynamo native classes without having to specify namespaces for them however decided not to take that route for various reasons. 
Even in the case where you have class conflicts and have to use native Dynamo classes, I don't see why you would need to "explicitly" call them as autcomplete will still display them, but only with a prefix of `Autodesk.` which you will have to pick. 
As for your concern about the following scenario:
"Person A uses code blocks in custom nodes without explicitly calling `Autodesk.DesignScript.Geometry.Point` (because he has no "interfering" 3rd party package installed). He then publishes it to package X. Person B installs package X and also another package like `Rhynamo` that adds a second `Point` class. This would effectively render the affected nodes in package X useless."
... this issue has already been taken care of: https://github.com/DynamoDS/Dynamo/pull/3255

You can try it out just as you said:
Open a clean Dynamo version without any 3rd party packages /libraries installed. You should be able to use `Point` as is in a code block node. Save the file (DYN/DYF) with the CBN using `Point`. Import libraries that introduce conflicts with `Point` such as `Rhynamo`. Open the file. Your code block using `Point` should continue to work as before as `Point` has been internally mapped to `Autodesk.DesignScript.Geometry.Point`. Now if you type `Point` in a new code block you will simply see `Point` and `Rhino.Point` in autocomplete as the system now knows how to resolve `Point` and needs just one additional qualifier to distinguish it from `Rhino.Point`.

**Comment by andydandy74** [comment]
@aparajit-pratap - thanks for clearing that up. One less thing to worry about. :-)
