### ISSUE TITLE
Sample Files

### ISSUE THREAD

**Issue by bdmackey** [DynamoDS/Dynamo#333]
This isn't a bug but a confusion issue.

Newest release had Number Sequence as well and Number Range

New Number Sequence = Old Number Range

Sample file Scalable Circle uses old Number Sequence and when users try to recreate it using the NEW Number Sequence it doesn't work it should use new Number Range.

Confusing for users mimicking sample videos etc that have been created previously.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
