### ISSUE TITLE
Length display units vs dynamo API unit

### ISSUE THREAD

**Issue by eertugrul** [DynamoDS/Dynamo#3420]
I have noticed everything that is modeled in dynamo is in meters.(please correct me if I am wrong) if I change the display units to feet, the double value I have set (unitless) as 10 is actually 32.808 ft, which is 10 meter.
![image](https://cloud.githubusercontent.com/assets/4672688/5420429/52d0ebd8-8223-11e4-90ae-ef975662a62f.png)

so I have a dilemma here: I am making a connection dynamo to a 3rd party modeling/analysis platform. So the user should be aware the parametric model in dynamo is always in meters. So we can do the conversion correctly from meters to whatever the platform we are sending to and the way back. From a user point of view I think this is very confusing. People might think they model in display units not in meters !

I think it would be better especially when do parametric modeling, the values units should match whatever the host platform's units or if it is standalone version should match the display units.

@ikeough any enchantments are planning on units in the near future ? Thank you

**Comment by dbaldacchino** [comment]
@ikeough units still seem to be an issue when python nodes are used to retrieve data from Revit. For example when extracting geometry from rooms to build filled regions as explained in the post below, a  (incorrect) conversion happens when units in the Revit project are set to metric.

http://dynamobim.org/forums/topic/filled-region-by-room-boundary/#post-43662

Any plans to fix this? Thanks.

**Comment by dbaldacchino** [comment]
Actually I need to make a correction: the incorrect conversion issue exists if units are set to anything BUT feet. If units are set to inches for example, then an incorrect conversion is still being made (x12).

**Comment by jnealb** [comment]
@dbaldacchino We provide an explicit Convert Between Units node; does that help?

**Comment by mjkkirschner** [comment]
I think this is just how the RevitAPI works, and we're not doing any type of conversion. @ikeough can correct that if I'm wrong. I think what you want to do, if you are using our wrappers and revit services libraries in python is to call InHostUnits() on the geometry which will scale the geometry based on the host unit of revit's project.

**Comment by dbaldacchino** [comment]
Thanks all. Well, I thought that Dynamo now works seamlessly with the units specified in Revit. The example on the forum is something I was working with and I know I'll be running into this exact issue as the graph I'm coming up with will be used on both Imperial and Metric (take slab boundaries and create filled regions using those same boundaries). So unless I'm misunderstanding, I was expecting Dynamo to yield expected results regardless of Revit units, without having to manually do any conversions.

**Comment by dbaldacchino** [comment]
Thanks Michael @mjkkirschner , I'm really not very well versed in Python and the Revit API so it will take me a while to reverse engineer an example from somwhere to test that. Now if only there was a native node that created filled regions from boundaries :)

**Comment by dbaldacchino** [comment]
Ok so I just found another Python example by user Organon that behaves exactly as I expected, with no scaling issues when units are changed:

http://dynamobim.org/forums/topic/filled-region-from-room-boundary/

Might need to steal some code from this and adapt, although I still don't understand how to get it to update the filled regions instead of creating new ones each time, but that's taking this thread off-course.

**Comment by ikeough** [comment]
@dbaldacchino As @mjkkirschner mentioned, `InHostUnits(...)` needs to be used when you are using python to get geometry out of Revit. The reason for this is that we cannot know that you are in python to make the conversion for you automatically, like we do when you are using the Revit Nodes. As such, we don't have plans to "fix" this. Without conversion, all of your geometry will come back from the Revit API in decimal feet, because that's the units in the Revit API.

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
