### ISSUE TITLE
Feature Request: Ceiling.ByOutlineTypeAndLevel

### ISSUE THREAD

**Issue by seandburke** [DynamoDS/Dynamo#3439]
Similar to the Floor.ByOutlineTypeAndLevel, we should be able to also make ceilings. This would avoid the common issue of when Revit auto-ceiling sketch is used to make ceilings, where they break when the wall bounding elements are edited.

**Comment by johnpierson** [comment]
I definitely would appreciate this functionality too! Here we are 4 years later and the Revit API still does not allow this. Turns out there is a Revit Idea for it here, https://forums.autodesk.com/t5/revit-ideas/create-ceilings-via-dynamo-or-api/idi-p/6618383. I suggest voting on that idea to see if we can make it happen. I will go ahead and leave this open for tracking.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2182).
