### ISSUE TITLE
PolyCurves

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#3451]
I am looking at breaking down and extracting sub curves of a PolyCurve() class. When I query all of the curves contained withing polycurve.Curves() it returns a list of "Curve" objects. Why doesn't it return the actual objects that "curve" class represents here (Line, Arc, NurbsCurve etc)? 
Is there a method that I am missing here to check if "Curve" is Line, NurbsCurve etc? 
I can only seem to be able to convert them to Nurbs using ToNurbsCurve() but that's really a waste. 

Ideas?

**Comment by teocomi** [comment]
Just wanted to bump this issue, it's still happening in Dynamo 1.3. 
It would be nice to get the original geometry when decomposing a polycurve:

![image](https://user-images.githubusercontent.com/2679513/28210342-c27acbd0-688e-11e7-8ee8-62bc7d8919aa.png)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current Dynamo Public Roadmap.

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by aparajit-pratap** [comment]
This has finally been fixed. It should come in Dynamo 2.8. Removing the `DidNotFix` label.
