### ISSUE TITLE
Self-Intersecting Surface Not Allowed

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#3487]
I'm currently writing some nodes that allow users to generate mathematical shapes, but it looks like Dynamo does not allow "self-intersecting" surfaces to be created.  It even gets touchy if surfaces meet at a single seam (in most cases)

I am using NurbsSurface.ByPoints()

"It's as if millions of Klein surfaces cried out in terror... and were suddenly silenced."

![image](https://cloud.githubusercontent.com/assets/1890663/5591127/a31bb11c-9110-11e4-9790-18675dc67baa.png)

**Comment by lukechurch** [comment]
@pboyer @hlp @Randy-Ma

**Comment by holyjewsus** [comment]
I remember @tatlin mentioning something about this with his costa minimal surface work, I thought he had made the resulting surface by splitting it automatically on an isoline.

**Comment by hlp** [comment]
Hi Nate,
We've logged this on our internal bug tracker.

**Comment by ikeough** [comment]
@ptierney Do you know what the tracking number is?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current Dynamo Public Roadmap.

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
