### ISSUE TITLE
TransactionManager

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3520]
I just have a question:
is the TransactionManager capable to RollBack a transaction?
Tx Peter

**Comment by ksobon** [comment]
you can just create a regular transaction. Here's an example: 

```python
trans = Autodesk.Revit.DB.Transaction(doc, "Temp Transaction")
trans.Start()

schName, schId, ids = [], [], []
for i in elements:
	ids.append(doc.Delete(i.Id))
trans.RollBack()```

**Comment by epeter-** [comment]
konrad, thanks for your reply, i use the same technique for transactions.
i was just feeling like if there is a "transactionmanager" provided, he should be capable of managing at least the basic transactions required, including rollback.
tx peter

**Comment by Steell** [comment]
The Dynamo transaction manager manages the global transaction which the
entire Dynamo graph is evaluated in. Because your python script is part of
the graph, it is operating within the same transaction context as any Revit
nodes also in the graph.

For safety purposes, we disallow rolling back the global Dynamo
transaction. This is done to prevent potential graph de-synchronization. If
you need to rollback a any transaction that you're working on in a Python
script, use a Revit `SubTransaction`. Instantiating a new Transaction like
Konrad suggested will not work in cases where Dynamo has already initiated
the global Transaction before the Python script has run.

**Comment by epeter-** [comment]
@Steell : I found out. and learned that there are SubTransactions. 
that was tough for me as Architect with limited coding skills.

**Comment by ksobon** [comment]
In that case just use ```trans = SubTransaction(doc)``` , then start it ```trans.Start()``` and then roll it back with ```trans.RollBack()``` or commit with ```trans.Commit()```

**Comment by ksobon** [comment]
@Steell Thanks for clarifying how the "global transactions" work. I had some issues with it before and this will certainly help.

**Comment by ksobon** [comment]
@Steell would you be kind enough as to post an example of utilizing SubTransaction() to do some operation that normally requires doc.Regenerate() in order to execute properly. What I am referring to is a situation where I am creating a new element inside of Python node and in the same node I am trying to extract some information about that element/set its parameters. What normally happens is that until model is regenerated that newly minted elements are not properly recognized as part of Revit DB. 
I tried that with Schedules where I create a new Row, and then try to set parameters for that row. It doesn't work until I re-run the graph multiple times as if its not possible to create a new row and set its parameters in one transaction. I later separated those two actions into two Python nodes and it worked fine. I also, tried putting them into separate SubTransactions inside of the same Python node but that didnt work.

**Comment by Steell** [comment]
@ksobon If you need regeneration to take place, you can use `TransactionManager.Instance.ForceCloseTransaction()`. This will commit the global Dynamo transaction and cause the document to regenerate. `SubTransactions` are not a complete replacement for the `TransactionManager`:  if your Python script is using them, then the script should *still* start with `TransactionManager.Instance.EnsureInTransaction(doc)`. This will start the global transaction if it hasn't been started already, that way your `SubTransactions` can work (they are called __sub__ transactions because they require an active regular `Transaction`). Also, make sure to end your Python script with `TransactionManager.Instance.TransactionTaskDone()` as well.

You really only need `SubTransactions` if you need to rollback some changes you're working on in the Python node. The `TransactionManager` should be used no matter what.

Also, if after you use `ForceCloseTransaction()`, if you need to do work inside of a new Transaction, you can use `EnsureInTransaction(doc)` again.

```python
TransactionManager.Instance.EnsureInTransaction(doc)

trans = Autodesk.Revit.DB.SubTransaction()
trans.Start()

# do some stuff

if not success:
  trans.RollBack()
else:
  trans.Commit()

  TransactionManager.Instance.ForceCloseTransaction() # regenerates the document

  # do some stuff

  TransactionManager.Instance.EnsureInTransaction(doc)

  # do some stuff that requires a transaction

  TransactionManager.Instance.TransactionTaskDone() # we're done
```

**Comment by ikeough** [comment]
@ksobon Is the provided example enough to go on?

**Comment by ksobon** [comment]
Yeah i am fine. Thanks!

**Comment by mfleming04** [comment]
How do you properly Name your Transactions using the above?
I would normally want to use something like the below, but that isn't working in this case.

`# Defines a Transacation which includes the current Document
t = Transaction(doc, 'Create multiple family instances.')

# Starts a Transacation
t.Start()
t.Commit()`

attempt the obvious and no go.
`TransactionManager.Instance.EnsureInTransaction(doc, 'Create Family Types')`

What basic step am I missing?

Matt
