### ISSUE TITLE
feature request: create walls by profile

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#3546]
feature request: create walls by profile

**Comment by monikaprabhu** [comment]
@marcellosgamb ,We already have an Wall.ByCurveheight,Im sure you have taken a look at it . What additional setting are you looking at , you need the height also governed by profile ? 
Im tracking it here in MAGN - 5820 - I need to add more details to the story.

**Comment by andydandy74** [comment]
It's about creating walls based on non-rectangular profiles. There are 3 creation methods for this in the Revit API:
- http://revitapisearch.com/html/d2848332-daca-2bf1-4aca-21ea21937758.htm
- http://revitapisearch.com/html/8d651eae-ae63-bc50-5f43-383d71ec4301.htm
- http://revitapisearch.com/html/6c247699-c8e5-91df-67f7-470d10fa7ba3.htm

I would think that number three makes the most sense since it's the only one that will let the user specify all important properties of the wall (including orientation).

P.S.: Since you guys are going to work more closely with the Revit API team this year, how about exposing the ability to *edit* the wall profile of an existing wall in the API (or the path of a wall for that matter, or recomputing a FaceWall after the underlying geometry has changed)? Currently, operations like these require the creation of a new element (and thus, a new ID - which is never a good thing).

**Comment by monikaprabhu** [comment]
@andydandy74  Thanks!We have added the details to story - 5820.

**Comment by johnpierson** [comment]
Closing this as it is available in Wombat package. If this is still a feature request for you as an OOTB node, please open on the [Revit issues](https://github.com/DynamoDS/DynamoRevit/issues) page.
