### ISSUE TITLE
Select Elements node

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#355]
This node should let the user make a multi-element selection by Ctrl + clicking and not just through a box selection.

**Comment by smangarole** [comment]
This issue will be addressed when we process all D4R issues. 
Thanks.

**Comment by ramramps** [comment]
@smangarole Just checking because we did fix for 2.0. Is this something that was addressed in 2.0?

**Comment by johnpierson** [comment]
This is still a wishlist item for sure, (updated the labels). Would love a node that utilizes the [PickObjects ](https://apidocs.co/apps/revit/2018.2/e5a547a2-3cf5-7638-2daa-ea85b4d3de2d.htm) method. It would be great to have one for filtered selections, and one just for picking any objects with a finish button in the contextual ribbon.

I actually added a filtered pick objects method to Rhythm quite a while back because I wanted the functionality so bad,
![20181004-355](https://user-images.githubusercontent.com/15744724/46477635-50460780-c7a8-11e8-97fd-220ae8c8b6f3.gif)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2201).
