### ISSUE TITLE
reference curve node should accept curve loops

### ISSUE THREAD

**Issue by kronz** [DynamoDS/Dynamo#359]
Currently you need to put a "curve loop list" node between a curve loops and reference curve node.  Should be an auto-convert.  Downsides?

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
