### ISSUE TITLE
Structural Framing and curves

### ISSUE THREAD

**Issue by hsveinbjorns** [DynamoDS/Dynamo#3627]
I am drawing reinforcement into a retaining wall, and I am having trouble placing rebars on faces.

Is it possible to make Structural Framing beams with Nurbs Curves?

**Comment by hsveinbjorns** [comment]
Anyone? Is it possible to draw stuctural framing beam with a polycurve/Nurbscurve? Am really stuck on this problem and would really like some help.

**Comment by dimven** [comment]
It works but you have to make sure your NurbsCurves are at least of degree 3(that means at least 4 control points) as described here by ksobon:
https://github.com/DynamoDS/Dynamo/issues/3689
![2015-02-05_122334](https://cloud.githubusercontent.com/assets/7148394/6055066/8fa076a2-ad32-11e4-8ef9-812fad4aed40.jpg)

Also it seems Revit is not happy if your curve is not planar:
![2015-02-05_122358](https://cloud.githubusercontent.com/assets/7148394/6055068/96e5c156-ad32-11e4-921f-7489dd3e0555.jpg)

**Comment by hsveinbjorns** [comment]
Thank your for your comment @dimven . My NurbsCurves are of third degree, but I am trying to draw the object in height and coordinates so keeping the surfaces in plane is kind of difficult. Here is my dyn file (Used information from https://aecuandme.wordpress.com/ ) It works fine as long as the surface is in plane...

![2015-02-26 rebar on face](https://cloud.githubusercontent.com/assets/10709896/6388840/02b1a04e-bd96-11e4-8b4b-b8f1442fd42a.PNG)

If anyone has ideas how to work around this, I would really appreciate it!

**Comment by dimven** [comment]
That looks like an older version of dynamo. There were some updated nodes for framing after 0.74. Do you mind trying with one of the newer versions of Dynamo?

**Comment by hsveinbjorns** [comment]
![2015-02-27 rebar on face](https://cloud.githubusercontent.com/assets/10709896/6416868/3cb837c4-bea1-11e4-8a7a-0fa0acdf2d57.PNG)

My Dynamo said it was up to date, but I still downloaded it again (0.7.5). Changed the framing node to StructuralFraming.BeamByCurve, and still have the same issue. 
As you can see, the curves aren't extreme. There is slight change in elevation along the way (106mm).

**Comment by dimven** [comment]
If you don't mind sharing your definition and revit face, I could have a look and see if I can help in any way.

**Comment by hsveinbjorns** [comment]
Thank you @dimven. Sorry about the delay, busy period at work. I have created a repository and put by Revit and Dynamo files in there. The problem seems to be that the faces aren't planar. Hope your offer still stands about the help :)

**Comment by dimven** [comment]
I'll have a look during the weekend. I checked out your repo, but it seems it's still empty.

**Comment by hsveinbjorns** [comment]
I put the files under "Releases", didn't find another way to upload them... Thank you again.

**Comment by dimven** [comment]
Hi Helga,
I checked out your file and I have a few suggestions. I suspect that the
problem stems from the fact the model-in-place wall's path is following an
edge hosted in the road family, instead of an edge hosted in the project
file itself and that may lead to very fine tessellation of the path's
curve. And due to the fact that the surface is extrapolated from the path,
that leads to an over-complicated surface as well. That is why only the
longitudinal rebar is failing (the one that follows the path) but the
perpendicular rebar is working without a hitch.

You can download the updated version from the following link:
https://www.dropbox.com/s/j495hotbh9i41ds/Rebar%20on%20face.zip?dl=0

I've tried to simplify the dynamo graph a bit. I also approximate the
longitudinal rebar enough, so that it can be passed along through the
framing creation node.

Good luck!
