### ISSUE TITLE
Need a way to make lacing only apply to certain ports

### ISSUE THREAD

**Issue by Steell** [DynamoDS/Dynamo#371]
The __Get From List__ node should lace the _index_ input, but should not lace the _list_ input. Right now, lacing is implemented for all ports or no ports, so there's no way to accomplish this.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
