### ISSUE TITLE
How to access the InPort Data in an UI Node

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#3770]
Hello everyone,
we're trying to work with the UI Nodes in Dynamo. The node sample (HelloDynamo in SympleLibraryUI) is working fine, also our XAML modification. But we don't manage to access the InPort Information. Just to hand through the InPort data and some additional data created within the node like in the sample. But we like to hand in a list and modify the items within the list.
Thanks, Fabian

**Comment by holyjewsus** [comment]
Have you looked at getmirror() in this sample?
https://github.com/DynamoDS/Dynamo/wiki/How-To-Create-Your-Own-Nodes

**Comment by holyjewsus** [comment]
if I'm understanding correctly on second reread you want to look at the buildOutputAst method, it's briefly explained in the sample,  you need to build the expressions that represent the transformations or function calls you want to perform on your data, you can see in the sample that the outputs are assigned from inputs like this:
 AstFactory.BuildAssignment(
                    GetAstIdentifierForOutputIndex(0), AstFactory.BuildExprList(inputAstNodes)),

which puts the input on output 0 of the node

**Comment by ikeough** [comment]
If the node is only modifying the items in a list, then passing the modified list out, I would make a method that modifies the list as you would like and returns a list, then use a FunctionCallNode in your generated AST to call that method. Using the GetMirror() method should be avoided unless you need to know something about the incoming list to populate your UI. It's not great to use that because your node model then requires a reference to the EngineController, which is possible, but is something that we don't like to recommend.

**Comment by redinkinc** [comment]
Thanks to your quick responses. I now have a clue how it might work. I'm right now also thinking about a node where I get have a hashtable as input, create a dropdown displaying the keys as items in a dropdown and return the corresponding value. there I think I have to use the GetMirror() method. Also the Watch2D node seems missing (see issue #3271) and I'm right now trying to implement it. 
Since my question of this issue is answered right now I will close this issue and come back if I need any further help.
Thanks, Fabian
