### ISSUE TITLE
Possible bug when writing parameters of length

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#3859]
Probably you know about this and the solution is on the way, but in any case….

Typical scenario: I have a project in revit in mm. I extract some geometry with Dynamo and because Dynamo internal units are in meter  the results are in meter. Imagine a Point with X=100000mm in Revit. When I extract the X coordinate in Dynamo the value is 100, as expected. Everything is fine until now.

But now I want to write that value to a parameter of an entity of Revit, so I can extract that information in Revit without having to run the dynamo file. I use SetParameterByName. The type of parameter is Length.

When later I check the parameter in Revit I will see that the value is ….30 480, which is exactly 100 feet in mm. So when dynamo is writing the value is “forgetting” that its own internal units are meter.

Adding just  *3.2808399 before writing the parameter will take care of this. But can be extremely confusing at the beginning if you don’t know what is going on.

**Comment by jbenoit44** [comment]
same here. pushing correct value from dynamo to revit I get an Imperial result in Revit schedule.
dynamo 0.7.6.4186

**Comment by dimven** [comment]
Correct me if I am wrong, but that has been the case ever since the transition to 0.7, no?

**Comment by monikaprabhu** [comment]
This is fixed in 8.0-Dynamo will use the same units specified by Revit if you are pushing any modifications to Revit. I've tested this SetParameterValue which is reported as an issue above. Please try the latest build - Units are changing- for more details you can read Blog by Our evangelist found here-http://dynamobim.com/units-in-dynamo-0-8-2/
![untitled](https://cloud.githubusercontent.com/assets/5218721/6914660/64c9d588-d7bf-11e4-8450-e252b5007f4f.png)
