### ISSUE TITLE
Limited usability of  "ParameterTrimStart" and "ParameterTrimEnd"

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#3895]
This is a question to @pboyer and @hlp 

The methods "ParameterTrimStart" and "ParameterTrimEnd" work only for simple single curves. If you try with a polycurve they are not working. Or if you try with a more complex curve, like for example if you extend a polycurve (the result is listed as "curve") they are not working.

It is really a pity, because these methods can be really useful. 

A bit of time ago it was discussed here to make available many methods for both curves and polycurves, without having to use a different specific one. And most of them are currently working perfectly and it is really great. Just in a few, like these two, we are not there yet.

**Comment by ikeough** [comment]
@hlp what do you think?

**Comment by hlp** [comment]
I've logged this bug. Thanks for reporting it @eproca !

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
