### ISSUE TITLE
transactions

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4058]
transactions don't seem to be comitted() as expected.
Trnsactionmanager is unloaded!!!!!!!!!!!!!!!
so i would expect that transactionhandling ist done by me?

example 
....
for i in x:
         t1 = Transaction(doc)
         t1.Start("pls do what i need")
          .....do something
          t1.Commit()
          t2 = Transaction(doc()
          t2.Start......
          t2.Commit()

error:

Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
Traceback (most recent call last):
  File "<string>", line 47, in <module>
Exception: Starting a new transaction is not permitted. It could be because another transaction already started and has not been completed yet, or the document is in a state in which it cannot start a new transaction (e.g. during failure handling or a read-only mode, which could be either permanent or temporary).

i'd expect that t1 is commited and t2 is commited for the loop.

**Comment by ksobon** [comment]
@ikeough this is all happening because DynamoRevit itself is an external command that automatically opens a transaction. Isn't that right? If that's the case than users should not manually create new transactions directly in API without use of `DocumentManager` or if they do so, please make sure that they check if there is a transaction open and close it before starting a new one. 

I don't see anything wrong with how its currently implemented. 

cc: @kronz if you agree we can close this issue or at least request more info from the OP.
