### ISSUE TITLE
Dynamo General Performance

### ISSUE THREAD

**Issue by urosjovanovic** [DynamoDS/Dynamo#4106]
Having a model with at least couple of hundred nodes (including the ones in custom nodes) the run time is painfully slow (10-15 minutes). The nodes are primarily basic inputs and geometry operations, generating complex 2D line profiles. Granted, some optimization to the model can and must be done, I am in process of condensing nodes into code but I was wondering, performance wise, is it faster to write somewhat big Code Block Nodes or use Python Scripts? Or maybe write custom nodes in C#?

**Comment by ke-yu** [comment]
hi @urosjovanovic , sorry I can't give you a concrete answer yet. For performance it could because of multiple reasons. If the CPU time mostly spent on geometry functions, then using code block node or use Python Script probably won't be much helpful. If there are big arrays in the graph, then writing Python script or optimized code may help to avoid some unnecessary memory copy operation and improve performance. If using a lot of high order functions like `List.Map` , which are slow, or having quite heavy computation in the graph, then writing Python script or implementing in C# would be faster.

**Comment by monikaprabhu** [comment]
@urosjovanovic Could you also post or send your file to us- we can help you explore a better workaround.

**Comment by ikeough** [comment]
@urosjovanovic Any update here. Do you have a reproduction case that we can test?

**Comment by ke-yu** [comment]
Close as not enough information to do further investigation.
