### ISSUE TITLE
passing data - Python creates extra list

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#4209]
Hi i would like to create a container node that only passes unchanged data in dynamo, but when i create it in python it adds extra list layer. thanks

![image](https://cloud.githubusercontent.com/assets/4834544/7063837/529a3f28-deaa-11e4-81bc-2eb974828b8a.png)

**Comment by dimven** [comment]
That's the expected behavior. Notice the "+" and "-" signs on the node. The Python script takes in exactly one list and spits out exactly one list as well. However the two can have numerous sub-lists. You can define each sub-list as a new separate variable with the help of indexing.

If you want to reduce the rank of your list, you should specify the specific input like so:
OUT = IN[0]

**Comment by monikaprabhu** [comment]
@dimven is absolutely right!Im closing this issue.
