### ISSUE TITLE
UI/UX Wish / Feedback:  More Straightforward Tree View of Nodes (0.8+)

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#4228]
Hello all,
Here is some feedback from recent workshops and my own personal exploration of Dynamo 0.8...  the introduction of icons is pretty cool, but the UI for navigating the library has become much more complex and confusing.  The user must now use three 'styles' of navigation to reach their nodes.  I found the previous (0.7 and earlier) tree view is far more navigation friendly.  Why not just introduce icons to the old navigation?

The following is an attempt to explain why this new UI is confusing to both myself and, especially, new users.

Starting out:  When starting Dynamo, the library gives the expectation of a "tree"-style UI like the previous versions and most other programs.
![image](https://cloud.githubusercontent.com/assets/1890663/7106251/6468e986-e100-11e4-9a3c-9881e237df87.png)

Expanding the Tree:  Expanding the "Core" library, I am now presented with a grid of icons.  My first reaction is "ah, cool! node icons!"   At this point I am expecting that Tree = categories, Icons = nodes.
![image](https://cloud.githubusercontent.com/assets/1890663/7106328/02a7c36e-e102-11e4-9445-82ff39748f35.png)

Confused Navigation:  This is where things get muddy.  Upon clicking on any these icons, it is revealed that icons are actually categories, too.  Clicking on any of these icons, the interface now introduces a "tab"-style navigation with nodes represented as a "list".  At this stage, the user has gone through 3 styles of navigation to get to a node...
1.  Tree Names
2.  Icon Grid
3.  List of Icons
![image](https://cloud.githubusercontent.com/assets/1890663/7106339/90ef66cc-e102-11e4-865d-ff23408c6a96.png)

As we continue to expand icons and look around, the navigation becomes nearly incoherent... I see category icons, node icon lists, and trees all at once.  Where should I click?
![image](https://cloud.githubusercontent.com/assets/1890663/7106386/6a7044f6-e104-11e4-82ea-c2720164a45b.png)

Tree View is Much Easier:  Now let's contrast this with the basic 0.7 tree view.  It is very straight forward.  It isn't as "pretty", but Icons could easily be added to this without the need for additional navigation UI.

![image](https://cloud.githubusercontent.com/assets/1890663/7106434/5233a70a-e106-11e4-8566-ecd795f36e79.png)

**Comment by pboyer** [comment]
@elayabharath @lillismith

**Comment by williamwong** [comment]
@archinate there's one more additional layer too...the separation of Action and Query nodes, which from a UI standpoint are similar to tabs, but have a different visual look than the actual tabs. I completely agree that there are too many visual metaphors that make it difficult to navigate to find nodes.

These problems are compounded by the fact that the alternative to navigating the tree to find nodes is by searching, but the autocomplete in the search box is erratic. While I appreciate that custom nodes can include search terms as hints for the autocomplete, it is extremely frustrating when I install a new package to find that the new nodes can sometimes supercede existing core nodes in the search results. I've gotten pretty familiar with essentially typing out the entire namespace to find the nodes I need, but this is a major frustration for new users.

**Comment by archinate** [comment]
@williamwong I completely agree with this.  In fact, when I was first using the new interface, I didn't realize "Action" and "Query" were buttons.  I thought they were headings or labels.

I also agree that autocomplete is very erratic.  For me, the bigger issue with search has always been that it is sluggish overall.  It will "hang" after typing in the first few characters.  This has continued with 0.8 versions.  I reported this as issue #3016 some time ago.

**Comment by archinate** [comment]
Also...

Is there a reason why the Geometry tab is always expanded when first opening or starting a new file?  It's a super minor complaint.... but it's kind of annoying to have to always minimize it when starting up a new definition.

![image](https://cloud.githubusercontent.com/assets/1890663/7123981/7acf1fec-e1eb-11e4-840f-a529c95c00e0.png)

**Comment by elayabharath** [comment]
Hi @archinate and @williamwong, 

Excellent points both of you, thanks for bring this up. My thoughts..

1. Library navigation: The new library UI was designed to aid exploration - is particularly against burying items way too deep in the tree. So this design works well for up to 3 levels. Example Geometry > Point > ByCoordinates

As a consequence, any library that is too bloated with items buried too deep surfaces as a problem in navigation. E.g. Core > File deserves to be a separate category by itself just like Geometry. This will have to be fixed by reorganizing the library, which is happening soon in the next weeks. 

This way the third party developers are also nudged to keep their library flat. Your thoughts?

2. Actions / query tabs: My idea is that the library should primarily be used for creating new things, rather than querying for properties or actions. These properties and actions work well when given in context - on top of the node itself. Example to access if you want to apply translate action or query for X values over a point..

(this long node is hypothetical and only for mock up purposes)
![image](https://cloud.githubusercontent.com/assets/4365353/7134167/d9bb8d10-e2cc-11e4-9b08-c3a0879c07d4.png)
![image](https://cloud.githubusercontent.com/assets/4365353/7134175/e203ba7e-e2cc-11e4-85e8-3bed26f31784.png)

I agree we landing the library UI without this feature is an early move, but this feature is being worked on as we speak.

More info here: https://docs.google.com/document/d/1GY4Fmx6DBeY_oD52erWOn4CBE5yGatHW3n3cfuFcGq4/edit#bookmark=id.edhgxhs9wq5e

3. Opening the Geometry was an experiment to aid the first time users to give some hint. Noted about the annoyance, happy to collapse it for non-first time users.

4. I will have to investigate more on the search, give me a few more days on this.

EB

**Comment by sharadkjaiswal** [comment]
Hi @archinate the library UI is now back in the tree view form. If you have any more comment/feedback on the library UI, please feel free to write to us. For now I am closing this as resolved.
