### ISSUE TITLE
Different centroid results in 0.8.0 vs 0.7.5

### ISSUE THREAD

**Issue by sjspikings** [DynamoDS/Dynamo#4267]
I am getting different result from the Solid.Centroid node in 0.8.0 vs 0.7.5. I believe that the 0.7.5 result is correct as it is the same as the results from the MassProp command in AutoCAD.

I am running the node in the family editor of Revit 2015 UR 7. Sorry, not sure how to share the node and the family with you on GitHub but can send separately if required. The family is an 'L' shape extrusion with an opening in one face created by a nested void family (not all openings show up in the Dynamo preview).

![dynamo 0 7 5 3881](https://cloud.githubusercontent.com/assets/12006145/7215094/05a4a69c-e5bf-11e4-8c49-da4443455305.png)
![dynamo 0 8 0 950](https://cloud.githubusercontent.com/assets/12006145/7215095/05a806ca-e5bf-11e4-9d69-b93d6c82b13d.png)

**Comment by monikaprabhu** [comment]
@sjspikings you can email me the files at monika.prabhu@autodesk.com

**Comment by ikeough** [comment]
@sjspikings Any update here?

**Comment by sjspikings** [comment]
Hi,
I repeated the test with Dynamo 1.0 and get the same result. I think the problem is that the volume of the void is being added to that of the host rather than subtracted which would explain where the CoG is being located. Let me know if you would like me to forward the original files.

**Comment by ikeough** [comment]
@sjspikings Yes, you can attach a .dyn file here by renaming it with a .jpg extension and dropping it into the conversation.

**Comment by sjspikings** [comment]
@ikeough Copy of Dynamo script and test family attached.
![cog test - home dyn](https://cloud.githubusercontent.com/assets/12006145/15065676/f49d8c14-1359-11e6-885e-602658ab1262.jpg)
![hcd-380_cog test rfa](https://cloud.githubusercontent.com/assets/12006145/15065679/f9d64324-1359-11e6-893d-3b11e48c2b8a.jpg)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
