### ISSUE TITLE
0.8 sandbox (official  release) not even starting

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4380]
0.7 is working correctly, but nothing pops up with 0.8.

**Comment by ikeough** [comment]
@jbenoit44 Do you have 3D Studio Max on your machine? We noticed recently that users with 3D Studio Max installed with Dynamo, including @mccrone, could not start Dynamo. This was due to Dynamo attempting to use 3DS max's geometry libraries instead of Revit's. A fix has been submitted in https://github.com/DynamoDS/Dynamo/pull/4373, but unfortunately will not be available in a "stable" release until 0.8.1.

**Comment by dbaldacchino** [comment]
No 3D Studio Max here, still no 0.8 Sandbox on Windows 8.1. 0.7.5 Sandbox works.

**Comment by jbenoit44** [comment]
no 3ds.

**Comment by mccrone** [comment]
There is a good chance that #4373 will solve this problem more generally once it's in Master.  It would be great if you could try again with the daily builds in the middle of next week, @jbenoit44 @dbaldacchino.

**Comment by dbaldacchino** [comment]
Will do, thanks Colin.

**Comment by dbaldacchino** [comment]
Just installed DynamoInstall0.8.1.20150513T0845.exe. This time it tries to launch, but I get a bunch of errors and crashes. It still fails to run within Revit with another 2 or 3 errors. Here are the Sanbox errors:

![2015-05-13_11-18-48](https://cloud.githubusercontent.com/assets/4656191/7615397/14b540a8-f963-11e4-8fd5-773855c2e5a1.png)
![2015-05-13_11-17-22](https://cloud.githubusercontent.com/assets/4656191/7615399/14b6b762-f963-11e4-8493-8ed95291aed2.png)
![2015-05-13_11-17-44](https://cloud.githubusercontent.com/assets/4656191/7615400/14b73020-f963-11e4-9dc4-4314fe27a906.png)
![2015-05-13_11-18-35](https://cloud.githubusercontent.com/assets/4656191/7615401/14b7d426-f963-11e4-8487-85e84cd53421.png)

**Comment by dbaldacchino** [comment]
Won't run in Windows 7 either.

**Comment by RodRecker** [comment]
@jbenoit44 - are you able to run the most recent daily build?

**Comment by RodRecker** [comment]
@dbaldacchino Thanks for your patience while we try to figure this out. We're actively working to resolve these initialization issues.

**Comment by dbaldacchino** [comment]
No worries, let me know if you need any logs etc. :)

**Comment by RodRecker** [comment]
@jbenoit44 @dbaldacchino - one thing to try to help us diagnose why 0.8.0 is not working. Can you find your DynamoSettings.xml file and edit it?

It is usually in this folder: C:\Users\<user>\AppData\Roaming\Dynamo\

Exit Dynamo and then change this line in DynamoSettings.xml to be false instead of true:
<UseHardwareAcceleration>true</UseHardwareAcceleration>

becomes:
<UseHardwareAcceleration>false</UseHardwareAcceleration>

Start Dynamo 0.8.0 and see if that helps. If it doesn't improve then please change the setting back to "true" in DynamoSettings.xml.

Let us know how it goes.

**Comment by dbaldacchino** [comment]
Hi Rod, which line? There are several true/false:

<?xml version="1.0"?>
<PreferenceSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <IsFirstRun>false</IsFirstRun>
  <IsUsageReportingApproved>true</IsUsageReportingApproved>
  <IsAnalyticsReportingApproved>true</IsAnalyticsReportingApproved>
  <LibraryWidth>304</LibraryWidth>
  <ConsoleHeight>0</ConsoleHeight>
  <ShowConnector>true</ShowConnector>
  <ConnectorType>BEZIER</ConnectorType>
  <FullscreenWatchShowing>true</FullscreenWatchShowing>
  <NumberFormat>f3</NumberFormat>
  <MaxNumRecentFiles>10</MaxNumRecentFiles>
  <RecentFiles />
  <BackupFiles />
  <PackageDirectoriesToUninstall />
  <WindowX>0</WindowX>
  <WindowY>0</WindowY>
  <WindowW>1024</WindowW>
  <WindowH>768</WindowH>
  <UseHardwareAcceleration>true</UseHardwareAcceleration>
  <BackupInterval>60000</BackupInterval>
  <BackupFilesCount>1</BackupFilesCount>
  <PackageDownloadTouAccepted>false</PackageDownloadTouAccepted>
</PreferenceSettings>

**Comment by RodRecker** [comment]
I see that the github site didn't paste everything since I copied it in as XML format.

The one near the bottom - "UseHardwareAcceleraction"
I'll see if I can edit my prior post.

**Comment by dbaldacchino** [comment]
Nope, still crashed, no change :(

Just to be clear:

a) DynamoInstall0.8.1.20150513T0845.exe doesn't work in Windows 8.1 or Windows 7 (Sandbox AND Revit add-in);
b) DynamoInstall0.8.0.exe works in Windows 7 (both Sandbox and Add-in), and in Windows 8.1 the Add-in works but not the Sandbox.

**Comment by dbaldacchino** [comment]
This is now working.

**Comment by mccrone** [comment]
Great.  And thanks for following up!

**Comment by bhowes-tt** [comment]
We are seeing the same issue at TT...  We tried switching UseHardwareAcceleraction to false and still nothing.   Any other suggestions?

**Comment by RodRecker** [comment]
Hi Ben - take a look at this thread and see if it helps. https://github.com/DynamoDS/Dynamo/issues/4658
