### ISSUE TITLE
need to have a cleaner error presentation for issues that causes loading/saving to fail

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#441]
When trying to save a dyn file, console says:
```
Object reference not set to an instance of an object.
   at Dynamo.Models.WorkspaceModel.SaveWorkspace(String xmlPath, WorkspaceModel workSpace)
Workbench could not be saved.
```
Closing Dynamo will result in a prompt to save my changes.
They will, however not be saved, and Dynamo will not inform me of this fact.
This just happens with one specific dyn-file.
Build 0.6.0.19901

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
