### ISSUE TITLE
Wish: New node - XYZs from placed ACs, Repeaters & CWPs

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#444]
It would be great to have a node that extracts placement point XYZs from: 
- adaptive components that were placed manually or via Dynamo
- pattern-based elements hosted on a divided surface
- a list of repeater components

I created a custom node called XYZs From Adaptive Components using a bit of Python which now lives in the package manager as an example of item 1 in the above list. I don't know whether the other two are actually possible with the current Revit API (I, for one, couldn't figure it out), but I think these would be really helpful tools when working with existing geometry in Dynamo.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
