### ISSUE TITLE
Faulty results on reusing variable name

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4549]
On reusing a variable name, changed values, instead of being reprocessed, seem to use the last value as the base to calculate the next.

The attached images attempt to elaborate
Note the last line in the code and the highlighted geometry in the background preview
![20150522-10](https://cloud.githubusercontent.com/assets/5621624/7767098/55514860-008d-11e5-9e66-a30ebcb05f43.jpg)

The values in the last line were changed to something else and then changed back to what it was earlier, but the position of the highlighted geometry doesn't return to intended position.
![20150522-11](https://cloud.githubusercontent.com/assets/5621624/7767124/872aa458-008d-11e5-93fa-3fba3d06b887.jpg)

Note: This problem can be avoided by using unique variable names for each step

Regards,
Vikram Subbaiah

**Comment by junmendoza** [comment]
Can you attached the dyn file for this case? It will be easier for us to debug this with the complete scenario

**Comment by testingwaters** [comment]
@junmendoza - I don't have the file in that state. 

However, the issue can be replicated by pasting the code below (three lines) in a code block node and changing the value of 'x' (and running). 

x=3;
a=Cuboid.ByLengths(3,6,1);
a=a.Translate(Vector.ZAxis(),x);

When run repeatedly with changed values of 'x', The new value of 'x' is not reset, but is the sum of all previous values

For example
First Run: x=3, 'a' moves up by 3 from 0 (as expected)
Second Run:x=4, 'a' moves up by 7 from 0 (instead of by 4)
Third Run:x=2, 'a' moves up by 9 from 0 (instead of 2)
and so on

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
