### ISSUE TITLE
Icons not matching function name after migration.

### ISSUE THREAD

**Issue by nguyen-binh-minh** [DynamoDS/Dynamo#4757]
Rectangle.ByWidthHeight was renamed to Rectangle.ByWidthLength.
However, the icons weren't changed so they do not go well with the new name.

[Rectangle.ByWidthLength.CoordinateSystem-double-double.Large.png](https://github.com/DynamoDS/Dynamo/blob/master/src/Resources/ProtoGeometry/LargeIcons/Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.CoordinateSystem-double-double.Large.png)
[Rectangle.ByWidthLength.Plane-double-double.Large.png](https://github.com/DynamoDS/Dynamo/blob/master/src/Resources/ProtoGeometry/LargeIcons/Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.Plane-double-double.Large.png)
[Rectangle.ByWidthLength.double-double.Large.png](https://github.com/DynamoDS/Dynamo/blob/master/src/Resources/ProtoGeometry/LargeIcons/Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.double-double.Large.png)

[Rectangle.ByWidthLength.CoordinateSystem-double-double.Small.png](https://github.com/DynamoDS/Dynamo/blob/master/src/Resources/ProtoGeometry/SmallIcons/Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.CoordinateSystem-double-double.Small.png)
[Rectangle.ByWidthLength.Plane-double-double.Small.png](https://github.com/DynamoDS/Dynamo/blob/master/src/Resources/ProtoGeometry/SmallIcons/Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.Plane-double-double.Small.png)
[Rectangle.ByWidthLength.double-double.Small.png](https://github.com/DynamoDS/Dynamo/blob/master/src/Resources/ProtoGeometry/SmallIcons/Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.double-double.Small.png)
@elayabharath

**Comment by monikaprabhu** [comment]
@lillismith - could you please take a look at this one.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
