### ISSUE TITLE
Point.Project issue

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4763]
Point.Project does not work as expected.

As an example there are two surfaces of varying complexity in [this](http://a360.co/1K3SR9c) file that demonstrates the inconsistency.

-Vikram Subbaiah

**Comment by monikaprabhu** [comment]
@testingwaters , please use node "Surface.ProjectInputOnto"  , which is working correctly at my end. 
To track this issue I've filed -MAGN-7732.This seems to be happening if the point is on the same plane as the surface at the given point. You can also fix this by translating the point a little bit and then Point.Project.  
![project](https://cloud.githubusercontent.com/assets/5218721/8276806/42992490-18ed-11e5-852c-3648590d30c5.png)

**Comment by testingwaters** [comment]
@monikaprabhu - *Surface.ProjectInputOnto* also behaves just as bad as *Point.Project*
In the image below, the complete list of points is on the left (399), the one in the middle using Surface.ProjectOnto is of the same length (399). However, the list on the right using a slightly elaborate approach seems to work.

![20150623-1](https://cloud.githubusercontent.com/assets/5621624/8305798/f3bfaac2-19cf-11e5-9cc7-80efc9111a40.jpg)

**Comment by testingwaters** [comment]
Just tried *Surface.ProjectInputOnto* and *Point.Project* with points that are offset from the surface they are projected onto. It still doesn't work as illustrated in the image below.

![20150627-1](https://cloud.githubusercontent.com/assets/5621624/8390521/667d21aa-1cb6-11e5-8019-7f953f68f4bb.jpg)

**Comment by riteshchandawar** [comment]
Hello @vykrum, Can you please share you file with me.
On my end it is working as expected for Point.Project.

![image](https://cloud.githubusercontent.com/assets/5109531/8925422/3d6e4ce8-353a-11e5-9df8-74de1df26950.png)

**Comment by riteshchandawar** [comment]
Hello @vykrum I think the best way to get the points on random suface is using Geometry.Intersect which you have already used. Point.Project is failing because it cannot be a Z or -Z direction to project the points on surface which are created on same surface.

You can take the below approch if you want to use POint.Project instead of Geoemtry.Intersect.

I have projected points on XY plane first and then I projected those points back to Surface.

Hope this will help.

Thanks,
Ritesh

![pointproject_updatedbyritesh](https://cloud.githubusercontent.com/assets/5109531/8926307/45ef56b2-3541-11e5-884f-102c4876539d.png)

Download PointProject_UpdatedByRitesh and change its etn to dyn.
![image](https://cloud.githubusercontent.com/assets/5109531/8926275/151f650e-3541-11e5-9404-75afa28334f2.png)

**Comment by vykrum** [comment]
@riteshchandawar the alternate approach works as another work around. Thanks
However, it would still be so much more convenient if Point.Project works as it should.

**Comment by riteshchandawar** [comment]
I think for that we need DirectoTo method which will provide us the Direction to Surface from Points which we can use for Projection Direction. Z or -Z definitely not going to work in this case.

I have logged a request to have DirectionTo method on geometry ( MAGN-3556). 

It was there earlier.

Thanks,
Ritesh

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
