### ISSUE TITLE
Element.OverrideColorInView not working on Model Lines

### ISSUE THREAD

**Issue by dietervermeulen** [DynamoDS/Dynamo#4769]
Dynamo V. 0.8.1.1473

When selecting model elements in Revit 2016 and using Dynamo to override their color in the current view, the nodes seem to pass, but they don't have any effect in Revit.

![image](https://cloud.githubusercontent.com/assets/12096185/8291197/536af574-1928-11e5-824a-f71a4eb87699.png)

**Comment by monikaprabhu** [comment]
@dietervermeulen - Element.OverrideColorInView seems to work correctly on 3d elements, seems to be a problem with 2d (curves) - I've files MAGN7741 - to track this issue.Will discuss with developer and check if this can be fixed soon.

**Comment by andydandy74** [comment]
I think this node is doing exactly what it's supposed to do. It's overriding the color of a *surface* using a solid fill pattern. Overriding a line colour in projection is a *different* Revit API call  (```OverrideGraphicSettings.SetProjectionLineColor```) and I would urge you to *not* aggregate those separate functionalities in one node as it would mean that the colours of *all* edges of any Revit elements passed to this node would be overridden as well. What would be nice, though, would be a node that allows us to pick several override options (surface color, edge/line color/linestyle, transparency, halftone etc.). Why? Because the nature of the Revit API call to create these overrides (```View.SetElementOverrides```) is such that it will reset any overrides set previously with another node. (For an example on how these calls cancel each other out when performed separately, try using Element.OverridecolorInView together with Clockwork's Element.OverideTransparencyInView...)

**Comment by monikaprabhu** [comment]
@andydandy74 - noted- will let the developer know about this. @Randy-Ma - do you want to add any comments here?

**Comment by ksobon** [comment]
This should have been fixed with 1.3 with this: 
![image](https://cloud.githubusercontent.com/assets/529781/26564220/6016e18c-44ac-11e7-8423-5cbbcbaf0ee6.png)

cc: @kronz can we close this?

**Comment by andydandy74** [comment]
The original node should be deprecated...

**Comment by kronz** [comment]
@andydandy74 The original still has use for general use in easy coloring of items, no?
