### ISSUE TITLE
‘Polysurface.ByLoftGuides’ bug

### ISSUE THREAD

**Issue by PaulusPresent** [DynamoDS/Dynamo#4798]
Hi,

There seems to be an issue with the way ‘Polysurface.ByLoftGuides’ handles NURBS profiles.

I constructed a simple file to explain the bug. It contains 4 guide curves (also NURBScurves) and 2 sets of 2 profile curves (NURBScurves).

Profile set 1 was created by the ‘NurbsCurve.ByPoints’ node. When I loft these profiles along the 4 NURBSguides everything is fine and works as expected. See image 1.

Profile set 2 was created by the ‘NurbsCurve.ByControlPoints’ node. When I loft these profiles the 4 NURBSguides get ignored and the result is a straight loft. No yellow warning is presented. See image 2.

In my opinion this is a bug. Is this the right place to report this issue? Can something be done about this or is this normal behavior?

![01](https://cloud.githubusercontent.com/assets/8777130/8390765/6e3dcdb4-1ca6-11e5-88ba-dd050125bda6.PNG)
![02](https://cloud.githubusercontent.com/assets/8777130/8390766/6e4f393c-1ca6-11e5-938f-aa674be3a51b.PNG)

**Comment by mccrone** [comment]
PolySurface.ByLoftGuides is definitely busted.  It completely ignores any guide curve.  I think it should be fixed or removed.

![byloftguides](https://cloud.githubusercontent.com/assets/6430819/18393482/838efc14-7683-11e6-87c4-962c95180e54.PNG)

**Comment by jnealb** [comment]
Thanks for the report @mccrone

**Comment by jnealb** [comment]
This is being tracked with MAGN-10645.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
