### ISSUE TITLE
Display Enhancement: Add method to hide/show.

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#4816]
Would it be possible to control visibility of objects? 
There are situations where I need all of the output from a python-script node to be generated, but turn on and off a few based on user defined criteria. Currently, all outputs are rendered. 

Something like the Display.ByGeometryColor component would work.

**Comment by ke-yu** [comment]
@melkhaldi , have you tried to disable "Preview" from node's context menu?

**Comment by melkhaldi** [comment]
Hi Yu Ke,
Yes, that works, but it hides all items generated by the node. For example
when 'OUT = [ A , B ]'. I need this the mist when using python script
nodes. I would like to generate A & B, but control the visibility of each
independently, interactively.

The only solution I can think of is adding more graph nodes to split
outputs-- one per node. This is doable but can make the graph unnecessarily
complex.

It would be great if visibility/display properties can be set per object in
the python script node.

Thanks,
Maher

**Comment by holyjewsus** [comment]
hmmm, have you tried setting the color of the geometry to some color with an alpha of 0, not sure if this would work.

**Comment by melkhaldi** [comment]
Hi Michael, No, I haven't done that just yet. but that is because it is
pretty much the same work-around-- adding more nodes to the graph. I am
currently approaching the use of nodes solely to control propagation of
data in the overall graph. I mostly use CodeBlock Nodes to use
Design-script's replication shorthand, and Python-Script Nodes to keep the
graph simple.

On Fri, Jul 3, 2015 at 11:25 AM, Michael Kirschner <notifications@github.com
