### ISSUE TITLE
background preview

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4871]
When navigating a background preview in Dynamo:

Zoom To Fit  - zooms to objects but also zooms to origin so if objects generated in canvas are far from the origin then zoom to fit is useless since it really zooms to extents (origin included).
If objects are far from origin then its impossible to zoom in on them or even rotate them. It would be nice to be able to center our origin on geometry by selecting a node on canvas so when we rotate the center of rotation is our selected geometry. Also it would be nice to zoom into the selected geometry.

**Comment by ikeough** [comment]
Agreed. Will log an internal issue for this when I'm at a computer.

**Comment by dbaldacchino** [comment]
I'm noticing that if Dynamo is not maximized and you stretch the window, the background graphic stretches unproportionately, then restores to the correct size. Yet it shifts position. I think it should maintain it's relative location and not re-size as this causes constant readjustment.

**Comment by dbaldacchino** [comment]
As of 0.8.1, background preview does not display when Dynamo is run on another machine through a Remote Desktop session.

**Comment by josols** [comment]
I don't know if this is under the same issue, but for us that use mm in our Revit models it's near impossible to use the Dynamo preview if elements are a little off from origin. it's like dynamo culls the objects as well as near impossible to rotate and zoom in.

**Comment by ikeough** [comment]
@ksobon We've done some work recently to improve zoom to fit, especially for elements far from the origin. Now, if you select zoom to fit with nodes selected, the fit will occur around the geometry generated by those nodes. And the center of rotation will be set to the center of the fit. 

Can you and @josols have a play with this, and let us know if it feels better?

**Comment by josols** [comment]
It feels so much better, thank you! But does this works also with list managment nodes? As if I'm extracting all the walls from a project and select item 0..10, will the zoom be centered on that collection? another one that came to mind: Is it possible for the background preview grid to be set to follow whatever units we're using as well?

**Comment by ikeough** [comment]
@josols Yes, the background grid is an issue. The problem is, I haven't yet figured out what the right automatic behavior should be. Obviously, for users working in mm, it's too small. But we can only know that it is "too small" by looking at the size of things in the scene. Once we do, we'd have to make some clever guess at what unit the user wanted (i.e. show the grid every 100th unit). Then someone would go and put a point 1000000 units away in space, and the grid would adjust to be incorrectly over-sized.

I think the way to solve this is with a "Grid Spacing" setting in the Settings menu. You could set it to whatever you want, and it would get saved in your preferences.

**Comment by ksobon** [comment]
How about a setting that kills the grid all together. Since you can't snap to it, control its visibility etc - I don't see how it's useful for anything at the moment. I can of course be wrong about this. 
I will also preview the zooming functionality and get back to you. Is that in latest daily?

**Comment by ikeough** [comment]
That is an option as well. In fact, we are just now merging work to allow you to disable the grid as an option.

The grid is useful insofar as it provides a frame of reference. Obviously, when it's too small to be seen, it does not achieve this. A similar frame of reference can be provided with a horizon line or a gradient background.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
