### ISSUE TITLE
Lost Nodes with 0.8.0 and up install

### ISSUE THREAD

**Issue by revitj0hnp** [DynamoDS/Dynamo#4894]
We have noticed that if you download any version after 0.8.0 it copies nodes from the 0.7 directory. Sometimes this causes a loss of custom nodes in a package because it overwrites the new with the old.

This is primarily an issue when you publish a package in 0.8 after install. An example to reference is the current version of the Archi-lab package. it is missing 11 nodes from the 5.5.15 release.

I have also noticed this if you try to publish from a computer with an older version of a package installed.

**Comment by andydandy74** [comment]
Let's take this a step further: I think Dynamo shouldn't overwrite someone's own package at all - under no circumstances - except if I deliberately re-install my own package. I'm having similar issues when installing packages that have my own package as dependency (see #3433).

**Comment by aparajit-pratap** [comment]
@revitj0hnp this issue has been fixed here: https://github.com/DynamoDS/Dynamo/pull/4901

**Comment by riteshchandawar** [comment]
Hello @revitj0hnp @andydandy74 : Did you Un-Install Dynamo 0.8.0 Manually?

Thanks,
Ritesh

**Comment by andydandy74** [comment]
@riteshchandawar - Sorry, but I don't really remember.

**Comment by riteshchandawar** [comment]
@andydandy74 The reason I have asked this because Migration of packages will only happen when there is no DynamoStteings.XML file. We delete this file when someone manually uninstalls Dynamo. Migration logic reads whether Dynamo running first time or not from this XML file. @aparajit-pratap is working on the fix for this.

**Comment by revitj0hnp** [comment]
I uninstall manually before each install of similar versions. It was
suggested once I believe.

**Comment by riteshchandawar** [comment]
You have to uninstall manually only when your are installing lower version on top of higher version for same series of Dynamo.

If you have Dynamo 0.8.1 installed on your machine and you want to install Dynamo 0.8.0 then only you have to uninstall manually, otherwise there is no need to uninstall manually.,

Thanks,
Ritesh

**Comment by ikeough** [comment]
Closing this because a fix is linked. @revitj0hnp, please re-open if you're still having issues.
