### ISSUE TITLE
Highlighting of geometry not working as expected

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4937]
I don't believe this problem existed before but I'm noticing that if there are coincident pieces of geometry (ex: points on top of each other created by different parts of the graph), selecting the node that creates them does not highlight the geometry as expected. It's as if the highlighted geometry is obscured. Highlighting should always render on top of other duplicate geometry, otherwise "debugging" is next to impossible to perform when building a definition. I'll try to illustrate the issue with the following images, thanks.

![issuea](https://cloud.githubusercontent.com/assets/4656191/8712914/b173d72e-2b27-11e5-851c-2caad17b7e30.png)

![issueb](https://cloud.githubusercontent.com/assets/4656191/8712919/babe87b6-2b27-11e5-8dc2-27c01c03db0e.png)

**Comment by dbaldacchino** [comment]
Another issue that seems somewhat related is when previewing geometry in Revit. For example some points displayed in the drawing area respect the "Preview" setting of the node that produces them, while others display whether they are previewed within Dynamo or not.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
