### ISSUE TITLE
BUG Report: Divide PolyCurve Equally

### ISSUE THREAD

**Issue by TomMahon** [DynamoDS/Dynamo#4943]
Dynamo version: Dynamo Studio 0.8.0.1233
Windows 8.1

There appears to be a bug when dividing a PolyCurve.ByJoinedCurves using the Curve.DivideEqually method. 

The PolyCurve I am creating is closed (an ellipsoid built from tangential arcs)

The divisions of this PolyCurve results in divisions = divisions +1 instead of divisions = divisions. No null objects or zero length items are created. Other curves appear to divide as expected.

Oddly, if the PolyCurve is divided equally in a Python node, using 6 divisions works as expected? Any other number of divisions will result in the error described above.

Tom

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by aparajit-pratap** [comment]
Fixed in polycurve feature branch, will be available in Dynamo 2.16+.
