### ISSUE TITLE
mesh.VertexPositions property is an order of magnitude slower than it should be

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#4982]
will track internally when I can, this call is an order of magnitude too slow on the mesh object, querying this property in a loop is deadly on .81, not sure on .82.

**Comment by dimven** [comment]
I extracted 40k vertices in ~15 seconds in the 0.82 daily from one week ago. Not sure if that is considered fast or slow tho.

**Comment by ikeough** [comment]
@mjkkirschner Was this ever tracked?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
