### ISSUE TITLE
Unexpected Null in Imperative Code Block

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5035]
Ver: 0.8.2.2113
OS: Win7

![20150802-2](https://cloud.githubusercontent.com/assets/5621624/9024623/d39ee578-38f6-11e5-86fd-457059209dcc.jpg)

**Comment by dimven** [comment]
Hello Vikram,
My current understanding is that lacing(or replication guides) is not and has not been supported in any form inside imperative blocks.
Because "c" is a list and you're basically trying to add 10 to each item in c, you have two options:
1) perform the addition outside of the imperative block
2) iterate through c and add 10 to each item.
![2015-08-03_15-48-38](https://cloud.githubusercontent.com/assets/7148394/9033212/c4a92dc4-39f7-11e5-8a44-bbc76319d65f.png)

@ke-yu I would personally love to have lacing enabled inside imperative code blocks. Would that be possible in the future?

**Comment by ke-yu** [comment]
@dimven , seems it is defect! Definitely replication guide should be supported in imperative code block node. @riteshchandawar , @monikaprabhu ?

**Comment by dimven** [comment]
@ke-yu This has been the case for me for probably as far back as 0.74
![2015-08-03_16-21-26](https://cloud.githubusercontent.com/assets/7148394/9033714/6369988c-39fc-11e5-947b-ccfdc2db2ac2.png)

**Comment by junmendoza** [comment]
@dimven 
Pls note that replication and replication guides are not supported within Imperative. 
This is by design in the core DesignScript language.

The reasoning is that Replication, which is fundamentally looping over a function, is supported within Associative (the default mode) and if you wanted to do the same in Imperative, you just manually do it with a for loop and while loop.

Hope this helps.

**Comment by dimven** [comment]
@junmendoza , Thank you for clearing things up. So it seems that my initial observation is correct.

**Comment by vykrum** [comment]
@dimven @ke-yu The availability of looping and conditional statements within Imperative code blocks is what got me to try them. However, it seems like the the thinking for certain simple things within Imperative code blocks needs to be a little different. Beginning to understand that, but being new to this, 'null' was unexpected :smile:

@junmendoza Replication guides not working is understandable and maybe expected, but , if made possible will certainly bring about some consistency inside and outside Imperative blocks.

**Comment by lukechurch** [comment]
>@junmendoza Replication guides not working is understandable and maybe expected, but , if made possible will certainly bring about some consistency inside and outside Imperative blocks.

I agree - I think we need to revisit this decision as part of the larger overhaul of replication and list management.

We also need to give better feedback on this than simply returning 'null'. That's not great UX for explaining why something isn't working. Invalid Imperative_Factor is an even sillier error message :)

**Comment by monikaprabhu** [comment]
I've filed two issues below to track the user request. 
MAGN-8162 - Revisit the language design for  using List operation with replication in imperative. MAGN-8161 - Appropriate error message while using wrong syntax in imperative.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
