### ISSUE TITLE
Object.IsNull returns true for List.Empty

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5073]
...when the empty list is part of another list. Seems wrong to me.
![listemptyshouldnotbenull](https://cloud.githubusercontent.com/assets/3014437/9168639/c42cb65c-3f58-11e5-8a8a-db832aa259fe.PNG)
Dynamo 0.8.1

**Comment by monikaprabhu** [comment]
@andydandy74 - I agree it must be consistent and it should return EmptyList in the above case. Tracking at MAGN-8191

**Comment by sharadkjaiswal** [comment]
It's strange, if List.Empty is first element in the collection then it gives correct result.
![image](https://cloud.githubusercontent.com/assets/1754137/9628741/0327d392-51a0-11e5-8402-2e815129bf7f.png)

can it be related to how DesignScript infers the type of a collection?

**Comment by ke-yu** [comment]
@sharadkjaiswal you mean `Object.IsNull` should replicate on empty list? It is weird to me, it should return boolean value.

**Comment by sharadkjaiswal** [comment]
Object.IsNull does replicate on empty list, but it behaves differently when it's part of a collection and is not the first element of the collection.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
