### ISSUE TITLE
ReplaceByCondition issue with List.Empty

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5074]
`ReplaceByCondition` will return `null` for instances of `List.Empty`.
Expected behaviour: Empty lists should stay empty lists.
![ReplaceByConditionAndEmptyLists](https://cloud.githubusercontent.com/assets/3014437/9171790/b2b368b0-3f6e-11e5-96e4-32539b4425bf.PNG)
Dynamo 0.8.1

**Comment by monikaprabhu** [comment]
I agree it must be consistent and it should return EmptyList in the above case. Tracking at MAGN-8191

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
