### ISSUE TITLE
Flatten is ignored in custom nodes with specified input data types

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5244]
The built-in `Flatten` command is ignored in custom nodes when a data type is specified for the custom node input.
Steps to reproduce:
1. Wire `Face.Vertices` into `Flatten`
2. Turn that into custom node
3. Run the graph - you'll receive a flattened list
4. Change input label to `face : Surface`
5. Re-run the graph - you'll receive a nested list
I have tested some other geometry-related cases with the same result.
Dynamo 0.8.2

**Comment by monikaprabhu** [comment]
I think this is due to replication. When you have face:Surface[] or face:Surface[]..[] the custom nodes will execute on all the surfaces and return a list of vertices.  When you change the input to "face:Surface" the custom node is executed one at a time on the input list of faces and it will return the vertices for each face one at a time which then accumulated will be a nested list. If you are seeing something different please post the graph so we can take a look.

**Comment by ikeough** [comment]
@andydandy74 Is this still an issue?

**Comment by ParametricMonkey** [comment]
Yes this is still an issue.

[test.zip](https://github.com/DynamoDS/Dynamo/files/377366/test.zip)

**Comment by ParametricMonkey** [comment]
@monikaprabhu I've posted my custom node which was causing an issue. I can't troubleshoot why it is failing. Some lists (doubles) work, while others don't. Removing the input hints and comments helped. Not sure what is going on.

**Comment by smangarole** [comment]
@ke-yu Any updates on this?

**Comment by johnpierson** [comment]
Reproducable in 1.3.3 and 2.0.1
![20181003-5244](https://user-images.githubusercontent.com/15744724/46419548-60e47800-c6eb-11e8-9e75-06644288f65b.gif)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
