### ISSUE TITLE
Display server time zone on dynamobuilds.com

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5286]
Sometimes when waiting for recently merged features to make it into the daily builds it would be nice to know which time zone the dynamobuilds.com server is hosted in. It would help if that information were displayed on the landing page.

**Comment by monikaprabhu** [comment]
Are you trying to figure out how much time will be taken to get the build - While this is a completely valid request. We generally upload the builds after the internal automation tests are run and verifying nothing majorly broken. So time is generally not predictable. if you are looking for anything more please get back to us.

**Comment by andydandy74** [comment]
@monikaprabhu - I'd like to know how old the currrent daily build is. If I know the timezone of the server I can just do the maths.

**Comment by ke-yu** [comment]
@mccrone ?

**Comment by RodRecker** [comment]
@andydandy74 the best way is to look at the name of the build - most recent is DynamoInstall0.8.3.20150917T0114.exe

150917T0114 encodes the build date and time:

150917 is the date (Sep 17, 2015) and 0114 is the time 1:14am Pacific time zone.

Using the file name is best because the time stamp on the left side of the builds page shows when the file was uploaded after passing tests which can vary due to a number of factors.

**Comment by mccrone** [comment]
@ke-yu I don't have access to the server.

**Comment by pboyer** [comment]
This is mine.

**Comment by andydandy74** [comment]
@RodRecker - Thanks - that's exactly the info I needed! Now that I know that it's PST I can do the maths myself. FWIW, I think that this may in some cases be interesting for other users, too, so perhaps it would make sense to include ```PST``` in the file name as a suffix.
