### ISSUE TITLE
Iterating Dynamo Definition with Revit Objects

### ISSUE THREAD

**Issue by ralvarez76** [DynamoDS/Dynamo#5349]
I am trying to drive a small test building geometry parametrically through Dynamo. This geometry will then be converted to Revit elements either in Dynamo or through the Revit interface. I am running into the following issues:

- If I create the geometry entirely in Dynamo, and use import instance into a mass family, I can create elements in the project “by face.” However when I update the geometry at a later date, all the “by face” elements are deleted because they can’t find their original hosts. I thought Dynamo updated the geometry? It looks like its recreating it instead.

- Next I tried to create reference lines form Dynamo and either create forms form these “bones” or snap points / lines to create forms from, and the same issue presents itself. The forms get deleted if created directly from the Dynamo reference lines, or the points get left behind if a parameter is changed in Dynamo.

Has anything broken with regards to the Revit / Dynamo interoperability? I have tested this with the latest stable release 0.8.2. Which the latest dailies (0.8.3.20150921T0452) the Revit geometry is not even instantiated.

I tried this first with an adaptive Revit family, but the constraints brake easily and its not robust. The constraints work wonderfully in Dynamo, but then you can’t update the Revit elements after design iterations

![01 - initial iteration](https://cloud.githubusercontent.com/assets/2349069/10054079/34acf862-61e4-11e5-97ee-a93f237599c8.PNG)
![02 - subsequent iteration](https://cloud.githubusercontent.com/assets/2349069/10054083/3b6c574c-61e4-11e5-8bb1-403e4fae2e2d.PNG)

**Comment by dimven** [comment]
I can't offer much help on this, because it seems to be a major issue. I've been experiencing similar behavior with walls and beams generated through Revit.

However for the above example, you could try using the built in "Form.ByLoftCrossSections" node. That way the form will stay associated at least until you close down Revit. (you can even close down the Dynamo window and re-open it.)
![2015-09-24_11-36-57](https://cloud.githubusercontent.com/assets/7148394/10064900/9d4c828a-62b0-11e5-93e5-4368cf0accc5.png)

But if you re-launch Revit and load the definition again(or if you press undo inside the Revit interface), you'll get a new form every time (also applicable for any other Revit element):

![2015-09-24_11-39-16](https://cloud.githubusercontent.com/assets/7148394/10064928/eed7b3fe-62b0-11e5-9df1-06a93ae2093d.png)

**Comment by ralvarez76** [comment]
Incidentally, the update works when its just instantiating points. I worked around the issue by only using points and creating more of the model natively in the Revit UI.

**Comment by ikeough** [comment]
If element binding is somehow broken, then this is a BIG issue. We'll look into this straight away.

**Comment by ikeough** [comment]
@ralvarez76 Did we ever get a reproduce-able case for this?

**Comment by ralvarez76** [comment]
Looks like this is fixed on the build I'm currently running: 1.0.1.1115
This works on reference lines created from Dynamo with manual Form created in Revit. In the project environment, a wall and roof by face created on a Dynamo ImportInstance surface created in Dynamo inside of a family updated properly,

**Comment by ikeough** [comment]
@ralvarez76 Thanks for the update!
