### ISSUE TITLE
Persisting data in custom UI node

### ISSUE THREAD

**Issue by j12kemp** [DynamoDS/Dynamo#5365]
If I build a custom UI node using NodeModel and INodeViewCustomization (as per SampleLibraryUI project) with a drop down list to select a specific return value for the node. Is it possible to store/save the selection in order to maintain the selection between Dynamo sessions?

**Comment by monikaprabhu** [comment]
@pboyer - can you please take a look at this?

**Comment by mjkkirschner** [comment]
@j12kemp you can override SerializeCore on your new node model, when the node is saved you store the index of selection. You also need to deserialize it when the node is loaded.

**Comment by pboyer** [comment]
@j12kem When you say "maintain the selection between Dynamo sessions" I assume you mean you'd like to persist this data with the actual dyn file. 

The dyn file is an xml file and each node is represented. When Dynamo saves the dyn file, it allows a `NodeModel` implementor to save additional data for the node. 

You should be able to find many examples of this inside of the code base. One good example is the `DoubleSlider` node (known as "Number Slider" in the UI for obvious UX reasons), because it demonstrates two ways of serializing data for a node:

https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/CoreNodeModels/Input/DoubleSlider.cs

The `DoubleSlider` node overrides the `SerializeValue` and `DeserializeValue` methods inherited from `BasicInteractive<T>`. Each method is invoked at dyn opening and saving time respectively. These allow a node implementor to store a single value with a node - in this case a single floating point number.

However, the `DoubleSlider` node also has to store the range and step size of the slider. This requires overriding `NodeModel`'s core serialization/deserialization methods - `SerializeCore` and `DeserializeCore`:

https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/CoreNodeModels/Input/DoubleSlider.cs#L88

This approach requires a bit more effort and necessitates some more detailed knowledge of mutating the `XMLElement` for the node. I think the `DoubleSlider` example speaks for itself, so feel free to reopen this if you need any more guidance. :)

**Comment by j12kemp** [comment]
Hi Peter,

 

Thank you for the prompt response. You have it right I would like to save the data in the dyn file. I will go through the DoubleSlider implementation and then play around with my own custom node to see if I can get it to work. If I get stuck I will re-open and ask more detailed questions.

 

Regards

 

Jaco Kemp
