### ISSUE TITLE
Dynamo 0.82: "Floor.ByOutline" goes into an infinite loop in Automatic mode.

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#5385]
Both versions of "Floor.ByOutlineTypeAndLevel" (polycurve and curve[] ) start an infinite loop when used in Automatic mode. The exact same graph worked in 0.81, so this seems to be a regression.

Not sure if this is limited to floors, or if other Revit nodes are affected. Will need to do more testing.

**Comment by andydandy74** [comment]
I've actually seen this happen in some fairly recent dailies with some custom nodes as well. Must be connected to how Dynamo and Revit interact because I recall that the only affected nodes were Revit related nodes (and I think only nodes that create Revit elements). I can provide samples if necessary.

**Comment by josols** [comment]
It also happens with your directshape node, Dimitar. So Andreas observation about the creating Revit nodes seem right. Revit 2015+0.8.2

**Comment by dimven** [comment]
Yes it seems to be a global problem with the element wrapper.

**Comment by mjkkirschner** [comment]
Hi @josols @dimven can you provide any small repro samples of this - (when you say your direct shape node) do you mean the one in .83 dailies or another one?

want to get to the bottom of this, these infinite loops are hard to test for, they generally occur with rebinding.

**Comment by dimven** [comment]
https://github.com/dimven/SpringNodes/blob/master/Samples/FloorOpening.ByCurves%20sample.dyn
https://github.com/dimven/SpringNodes/blob/master/Samples/FloorOpening.ByCurves%20Revit%202015.rvt

In the sample above, the file extracts some model curves from revit, splits them into floor and opening boundaries and creates the appropriate elements. 
If you leave leave the two element creation nodes, or just the floor node(built-in), or just the openings node(python) and attempt to run in "Automatic" mode, Revit and Dynamo hang.

**Comment by dimven** [comment]
The "StructuralFraming.BeamByCurve" node works wonderfully in automatic mode. I thought it would freeze as well because similarly, it creates elements by curves.So it seems like only certain nodes are affected?

![2015-10-01_13-56-06](https://cloud.githubusercontent.com/assets/7148394/10213791/2e4c066e-6844-11e5-8268-8a9d82faee89.png)

**Comment by mjkkirschner** [comment]
yes I'll need to look into this further, I'll repro and then track it asap.

Each Revit constructor may cause an infinite loop issue as they they cause node modified events when updating revit geometry, then this causes the node to fire again... and again... the fix is to check that no real work is being done (the inputs are the same) and not to modify the bound revit element

**Comment by dimven** [comment]
Revisiting this, it seems that the problem was the "All Elements of Category" node. It was constantly refreshing at every change to the Revit document and providing "new" elements, thus dirtying the graph. This is what caused the infinite loop and I believe this is also what's been causing the other loops.
