### ISSUE TITLE
public override string not visible in library

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5419]
Hi, I'm implementing a Class derived from an abstract class and override an abstract member function like this:

```
    [IsVisibleInDynamoLibrary(true)]
    public override string Write()
    {
        var value = Modifier + " " + Type + " " + Name + "\n" +
                    "0\n" +
                    "0\n" +
                    (Points.Count * 3);
        foreach (var point in Points)
        {
            value += "\t" + point.X + "\t" + point.Y + "\t" + point.Z + "\n";
        }

        return value;
    }
```

When I do this, the Function Write() is not visible in the Dynamo Library. Is there a way to have this in the Library again?
[IsVisibleInDynamoLibrary] set to true doesn't help.
Thanks, Fabian

**Comment by mjkkirschner** [comment]
@lukechurch

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
