### ISSUE TITLE
Surface.Point.At.Parameter not aligning with XY object from Revit

### ISSUE THREAD

**Issue by dietervermeulen** [DynamoDS/Dynamo#5475]
When a Face, coming from an Floor object in Revit, which is not aligned with the main WCS X-axis, is connected to the Surface.PointAtParameter node, then the points are generated according to the global Dynamo X-axis and on the XY boundary box of the face. When the same script is done on a Face selection of a wall, which is also not aligned with the X-axis, then the points are nicely generated within the curves of the vertical face.

Read more and find datasets at Forum: http://dynamobim.com/forums/topic/surface-point-at-parameter-not-aligning-with-xy-object-from-revit/

**Comment by dimven** [comment]
Bump @kronz 
This is still a problem in the 1.0 dailies:
http://dynamobim.org/forums/topic/dividesurfaceuv-problem/#post-36637

Looks a lot like a deeper issue inside the ASM

**Comment by kronz** [comment]
Thanks @dietervermeulen and @dimven .  Yes, this is actually a deeper issue inside of Dynamo, not a conversion from Revit geometry.  We need to add a more sophisticated piece of code, particularly for 4 sided elements.  Let's see what we can do for 1.0  
MAGN-9350

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
