### ISSUE TITLE
Polycurve.Offset not always in right direction

### ISSUE THREAD

**Issue by dietervermeulen** [DynamoDS/Dynamo#5477]
In the next example, it seems that when offsetting polycurves, which are composed from the perimeter curves of equal generated surfaces. Generated in Dynamo 0.8.2
In the example below, some curves are offset inside the original closed curve, in other indexes it is performed outside.

The original surfaces are the result of intersections of surfaces coming from a face selection in Revit and the solid.

Perimeter curves coming from the generated surfaces.
![image](https://cloud.githubusercontent.com/assets/12096185/10369694/dc52d566-6ddb-11e5-9e2b-0f39196050c4.png)

Offset curves, indicated ones are outside boundaries
![image](https://cloud.githubusercontent.com/assets/12096185/10369700/e49151f8-6ddb-11e5-9725-1d91b64b3e9d.png)

Offset curves and original curves together.
Some are inside, some are outside.
![image](https://cloud.githubusercontent.com/assets/12096185/10369747/1e3c5240-6ddc-11e5-85fa-3993ea1e1954.png)

Datasets:
https://autodesk.box.com/s/ow4vl43szb91z2i3ic1mlycxuv4mzzv7

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
