### ISSUE TITLE
ContainsKey

### ISSUE THREAD

**Issue by JohanCantryn** [DynamoDS/Dynamo#5478]
I have a list with four indexes. When I use the "ContainsKey" with 1 as the key-value it returns "True".
But when I choose lacing Longest for the "ContainsKey" node, suddenly all results are False.

![containskey](https://cloud.githubusercontent.com/assets/13676901/10380930/518acbaa-6e17-11e5-88d9-9bbe4c769a16.PNG)

Johan

**Comment by monikaprabhu** [comment]
@JohanCantryn,

**Comment by ke-yu** [comment]
@JohanCantryn ,

`Contains()` returns true if a list contains the specific value. E.g., `Contains({1,2,3,4}, 3)` return `true`.

A list could also be associative. That is, it could have key-value pairs. By default, its key is numeric value start from 0. So for the following list `xs`:
```
xs = {3, 5, 7};
```
It has three keys: `0`, `1`, `2` so that you could use them to index into the list. But it could also have non-numeric keys:
```
xs["foo"] = 11;
xs["bar"] = 13;
```
So `ContainsKey(xs, "foo")`, `ContainsKey(xs, 1)` both returns `true`, `ContainsKey(xs, 100)`, `ContainsKey(xs, "qux")` both returns `false`.
