### ISSUE TITLE
Search does Not work

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#5540]
Hi,

i am testing new dynamo 0.9.1 (DynamoInstall0.9.1.20151015T0049)
and according to descriptopn it should have improoved search, but it does not work at all:

i am looking for node (id to element) from archilab package that is saved on disk - external path:

here it is in browser

![id](https://cloud.githubusercontent.com/assets/4834544/10542203/c7ffc970-7416-11e5-8411-62a1a4780762.PNG)

here is amazingly long list with very little relevant nodes (to search), and further one i am after is nowhere in 4 page long list:

![id to element](https://cloud.githubusercontent.com/assets/4834544/10542201/c32d49b8-7416-11e5-85e7-95abd40dbf8f.PNG)

**Comment by andydandy74** [comment]
This is still an issue in 1.0 - I find this very disruptive to the overall workflow...
![suckysearch](https://cloud.githubusercontent.com/assets/3014437/15070483/d3053216-1384-11e6-9180-38669ba1bf2c.PNG)

**Comment by jnealb** [comment]
@andydandy74 @pboyer @Racel Agreed; work in progress.

**Comment by andydandy74** [comment]
If the search term matches a node name exactly, why not display that node as the first result? That should be an **easy fix** that could be **quickly** accomplished. Please, please. please give us at least that.
Examples this could be tested on in current versions (and that drive me mad time and time again): 

- "not" (shows RemoveIfNot instead of Not as best result)
- "sum" (shows Add instead of Sum as best result)
- ...

CC @kronz @Racel @jnealb

**Comment by smangarole** [comment]
@Racel @kronz Can you please provide an update on this issue?

**Comment by kronz** [comment]
Search is a big project, and we want to get it right.  We have major work slated to do on this after the 2.0 release, and we'd like to start using analytics to really nail it.  In the meantime, there are loads of very small changes you correctly point out.  We have avoided getting distracted by these, and perfect may be the enemy of good in this case, but we are trying to get to a better systematic overall solution rather than spot fixes.

**Comment by johnpierson** [comment]
Partial progress at, [QNTM-5869](https://jira.autodesk.com/browse/QNTM-5869)

**Comment by Racel** [comment]
The issue brought up by @ondejcik and @andydandy74 required a fix to a search algorithm that made queries with whitespaces difficult to manage. We have corrected this issue in this PR https://github.com/DynamoDS/Dynamo/pull/9332 which was just merged into master. The reported issue should now be resolved. Thanks so much for your feedback and patience. This fix will appear in the next release.
