### ISSUE TITLE
Enforce new run within Zero Touch

### ISSUE THREAD

**Issue by SaibotTe** [DynamoDS/Dynamo#5607]
Dear Comunity,

I would like to update the value of one previous node and then enforce a new run of the later way. I would like to do this with Zero Touch nodes in C#. I heard something about OnNodeModified but I do not understad how to include this in a Zero Touch node.
In the following example I want to update the value of the variable in the controller and I would like to plot these solutions in a list. But the value of the Variable does not change and so I can not save any solutions. Is there a way to solve this problem?

![dynamobuild](https://cloud.githubusercontent.com/assets/13719162/10741838/14290e7c-7c2a-11e5-9ee9-2f2161ca1c63.png)

My Code looks like the following:

namespace OptimizationDynamoSmall
{
    public class Variable
    {
        public static double _value;

        public Variable(double Value)
        {
            _value = Value;
        }

        public void setValue(double Value)
        {
            _value = Value;
        }

        public double getValue()
        {
            return _value;
        }
    }

    public class Function
    {
        public static double MultByTwo(double inputNumber)
        {
            return inputNumber * 2.0;
        }
    }

    public class Controller
    {
        public static Variable _variable;
        public static double[] _fitness;
        public static int _pointer;
        public Controller(Variable myVariable)
        {
            _variable = myVariable;
            _fitness = new double[10];
            _pointer = 0;

            for (int i = 0; i < 10; i++)
            {
                double x = 1.0 * i;
                _variable.setValue(x);
            }
        }

        public void setFitness(double Fitness)
        {
            _fitness[_pointer] = Fitness;
            _pointer = _pointer + 1;
        }

        public double[] getList()
        {
            return _fitness;
        }
    }
}

Finally I would like to use this in an optimization tool. Thank you all for your help!

**Comment by sharadkjaiswal** [comment]
Hi @SaibotTe, 

Dynamo is a graph based programming language, so order in which you create the dependency is important. Controller constructor takes Variable as an input so it depends on variable, but Dynamo doesn't know that the input variable will get modified by the Controller constructor, so the graph won't get updated in reverse order.

You may expose the stored variable as a property on Controller, so that you can query the new value of the variable after the constructor has modified and setup the graph accordingly. 
Also It would be good to return this Controller from setFitness method, because returning void will stop the dependency chain.

I hope this makes sense.
- Sharad

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move conversations to the forum. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
