### ISSUE TITLE
Wish: Checkboxes in node preview drop-downs

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#5655]
Wasn't this going to be implemented a long time ago? What happened to the idea?
![2015-11-05_18-02-10](https://cloud.githubusercontent.com/assets/7148394/10965552/bc750d9a-83e8-11e5-8f31-bdcf26a16b6c.png)
Basically the idea is to select only what you need from a list and output a new filtered list.

**Comment by redinkinc** [comment]
I also like the idea, but also like to have it as an extra node (in form of a dropdown or watch node with checkboxes...). Because when you can select items in the preview bubble, and hide it again, you do not see whats happening any more. For me one of the big advantages of Dynamo over Grasshopper is, that you cannot edit everything in the node directly, leaving somebody else (or yourself after a certain amount of time) with no idea whats happening in the graph.
