### ISSUE TITLE
Need Help: Surface Orientation

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5670]
Hello, I access the surfaces of a cube und now want to name them by their orientation. I have the following Code to do this:

``` c#
foreach (var surface in geometry)
 {
 if (Equals(surface.NormalAtParameter(0.5, 0.5), Vector.ByCoordinates(0, 0, 1)))
 {
 buildingSurfaces.Add(new BuildingSurface(surface, zone, "Roof"));
 }
 else if (Equals(surface.NormalAtParameter(0.5, 0.5), Vector.ByCoordinates(0, 0, -1)))
 {
 buildingSurfaces.Add(new BuildingSurface(surface, zone, "Floor"));
 }
 else
 {
 buildingSurfaces.Add(new BuildingSurface(surface, zone, "Wall"));
 }
}
```

This results in having all surfaces as a wall exept the lower one, which is labeled "Roof" instead of "Floor". Has anyone an idea how to solve this?

Thanks, Fabian

**Comment by mjkkirschner** [comment]
I believe the normal for the bottom surface of the cube is facing inward, you'll need to unify the normals first...

**Comment by redinkinc** [comment]
ok, thanks. any quickshot on how to do this? and why isn't the real Roof surface labeled anyway?

**Comment by mjkkirschner** [comment]
theres a few things,

1) use .IsAlmostEqual to compare the vectors instead of equals

2)

check out this thread:
http://dynamobim.com/forums/topic/solid-face-orientation/

3) there are other ways to unify normals, try searching math.stackexchange - one potential way is to cast a ray along the normal from every face and count how many times it intersects other faces, if the number is even the normal is pointing outside, if odd it's pointing inside... this relies on being able to cast the ray from a point on the surface... sometimes difficult if the surface is trimmed... it's also slow because you need to perform many intersections -

**Comment by redinkinc** [comment]
@mjkkirschner: Thanks for the help. Using the points -> vectors -> cross product workaround ended in all Surfaces identified as Walls (also used .IsAlmostEqual). I have now a new workaround that works for my purposes, because I define Zone for energy simulation (energyPlus) and therefore do not have any concave volumes.
```c#
foreach (var surface in geometry)
{
 if (surface.NormalAtParameter(0.5, 0.5).AngleBetween(Vector.ByCoordinates(0, 0, 1)) < 0.01)
 {
 buildingSurfaces.Add(surface.PointAtParameter(0.5, 0.5).Z > centerpoint.Z
  ? new BuildingSurface(surface, zone, "default", "Roof")
  : new BuildingSurface(surface, zone, "default", "Floor", "default", "Ground"));
 }
 else
 {
  buildingSurfaces.Add(new BuildingSurface(surface, zone));
 }
}
```
Not the best way, I guess, but works so fine. To ensure surface normals always pointing outwards would be nice anyway. Will this be changed in future versions?
thanks, redinkinc.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
