### ISSUE TITLE
Vasari Unable to Display/Draw after Dynamo run, v0.6.1

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#573]
I still get some cases where running a Dynamo will result in the current document to crash and display a message akin to "Vasari can not display/draw view" or something along those lines and the document will crash/close.  It happens randomly mostly in the Project environment and usually when families are being created after Run.  I'm not sure how to reproduce as restarting Vasari will fix the issue.

-Nate

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
