### ISSUE TITLE
Manage Packages.

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5731]
Hi, this is an update to #4384. 
- Is it possible that the package search only shows packages available for the installed version of Dynamo? sometimes I want to install a package and it simply crashes when I try to use it (which I guess is most of the times a problem of the version the package is designed for and the one i have installed).
  This also encourages developers to move their packages to newer versions of dynamo.
- It would be nice if .dyn files that come with a package in the EXTRA folder would be easily accesible. For example in the menu "packages/samples/<packageName>/<sampleFiles>" or in "help/samples/<packageName>/<sampleFiles>" or on the startpage? This would definitly help to get an easy access to what the package is capable.
  Thanks

**Comment by kronz** [comment]
- @redinkinc This is conceptually a little tricky, as most packages are forwards compatible, that is, most tools made in previous versions will work just fine in newer versions. We definitely want to encourage people to update their packages based on newer build thought.   We have been recommending that package authors set their own versioning to coincide with the version of dynamo that they built against.  See the MeshToolkit as a good model for this.  
- Totally agree about the need for Extras to be more discoverable.  There is a bit of a cycle going on now, that I think authors don't add sample files because Extras is not well known, and Extras continues to be less well known because it is underused.  Making it more obvious as a feature will help.

**Comment by andydandy74** [comment]
For future reference: 
- Version filter for package manager requested here: #2889
- Expose ```extra``` folder requested here: #3261

**Comment by redinkinc** [comment]
@kronz This may be right for packages that contain costum nodes, but that using .dlls sometimes crash because of changes in the namespace or depenencies. In my case I'm not able to work with the "Energy Analysis for Dynamo" package in Version 0.9 and there is no hint in the package manager. Also I do not like the version numbers be the same as the Dynamo Version, because if I update something in my .dll package, I want to have a new release version for both Dynamo 0.8.2 and 0.9.0 so this should be statet very clear. There approach from @andydandy74's clockwork is more convinient i think, but still a version filter would be nice because with every Dynamo Version the package manager will become more crowded.

@andydandy74 Thanks for the links. In addition to the google doc [package manager](https://docs.google.com/document/d/1AB7u4K87jlDYYrC3fN59x8oGtZbnprKsvh2hRl3jAnQ/edit) mentioned in #3261 there is also the [package manager V2](https://docs.google.com/document/d/1GXidznhcULkh0P1h-OrWwQGhpXTvxsx5o1CZNt5Fr9M/edit) that seems to be outdated as well. But there seems to be a lot of development in package manager, so it hopefully gets an update soon (as well as the package manager website...).

**Comment by johnpierson** [comment]
Closing as this functionality is referenced in other issues.
