### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by netlander** [DynamoDS/Dynamo#5830]
This build crashes like hell... Even Point.ByCoordinates is bombing out.
Is there a tagging system where we can get the a clean working codebase?

**Comment by mjkkirschner** [comment]
hi, @netlander - 
sounds like you've built from source and can't use any of the geometry nodes (like point)
Do you have any autodesk tools installed (like Revit?) This is required to access the geometry library with open source Dynamo.

**Comment by netlander** [comment]
Ah OK. No I don't have Revit but I have Inventor 2015, Autocad 2016 and Maya 2015, would any of these apps help?
Also I would be grateful if you could point me to information about setting up the libraries for building and running from source in Visual Studio.
Thanks

**Comment by mjkkirschner** [comment]
@aparajit-pratap Do we load the correct .dlls with these other tools?

**Comment by mjkkirschner** [comment]
building from visual studio should be straightforward, see : https://github.com/DynamoDS/Dynamo#build-dynamo-from-source

you want to build the Dynamo.All solution file found in Src. If you have visual studio Nuget should go and get the correct .dlls that are not bundled with our repo when you build, if not you may need to enable Nuget to do this from the tools menu I believe.

you may need to build twice potentially.

what errors do you get in the console in vs?

**Comment by netlander** [comment]
The build is successful (most of the times). My question was how to configure the final build with the missing libraries (Revit, etc...) so I can run the sandbox successfully.
Thanks

**Comment by mjkkirschner** [comment]
If Revit is installed in the normal autodesk install location it will be detected automatically, no config required. I'm unsure on the other autodesk products - will look into it.

**Comment by aparajit-pratap** [comment]
@mjkkirschner even if @netlander does not have any products installed with ASM, he shouldn't be seeing a crash when using geometry nodes. In any case Inventor should have ASM which should be detected by the `DynamoInstallDetective`. Will need to verify that it works with products other than Revit. I remember the Robot Structural guys use Dynamo with only an ASM-packed Robot installation so it should work. The crash could be either that the ASM version on his machine is not compatible with the one required by LibG or due to my recent changes for direct manipulation, however, I don't see any crash with the latest build.

Hi @netlander, could you check the following for us:
- Are you able to create points using code block nodes by typing in `Point.ByCoordinates();`? 
- Are you able to create any other geometry without using a `Point.ByCoordinates` node?
- Could you check which version of ASM you have on your machine in the Inventor install?
- What is the Dynamo build version you're using?

**Comment by mjkkirschner** [comment]
It's unclear that Dynamo was actually crashing or that geometry nodes were not functioning? (i.e. returning invocation errors)

**Comment by aparajit-pratap** [comment]
Closing this for now.
