### ISSUE TITLE
Structural Framing Node Does not Work In Family or Conceptual Mass

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#584]
I get an error that the document.create does not work in a family and I should use family.create instead.

Is it possible to use the structural framing node in a family?

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
