### ISSUE TITLE
DirectShape.byGeometry() Creates Infinite Loop in a ZeroTouchPackage (C#)

### ISSUE THREAD

**Issue by HasanAyan** [DynamoDS/Dynamo#5898]
Following function starts an infinite loop (I guess. Dynamo hangs) when Dynamo is in Automatic mode. When I try Manual mode, It creates all the Elements with the same ID and only one of them is actually visible in the model. Is there a way to overcome this?

``` c#
public List<List<Element>> CreateModel(List<List<Geometry>> Solids, Category category, Material material)
        {
            List<List<Element>> result = new List<List<Element>>();
            foreach (List<Geometry> group in Solids)
            {
                List<Element> rgroup = new List<Element>();
                foreach (Geometry g in group)
                {
                    rgroup.Add(DirectShape.ByGeometry(g, category, material, "Formwork"));
                }
                result.Add(rgroup);
            }

            return result;
        }
```

**Comment by mjkkirschner** [comment]
I believe when calling revit constructors like this you are invoking element binding in an anticipated way. The hang should not be occurring, I'll add a tracking number for that, but the single element being created is the expected behavior, as the function is being rebound on the next invocation and the element is being updated.

To do what you want you can take a look at the source here:
https://github.com/DynamoDS/DynamoRevit/blob/Revit2015/src/Libraries/RevitNodes/Elements/DirectShape.cs

and use the necessary methods without the element binding code.

Another option is to use the SpringNodes package by @dimven and use his directShape constructors, I don't think these do element rebinding.
