### ISSUE TITLE
Have to close and re-open DYN to get it to run properly

### ISSUE THREAD

**Issue by truevis** [DynamoDS/Dynamo#6047]
I've had this problem often. Something gets cached in Dynamo and re-running the definition doesn't update its data even though the Revit model has changed.

Workaround: close DYN, re-open, run

**Comment by kudilovich** [comment]
I have a similar issue with custom nodes (WPF UI nodes and Zero-touch nodes). Changing input in UI nodes triggers an exception "Warning: Null value cannot be cast to double". Re attaching wires or reloading the file fixes the issue, but re-running the file in manual mode does not fix it. Sometimes this issue disappears for a while but then occurs again for no obvious reason.  See screenshot below.

![dynamoscreenshot](https://cloud.githubusercontent.com/assets/10949355/12719210/b8d615f8-c8c1-11e5-98ba-fef4eeed4676.png)

**Comment by truevis** [comment]
This is a major issue that will keep Dynamo from widespread adoption. I hope a fix can be found.

If it has been fixed in post version 0.9.0.3067, please let us know.

**Comment by ke-yu** [comment]
hi @truevis and @kudilovich , for custom node, when the input is changed, could you try `NodeModel.OnNodeModified(true)`? (note `true` in `OnNodeModified()`)

**Comment by kronz** [comment]
@ke-yu @mjkkirschner @ikeough  is there a good zero touch sample that could illustrate this constrution?  Nuget packages?

**Comment by kudilovich** [comment]
Unfortunately .OnNodeModified(true) did not do the trick for the type of ZeroTouch and UI nodes that I am running. My nodes can be found here: [https://github.com/Wosad/Wosad.Dynamo](url). All the necessary libraries are referenced as Nuget packages. I can send a separate example where changing a single UI node input invalidates some nodes downstream.

**Comment by mjkkirschner** [comment]
@kudilovich I will look at your nodes when possible - can you provide a small video example of what is happening?

**Comment by kudilovich** [comment]
I converted all my nodes to 0.9.1 hoping that the problem disappear. Unfortunately it is still there. Here's a video:
https://youtu.be/V4TYvuniAb8

**Comment by ke-yu** [comment]
hi @kudilovich I pulled your code and built in on the top of the latest Dyanmo, loaded wosad.dll, but I can't find node `Bolt diameter selection` that you mentioned in the video. Which library should I load? Could you provide sample file so that I can do more investigation?

**Comment by truevis** [comment]
There are much simpler examples. I'll have to note it next time I have to struggle with the problem (like I did today).

My workaround is to just save and reopen the DYN.

**Comment by kudilovich** [comment]
Hi @ke-yu . Thanks for looking into this. The node you mention is here:
![image](https://cloud.githubusercontent.com/assets/10949355/13835258/9135d35c-ebcc-11e5-8a81-ee2739ce1dc9.png)
Also the file sample in the video is here:
https://drive.google.com/file/d/0B6ZGFrZdDP_wUnVzLXVzck5XS00/view?usp=sharing

**Comment by ke-yu** [comment]
@kudilovich , I still cannot find this node. I imported both wosad.dll and wosad.Dynamo.UI.dll, this is what I got:

![untitled](https://cloud.githubusercontent.com/assets/2600379/13836482/eea608e8-ec3c-11e5-9694-61cb73971525.png)

Downloaded your sample files, and nodes are unresolved. Probably it is because I'm on the latest build.

**Comment by kudilovich** [comment]
@ke-yu  Those are the correct DLLs. And you are looking at the correct node, but the UI node is not displayed like it is on my machine (0.9.1 build)

So here's what I do:
1) I import only wosad.dll, since wosad.Dynamo.UI is picked up automatically from the /nodes folder
2) It looks like your build exposes the properties from UI node as query objects. In my build they are hidden, I don't think this is relevant for this problem.
3) I think that on your machine there's a problem creating User control that displays the combobox. Perhaps that's because I use MVVM Light framework as a reference. Below is the list of files I copy from /bin folder into /nodes subfolder :

\Wosad.Dynamo\Wosad.Dynamo.UI\bin\Debug\GalaSoft.MvvmLight.dll       
\Wosad.Dynamo\Wosad.Dynamo.UI\bin\Debug\GalaSoft.MvvmLight.Extras.dll
\Wosad.Dynamo\Wosad.Dynamo.UI\bin\Debug\GalaSoft.MvvmLight.Platform.dll
\Wosad.Design\Wosad.Analysis\bin\Debug\Wosad.Analysis.dll
\Wosad.Design\Wosad.Common\bin\Debug\Wosad.Common.dll
\Wosad.Design\Wosad.Concrete\bin\Debug\Wosad.Concrete.dll
\Wosad.Design\Wosad.Loads\bin\Debug\Wosad.Loads.dll
\Wosad.Design\Wosad.Masonry\bin\Debug\Wosad.Masonry.dll
\Wosad.Design\Wosad.Steel\bin\Debug\Wosad.Steel.dl
\Wosad.Design\Wosad.Wood\bin\Debug\Wosad.Wood.dll
\Wosad.Dynamo\Wosad\bin\Debug\Wosad.dll
\Wosad.Dynamo\Wosad.Dynamo.UI\bin\Debug\Wosad.Dynamo.UI.dll
\Wosad.Dynamo\Wosad\bin\Debug\Wosad.customization.dll

**Comment by kudilovich** [comment]
Also,
Here's the node definition:
https://github.com/Wosad/Wosad.Dynamo/blob/master/Wosad.Dynamo.UI/Nodes/Steel/AISC_10/General/BoltDiameterSelection.cs

And here's the User control:
https://github.com/Wosad/Wosad.Dynamo/blob/master/Wosad.Dynamo.UI/Views/Steel/AISC_10/Connection/BoltDiameterSelectionView.xaml

**Comment by ke-yu** [comment]
No luck. If only load wosad.dll, I even couldn't find BoltDiameterSelection node:

![untitled](https://cloud.githubusercontent.com/assets/2600379/13837762/6550bbee-ec49-11e5-9dfd-227952bdd505.png)

Checked Wosad\bin and Wosad.Dynamo.UI\bin, I couldn't find wosad.customization.dll, Wosad.masonry.dll and Wosad.wood.dll (though they are not related).  

Probably some settings on my machine is different. Will do more investigation when possible.

**Comment by truevis** [comment]
**Simpler example:** Here is a DYN that shows geometry of Curtain Panels either green or red depending on Height. 

I run it once, it's fine. 
![2016-03-17 02_16_48-dynamo](https://cloud.githubusercontent.com/assets/3574046/13837998/c2661684-ebe6-11e5-8bd3-463c49547570.png)
I change something in Revit and run it again, it doesn't work right. 
![2016-03-17 02_17_20-dynamo](https://cloud.githubusercontent.com/assets/3574046/13838001/c26b8cfe-ebe6-11e5-8de7-8e07c8f584b4.png)
I reopen the DYN. 
![2016-03-17 02_17_40-](https://cloud.githubusercontent.com/assets/3574046/13837999/c266baee-ebe6-11e5-8238-da00f38972d2.png)
I run it after reopening, and it's fine again.
![2016-03-17 02_18_03-dynamo](https://cloud.githubusercontent.com/assets/3574046/13838000/c2687460-ebe6-11e5-8638-8b79d0d4aa4b.png)

**Comment by truevis** [comment]
The DYN in my sample:
[Panels geometry test.zip](https://github.com/DynamoDS/Dynamo/files/177367/Panels.geometry.test.zip)
In Revit make some curtain walls with heights more and less than 12 feet to test it.

**Comment by mjkkirschner** [comment]
I believe you need to put those ui node dlls in the nodes folder

**Comment by ke-yu** [comment]
@truevis Seems it works fine on daily build. Could you please test on daily build?

**Comment by kudilovich** [comment]
@ke-yu  Unfortunately I did not have a chance to test my nodes on the the daily build that you mentioned, but I am still experiencing the issue with 0.9.2 update.

**Comment by kronz** [comment]
@truevis I think the issue that you might be seeing is a different one.  All your nodes are showing their geometric output, that is, you have lots of different geometries that are overlapping in an uncontrolled way.  If you wan tto be seeing just the Display geometry, turn off the preview state for all your other geometry creating nodes.  I'm finding that your definition works just fine for this, that is, when a change happens to the category that it is monitoring, the graph is updating.
