### ISSUE TITLE
Area Plans not recognized as View datatype

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6087]
It looks like Dynamo does not think that Area Plans are of the `View` datatype, instead they are categorized as `Element`:
![1](https://cloud.githubusercontent.com/assets/3014437/12852769/f708152a-cc30-11e5-8004-9c66a4dfa6ad.PNG)
![2](https://cloud.githubusercontent.com/assets/3014437/12852773/fb781a74-cc30-11e5-9cbb-2e1b000e19a6.PNG)
There's not much point in offering these data types for custom node inputs if it results in creating constraints that are actually too strict...
Dynamo 0.9 stable release

**Comment by dimven** [comment]
This is similar to the case with structural plans. Basically, because each plan view type in Revit (floor plan, engineering plan, ceiling plan, area plan) has its own internal class, we need to recreate a custom wrapper class for each and add it to the element wrapper. Otherwise the view is automatically categorized by the element wrapper as an "UnknownElement " type.

https://github.com/DynamoDS/DynamoRevit/pull/653/files

**Comment by ksobon** [comment]
This was fixed here: https://github.com/DynamoDS/DynamoRevit/pull/1679
