### ISSUE TITLE
String.Remove anomaly

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6111]
ver: 1.0.0.384
os: Win10
![20160211-2](https://cloud.githubusercontent.com/assets/5621624/12978700/a6d49d2c-d0f8-11e5-96d2-bc6628b96a1b.png)

**Comment by NightHawk-Michael** [comment]
[Fixed] When the input of count is -4.0, the count is from right to left and the removal starts from the indicated start index. 
The above issue occurs because the starting of the removal process is not at the exact indicated start index.
Here is the result after the fix:
![string_remove](https://cloud.githubusercontent.com/assets/14092408/16980889/c07cd0da-4e9a-11e6-84d2-86885a4e3ee0.JPG)

**Comment by ke-yu** [comment]
Fixed in #6909
