### ISSUE TITLE
UI / workspace / command severe lag after run

### ISSUE THREAD

**Issue by BrianFraumeni** [DynamoDS/Dynamo#6115]
Trying to understand the cause of slow UI, command execution, VG , graphics, dynamo workspace navigation, file save time that occurs after running of definition. Ongoing issue since 0.7.xx release. Definition originally created in 0.6.2. Currently running on 0.8.2.
[CurveFaceIntersects_160208_v082.zip](https://github.com/DynamoDS/Dynamo/files/127343/CurveFaceIntersects_160208_v082.zip)

**Comment by dimven** [comment]
Hi Brian,
Don't take this the wrong way, but you're doing it wrong. 
Your file has 1359 nodes and 2004 wires and most of that is just copy-pasting the same stacks of nodes over and over again. Dynamo wasn't really designed with that scale in mind.

For a start, try to structure your graph a little better. Instead of copying repetitive sets of nodes over and over, consider adding them to a custom node instead. This will also help you with maintaining your code. When you need to change something, you'll just have to change one custom node.

Secondly, try to limit the use of watch nodes. Right now you've got about 340 of them and all that duplication of lists is going to drag performance down a lot. Do you really need to observe absolutely every step of the process? Maybe you can limit that to just a few key steps.

**Comment by BrianFraumeni** [comment]
Dimitar,

Thanks your message. Point taken. A great conversation here, and I think maybe one of the most relevant  in regards to the success of Dynamo. This is the discussion about the organic evolution of a project utilizing dynamo in a real way. As you said, perhaps it has not been designed to deal with this not so clean reality.
![sb1](https://cloud.githubusercontent.com/assets/2466772/13122855/f6784922-d56d-11e5-81df-89ef4560c1dd.JPG)

What you see here is the result of a 2 yrs of intermittent development by an architect over the a few different dynamo versions, (keep in mind beginning in early 2013). There has Significant amounts of time spent in fixing new release compatibility issues and tracking the evolution of the list actions, operators, units, etc. At the end of the day, a fee based project only has so much time and money. For us it was better to get the graph working as long as the output was accurate, which it is. It is just that now there are so much wait time, the efficiency is be compromised in a serious way.

In regards to watch nodes, the attached image shows a small sectioned vignette of some of the many different types of elements arrayed by the definition. When dealing with all systems interfacing (SMEP, facade, architecture, interiors, landscape, etc.), understanding  every dimension and tolerance down to mm levels is necessary. Compound this with the evolution of an actual building in construction and that sporadic flow of information. Beta 6 had no built in watch capability, thus watch nodes were the best solution for understanding the intersections of double curving geometry and thousands of dimensional overrides that are necessary. Every stack controls a unique dimensional override situation. This is the best method for being able to track change and more importantly give the definition it's best chance to be understood by those who have not created or worked with the graph.**** Further, when working with intersect geometry on complex forms, the XYZ data cannot be consistently sorted by key due to an anomaly in the round methods of Revit. this itself has led to a couple hundred 'should be' unnecessary nodes ****

Would it not be ideal for any designer on the team to be able to execute a graph and be able to track the geometry through every evolution? Yes it would be ideal for every designer to understand unit vectors and lists thoroughly, but this is not reality... . list.map _is_ used hundreds of times in this graph. I agree that these efficiency methods should be used as much as possible in the interest of scale, but again, as the earlier versions did not allow for watch on every node, you run the risk of really obscuring the data by threading multiple list.maps together. And again, without a great understanding of unit vector math, the results are down right confusing. Furhter, the more you bury codes and nodes into python and custom nodes, the more you are defeating some of the inherent natures that have lead creative offices to adopt Revit as an all phase platform. 

To go beyond your point, why even use nodes? Let's just put this all into a single code block? You could, but the result of that would be so confusing to the next person who tried to understand what was going, how could we even describe the confusion. It is a paradox in this case as the work around for my issue becomes moving the graph away from visual hierarchical programming to just another form of coding. Let's say it is all 'code' anyway, in different medium, and we agree in the benefit of visual programming, then every time you add information (new nodes; more bytes) you reduce the adiabatic efficiency of dynamo. 

Take aways:

-Less watch nodes. Can be watched with built-in now. Although some believe they do not add to the lag.

-More functions. Saves the amount of Though this does obscure the tangible data whilst mid stream and creates an obscure environment for other users to understand the data.

-More custom nodes. Less node volume would 'weight loss'. Could create relative obscurity in worksharing. Severe lag, even in moderately complex and simple graphs, while switching between dyn / dyf workspaces * post run.

**Comment by dimven** [comment]
I believe it's safe to say that we've all felt the pressure to finish everything before the deadline.
Still sometimes it's wiser to invest some of your time into refactoring and simplifying your graph than waiting for a result for hours on end, without a guarantee for success. This is especially true for cases where you're going to use the graph over and over for the length of the project.

You said it yourself - Dynamo has changed a lot in the last two years and I'd like to think that that change has been for the better. So consider using some of the newer functionality to replace the clearly outdated methodology. 

I had another glance at your code. Here's an arbitrary example - a set of 6 nodes repeated 10+ times:
![2016-02-18_12-22-25](https://cloud.githubusercontent.com/assets/7148394/13133911/52487b82-d63b-11e5-9b35-cd8e3f4ad794.png)

![2016-02-18_12-32-34](https://cloud.githubusercontent.com/assets/7148394/13133933/81127120-d63b-11e5-9c91-5bb3374cad24.png)

By simply using a code block to store the indices, instead of unnecessarily splitting up strings, then converting them to numbers, and with the use of lacing, you can kill two birds with one stone - increased the overall readability of the graph and improved performance.

You also seem to be having a hard time with points. Consider adding/subtracting vectors , instead of constantly breaking up points and re-constructing the points. 

Could you explain exactly what anomaly you're having with sorting points? Revit/Dynamo are quite capable at handling points as long as you understand their basic principles. Points are constructed from floating point digits, and FP digits are not cohesive after the n-th decimal point. That's just how computers and every software out there works. It's very easy to circumvent this limitation. Consider first rounding up your points to a reasonable decimal first. From my experience, 5 decimal points provides more than sufficient accuracy, when working in meters:

![2016-02-18_12-50-23](https://cloud.githubusercontent.com/assets/7148394/13134207/9d8fd90c-d63e-11e5-913b-6d5c8902bff9.png)

It's true that editing custom nodes has some overhead, when working with large graphs. But consider that once you simplify your graph, that overhead will shrink tremendously. If you're having an issue with a particular custom node, you could also troubleshoot it in a smaller isolated file. Another possible alternative is to instead use custom functions. They live directly on canvas and can be edited without any overhead.

The end goal of your graph is placing a ton of adaptive components. Consider upgrading to Dynamo 0.91RC (not backwards compatible with earlier versions). In 0.91 the "AdaptiveComponent.ByPoints" node gets a big boost. Here's an extract from the change-log:

> Dynamo for Revit
- Batch placement of adaptive components : Huge improvements to the speed and reliability of placing large numbers of adaptive components.

> Known issues:
- In some situations, placement of Adaptive components requires a change in list structure.  The AC placement nodes now expect to receive lists of lists of placement coordinates.  In the past, the nodes expected to only place one AC, now it expects to place many. If you are going to only place a single component, it needs to be nesting into a list.

**Comment by BrianFraumeni** [comment]
Thank you for your interest in this. All of your points are valid certainly. Great work. I think there is something else going on here with the issue of interface lag, post graph run. The graph executes in 2-3 minutes, even with errors. With catastrophic errors, such as the wrong model element selection the graph still executes within minutes, and this is worst case scenario. I believe the issue is with the amount of models being placed and subsequently tracked by dynamo. It is a scale issue as had alluded too. Something like toggling 'show edges' and then applying should not take 3 minutes.

![itsthesoftwarenotthegraph](https://cloud.githubusercontent.com/assets/2466772/13310378/7c8de658-db3a-11e5-819d-b1dbaf083cc2.JPG)

**Comment by kronz** [comment]
@BrianFraumeni @dimven Great discussion.  Brian, I think you are discovering the concept of the "Big Ball of Mud", 
https://en.wikipedia.org/wiki/Big_ball_of_mud
The problems that you are running into, while sometimes exacerbated by the inherent inefficiencies of Visual Programming, are not unique.  If a skilled programmer set out to write the kinds of operations that you are doing in Python, or C# or whatnot over the course of a couple years with a couple people, there would need to be structure in place, standards, and regular time set aside for code refactor and cleanup.  Not really any different from making a building in a traditional way.

What I'm also wondering about is how this kind of graph works in a team environment.  One of the other problems I'm assuming that you are running into is that it really doesn't work as part of a collaborative workflow.  This can be another incentive to componentize your project, either so that different people can own and operate subsections and work in parallel, or that you can concern yourself with only a subsection without having to regenerate the other areas.  One place I have seen teams succeeding is in establishing an agreed upon interface between pieces of the project, and then either making separate dyn graphs that each feed each other, or custom nodes that are worked on separately and come together in a "central" file that collects the big overall design.  An agreed upon interface (schema) is necessary for this, so that downstream recipients can count on continuing to receive data in a consistent way.  For example, a "roof" component might always require a flat list of surfaces and a list of numbers to operate, and can receive that list from a "building footprint" component.  One person can then concentrate on building the footprint section as long as they consistently hand off the data in the right format.  The roof person can operate independently as long as they know they will be operating on a consistently structured input data stream.

What's exciting about all this is that I see us generally starting coalesce as a community around the need for standards, best practices, and structure in a domain that is still pretty new for mainstream architecture.
