### ISSUE TITLE
Adaptive Component Node Not Working on 0.9.1

### ISSUE THREAD

**Issue by briandeyoung** [DynamoDS/Dynamo#6175]
## Dynamo version 

0.9.1

## Operating system 

Windows 7

## What did you do? 

tried to use the "AdaptiveComponent.ByParametersOnCurveReference" node

## What did you expect to see?

Expected it to work

## What did you see instead?

Error - this node does not work in 0.9.1, it works perfectly in 0.9.0, but when run in 0.9.1. it fails everytime.

**Comment by jnealb** [comment]
Can you please provide us with your rvt and dyn files? Thanks, neal.burnham@autodesk.com

**Comment by briandeyoung** [comment]
Here are the files
[Truss.zip](https://github.com/DynamoDS/Dynamo/files/147672/Truss.zip)

**Comment by jnealb** [comment]
@briandeyoung Thank you, this appears to be related to some changes we made to the node for 9.1. @sharadkjaiswal @Randy-Ma @kronz @monikaprabhu can you please take a look (PR 758) and clarify?

**Comment by kronz** [comment]
Hi @briandeyoung,
In some situations, placement of Adaptive components requires a change in list structure.  The AC placement nodes now expect to receive lists of lists of placement coordinates (instead of a flat list).  In the past, the nodes expected to only place one AC, now it expects to place many. So, in the case of the regular unhosted AC placement nodes, if for some reason you are only going to only place a single component, it needs to be nesting into a list.   
Now hosted ACs are already a little more complicated, so let me take a look at your file.

**Comment by kronz** [comment]
Yes, so this is the same thing as described for regular ACs.  An additional level of nesting is needed
![2016-02-26_1211](https://cloud.githubusercontent.com/assets/3456818/13359413/202699ac-dc82-11e5-8ffb-32b49762caa2.png)

**Comment by kronz** [comment]
BTW, let me know what you see in terms of speed.  This should be much faster now, particularly in large numbers of elements

**Comment by kronz** [comment]
BTW, may I ask, why are you using .ByParametersOnCurveReference in this case rather than the simplier .ByPoints?

**Comment by briandeyoung** [comment]
It's part of a training class I'm creating. The next exercise is creating a similar truss using points. I'm just trying to show multiple methods.

Thanks!
