### ISSUE TITLE
ProtoCore.BuiltHaltException thrown at importing own package

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#6220]
Hello,
I experience a problem with my [DynamoPlus](https://github.com/redinkinc/DynamoPlus) package. On my own computer, everything runs fine, but when I add my package to a .zip file or download the file from github (uploaded using github within VisualStudio 2015), importing the package throws an ProtoCore.BuildHaltexception. Anyone ever experienced this as well? Any ideas how to solve this?
Thanks, Fabian

## details
Dynamo 0.9.0 on Windows 10, VS 2015, .net 5.0

**Comment by mjkkirschner** [comment]
@redinkinc theres a few things you can do:

unlock the the dll by right clicking on it and unblock

you can set Dynamo to import remote sources:
http://through-the-interface.typepad.com/through_the_interface/2011/07/loading-blocked-and-network-hosted-assemblies-with-net-4.html

the problem is that after zipping a dll the dll is now blocked by windows. You can also create a trustedSite, for instance if you're trying to load this dll from a network share.

**Comment by redinkinc** [comment]
Seems to work. thanks

**Comment by dyhdxm** [comment]
Hello! I wonder that how I can load it in Dynamo as nodes. Looking forward to your reply. Thank you!
