### ISSUE TITLE
Data Structure — Dynamo tends to wipe out the first empty list/null value?

### ISSUE THREAD

**Issue by mynovmbr** [DynamoDS/Dynamo#6377]
Dynamo 0.9.1.4062  Windows 7 

Hi, I was trying to get intersection between several items by using List.Map, for example: I have 2 horizontal surface and 3 vertical surface, the data structure I’m expecting would be {[(0,0)(0,1)(0,2)][(1,0)(1,1)(1,2)]}. 

However, if the first surface failed to intersect with other 3 surfaces, I’m only getting {[(1,0)(1,1)(1,2)]}, and if the second one failed to intersect, I’m still getting{[(1,0)(1,1)(1,2)][EmptyList, EmptyList, EmptyList]}, which is correct. For me, it feels like dynamo tends to wipe out the empty list/null value at the beginning until the note can successfully get some results. This can be very tricky and important to keep data structure same for future use. Any thought?

![dynamo datastructure - empty list as 1st item - test](https://cloud.githubusercontent.com/assets/10234287/14284076/fc8b6206-fb13-11e5-86ea-dbb59a051c05.JPG)

**Comment by kronz** [comment]
@ke-yu can you comment on how we do and don't return empty list data in this case?

**Comment by ke-yu** [comment]
@mynovmbr @kronz it is a bug in `List.Map()`. 

More details: `List.Map()` internally use `Count()`, the pseudo code looks like
```
result = {};
for each item in input list
    result[Count(result)] = map(item, parameters);
```
If the first item in result happens to be an empty list, `Count()` returns 0, so the following result will overwrite it (`result[0]`). 

@riteshchandawar @monikaprabhu please log a defect for it. 

@kronz @riteshchandawar @monikaprabhu , just to clarify - `Count({{}, {}, {}})` should return 3 right?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
