### ISSUE TITLE
My package search manager doesn’t work - no search results

### ISSUE THREAD

**Issue by cezlip** [DynamoDS/Dynamo#6390]
## Operating system

Windows 7
## What did you do?

Searching for packages
## What did you expect to see?

Any results
## What did you see instead?

Search returned no results!

**Comment by jnealb** [comment]
@cezlip Can you please update your version of Dynamo to the latest stable release, 9.2? We think this is fixed.

**Comment by cezlip** [comment]
I have updated Dynamo to  9.2 version. Unfortunately nothing has changed. Is it possible that  the company proxy server is blocking all communication with Dynamo?

**Comment by jnealb** [comment]
@cezlip Yes, with the Package Manager site. What happens if you browse to https://www.dynamopackages.com with your favorite browser?

**Comment by cezlip** [comment]
neither of my browser open this website

**Comment by jnealb** [comment]
@cezlip What error do you get? 404, 403?

**Comment by cezlip** [comment]
@jnealb I tried again and eventually was able to access website from Chrome. My IE shows :
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Timestamp: Wed, 13 Apr 2016 14:38:32 UTC


Message: Object doesn't support this action
Line: 7
Char: 3
Code: 0
URI: https://www.dynamopackages.com/js/app.js

**Comment by jnealb** [comment]
@cezlip Can you reach the Package Manager from Dynamo if you make Chrome your default browser?

**Comment by cezlip** [comment]
@jnealb no I can't

**Comment by jnealb** [comment]
@cezlip What version of IE are you running?

**Comment by cezlip** [comment]
@jnealb  IE10

**Comment by jnealb** [comment]
@cezlip Suggest you upgrade to 11

**Comment by cezlip** [comment]
@jnealb  I know. I suggested the same to our IT support but do you think it will help?

**Comment by jnealb** [comment]
@cezlip Not sure

**Comment by redinkinc** [comment]
Hello,
since this topic is still open I add my issue here: I'm currently using Dynamo 1.0.0 that comes with Revit 2016 on Windows 7. When I run "Search for Packages" my results also stay empty.
I tried to install "Mesh Toolkit". I then downloaded the package via the package manager website (IE 11) and tried to install it by hand. But this results in an error saying "unable to load package". Do you have any experiences with that issue?

**Comment by mjkkirschner** [comment]
@redinkinc do you see any more information on the failure in the console?

**Comment by redinkinc** [comment]
In the case of "Search for Packages": no 
![search for packages](https://cloud.githubusercontent.com/assets/3741716/17024120/eda982e4-4f56-11e6-9b70-ffc254aefc8e.PNG)

For Mesh Toolkit: I added it to the package folder, so on startup I get this:
```
Dynamo -- Build 1.0.0.1180
Doppelter Migrationstyp registriert für SunPathDirection
Dynamo will use the package manager server at : https://www.dynamopackages.com
Exception when attempting to load package MeshToolkit from C:\Users\rittefa\AppData\Roaming\Dynamo\Dynamo Revit\1.0\packages\MeshToolkit
System.IO.FileLoadException: Die Datei oder Assembly "file:///C:\Users\rittefa\AppData\Roaming\Dynamo\Dynamo Revit\1.0\packages\MeshToolkit\bin\DynAMT.Managed.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)
DynamoPackageManager (id: FCABC211-D56B-4109-AF18-F434DFE48139) extension is added
```
When I try to add it manually, I get this:
```
Build-Fehler für Bibliothek: C:\Users\rittefa\AppData\Roaming\Dynamo\Dynamo Revit\1.0\packages\MeshToolkit\bin\DynAMT.Managed.dll
Fehler beim Importieren von C:\Users\rittefa\AppData\Roaming\Dynamo\Dynamo Revit\1.0\packages\MeshToolkit\bin\DynAMT.Managed.dll
Eine Ausnahme vom Typ "ProtoCore.BuildHaltException" wurde ausgelöst.
Laden der Bibliothek fehlgeschlagen: C:\Users\rittefa\AppData\Roaming\Dynamo\Dynamo Revit\1.0\packages\MeshToolkit\bin\DynAMT.Managed.dll
```
Which means: Build error for package. Import error. An Exeption of type "Protocore.BuildHaltException" was thrown. Loading the package failed.

**Comment by mjkkirschner** [comment]
@redinkinc a few thoughts and more questions:

* what version of mesh toolkit at are trying to install 1.0 or 1.1?
* that exception you are getting through the package manager usually means that a dll is being blocked by windows - try right clicking through the assemblies and unlocking them if the option presents itself under info.

**Comment by redinkinc** [comment]
now that you are mentioning that: I remember I had this problem before. Unlocking the "external" .dll's solved the problem. Thank you.
Reduces this to the problem that Search for Packages returns no results.

**Comment by smangarole** [comment]
@cezlip and @redinkinc - I cannot reproduce this with the latest version of dynamo. Can you please confirm?

**Comment by aishu1212** [comment]
Hello i have Dynamo 0.9.1.4062 1.3.2.0 version with me but am unable to doanload the packages / my search package is not responding suggest me

![dynamo error](https://user-images.githubusercontent.com/38004305/38195156-a580e5f8-3699-11e8-9723-03fe5e45c130.JPG)

**Comment by tufailmab** [comment]
same issue here :(

**Comment by tufailmab** [comment]
same issue here :(
![image](https://user-images.githubusercontent.com/69433867/92245169-64876780-eedd-11ea-91c3-94fe9f7ff9b4.png)

**Comment by Amoursol** [comment]
Hello @aishu1212 and @tufailmab,

Unfortunately the **Package Manager** will no longer work in older versions of Dynamo as we have patched a Security threat. 

There is a workaround you will be able to use by accessing the [Dynamo packages](https://dynamopackages.com/) website and navigating to the package you wish to use.

![image](https://user-images.githubusercontent.com/12857357/92491526-53ca4080-f1c0-11ea-8bd4-5d39e35daeb8.png)

In here, you can either **Browse** or **Search** for packages. In my example I'm simply browsing by "Most downloads" and have chosen to expand the **Archi-Lab** package. 

![image](https://user-images.githubusercontent.com/12857357/92491756-97bd4580-f1c0-11ea-9031-f61017055c58.png)

You'll have to figure out what version works inside of your version of Dynamo - reaching out to the package author may work, or a forum search here.  You can scroll down in the _Versions_ section to the appropriate version, and click on it to download.

![image](https://user-images.githubusercontent.com/12857357/92492191-14e8ba80-f1c1-11ea-8a93-a79c8892c557.png)

Once downloaded, you need to either use **7Zip** to unzip or right-click on the downloaded ZIP package, select **Properties** and **Unblock it** - This is a Windows security feature rather than from our side. You can find the **Unblocked** check-box in the lower right. After unblocking, you can **Unzip** the package like normal. Note, it will default to the GUID rather than the name of the Package. So after unzipping feel free to rename to the package name if you wish (It will not affect Dynamo if you do not). 

![image](https://user-images.githubusercontent.com/12857357/92493139-254d6500-f1c2-11ea-8811-894c4f9ff07e.png)

After you have unblocked it - you simply need to put it into the right place 😊  Open up a new **Folder**, navigate to the path line and type in **%appdata%** - Which is a shortcut to take you to your appdata roaming folder. When you are in this folder, navigate to:

- Revit: _Dynamo/Dynamo Revit/<VERSION>/packages_
- Core: _Dynamo/Dynamo Core/<VERSION>/packages_

Then drag the newly unzipped file into this folder, restart Dynamo and you will have access! Note, that if the version you have uses any future content it may not load. 

![image](https://user-images.githubusercontent.com/12857357/92493056-11a1fe80-f1c2-11ea-9c83-a5128295e949.png)

![image](https://user-images.githubusercontent.com/12857357/92496656-6b0c2c80-f1c6-11ea-95ca-c79021e7d371.png)
