### ISSUE TITLE
why python module random is not installed?

### ISSUE THREAD

**Issue by ricardo7cordas** [DynamoDS/Dynamo#6395]
## Dynamo version

0.9.2.4472

## Operating system

Windows 10

## What did you do? 

i'm tried to import basic **random ** module in python, but it not work

## What did you expect to see?

the module working

## What did you see instead?

ImportError: No module named random

![image](https://cloud.githubusercontent.com/assets/14896455/14372607/8926d910-fd18-11e5-853a-8ff0adc909f9.png)

**Comment by mostaphaRoudsari** [comment]
@ricardo7cordas it's installed under IronPython folder. You need to add that to ```sys.path``` in order to import the library. I agree that the path should be added by default in Dynamo but meanwhile you can use the code below:

```python
import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")

import random

OUT = random.random()
```

**Comment by ricardo7cordas** [comment]
Works like you said @mostaphaRoudsari. Thank you very much. I saved a lot of code with it

**Comment by mostaphaRoudsari** [comment]
> This works for other libraries in then folder. I am sure?

it does!

**Comment by ViktorKuzev** [comment]
What is the default path for python nodes in dynamo?

**Comment by ricardo7cordas** [comment]
Hi @ViktorKuzev  this was pointed on the previous @mostaphaRoudsari 's comment. See above.

**Comment by ricardo7cordas** [comment]
C:\Program Files (x86)\IronPython 2.7\Lib

**Comment by ViktorKuzev** [comment]
Hi @ricardo7cordas and thanks for your reply. 
As I see now my question was not clear enough. 
What I am asking is if there is a place where I could put additional libraries and import them directly without having to use "import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")"

**Comment by mostaphaRoudsari** [comment]
@ViktorKuzev python will look for your module inside the folders that are available in `sys.path`. It can be different if you're running Dynamo from inside Revit, sandbox version or the dynamo studio.

**Comment by mjkkirschner** [comment]
sys path is where IronPython looks for modules, you can print sys.path and see what path is included, it will probably be . (current directory) of the executing dynamoCore.dlls...

**Comment by ViktorKuzev** [comment]
@mostaphaRoudsari @mjkkirschner   Thank you for your replies. 
I'm using Python from within dynamo. I managed to import an additional library, but I can't use it since it can't find __future__.py 
Apparently it uses it for something.  I opened the module that uses __future__.py and added the same line at the top that appends the directory. But now I get a message that __future__.py should be place at the very beginning of the code.

**Comment by mostaphaRoudsari** [comment]
@ViktorKuzev,

`future` module changes how the file will be interpreted for cases like print and should be on the very begging of the file. Instead of editing the module add the path to IronPython installation folder to sys.path inside your code in Dynamo. It will ensure that your custom library will import future with no issues.
