### ISSUE TITLE
one line if statement doesnt work inside imperative code

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6490]
## Dynamo version

0.9.2 Dynamo version
## Operating system

Win 10
## What did you do?

one line if statement doesn't work inside DesignScript imperative code
## What did you expect to see?

It working in the same way as associative code
## What did you see instead?

Null value
![one-line-if in imperative code](https://cloud.githubusercontent.com/assets/18601851/14724504/83cd4d72-080e-11e6-810f-199d59919922.png)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
