### ISSUE TITLE
One line if statement cant return a singleton and an array within the same statement

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6491]
![one-line-if cant return singletons and arrays](https://cloud.githubusercontent.com/assets/18601851/14724638/5e3798f0-080f-11e6-8c53-2e74139ae356.png)
## Dynamo version

0.9.2 Dynamo version
## Operating system

Win 10
## What did you do?

one line if statement cant return a singleton and an array within the same statement. So if true = singleton and false = array it will always return a list
## What did you expect to see?

I expect it to return whatever I tell it to and not default to what appears to be 'longest' lacing
## What did you see instead?

A list equal to the rank of the list either side of the conditional return statement

**Comment by sharadkjaiswal** [comment]
I think the conditional statements are defined as a function 
`def conditional(condition : bool, iftrue : var, iffalse : var)`
So when one of the parameters is passed as collection, this function replicates and hence returns a collection in both the scenarios. @ke-yu any thought how we can handle it differently?

**Comment by ThomasMahon** [comment]
@ke-yu @sharadkjaiswal further to the above issue, I've also found that even if arrays are used, the one line if cant return arrays that differ in length. The example below shows an example where only the first 2 items are returned: 

![cant return arrays of differering lengths](https://cloud.githubusercontent.com/assets/18601851/15302603/b090c8ba-1bab-11e6-96da-1c7015d44780.JPG)

**Comment by andydandy74** [comment]
@ThomasMahon  - please also see the discussion here: #3106 
While you can use ```ScopeIf``` in cases like these (which at least until recently did not work stably in larger graphs), I have come to rely mostly on the following workaround:
```
result[0] = seq1;
result[1] = seq2;
result[booltest ? 0 : 1];
```

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
