### ISSUE TITLE
List SortByKey fails when sorting Revit objects (floors)

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6495]
## Dynamo version
0.9.2

## Operating system

Win 10

## What did you do? 

Selected some floors in a Revit project. Got their elevation heights. Sorted the list using SortIndexByValue method. Used the index list to sort the floors using SortByKey (to guarantee they were ordered by height sequentially and prevent problems caused by the order in which they were selected). 

## What did you expect to see?
The floors sorted based on the heights via the sorted index list. 

## What did you see instead?
Only one floor was sorted, the rest remain unsorted.

I had to write a simple DesignScript function to sort the floors using the same index list which rules out any error with the SortIndexByValue method. The problem is coming from the SortByKey method
![sortbykey fails](https://cloud.githubusercontent.com/assets/18601851/14726285/f521b6ac-0818-11e6-92f8-f23a9c93e011.png)

**Comment by dimven** [comment]
@ThomasMahon  "List.SortByKey" works as expected:
![2016-04-22_10-15-51](https://cloud.githubusercontent.com/assets/7148394/14729713/f81ba52a-0872-11e6-84ad-0833856bdc26.png)

The problem is that "SortIndexByValue" is giving you a wrong value keys:
![2016-04-22_10-38-44](https://cloud.githubusercontent.com/assets/7148394/14730090/1d8df094-0876-11e6-96a1-fe86256b1ca0.png)

**Comment by ThomasMahon** [comment]
Thanks Dimitar....my hangover from my days of GC!

**Comment by jhubers** [comment]
However if you have lists in lists and one or more of the keys lists have only one value, you get an error. It should just not sort that list.
