### ISSUE TITLE
List.AllIndiciesOf inconsistent behaviour with number node and output from Vector.Dot list

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6529]
## Dynamo version

0.9.2
## Operating system

Win 10
## What did you do?

Output the dot product of two vectors (results are in a list). I want to identify all the co-linear and opposing test vector results (i.e. scalars of +1 or -1) and used the Number node and List.AllIndicesOf node to return all the indexes in the list that have a value (a dot) of 1.0 or -1.0. 
## What did you expect to see?

I expect to see all the indices where 1.0 and -1.0 occur
## What did you see instead?

An empty list. 
## It gets complicated

I found that if a code block with 1.0 and -1.0 is used instead of number nodes, the List.AllIndicesOf node works as expected. Furthermore, if the output of the dot array is, instead, replaced with a list hardcoded from a code block, then the List.AllIndicesOf node works with the number nodes? Very confusing. See attached image for all three examples. 

I discovered this problem after extracting all faces from a Revit mass and using their normals to identify verticality.

![capture](https://cloud.githubusercontent.com/assets/18601851/14826271/05d24222-0bd5-11e6-978f-628afd3ed467.png)

**Comment by dimven** [comment]
It's probably got something to do that in one case your search item is an integer and in the other a double:
![2016-04-27_16-50-22](https://cloud.githubusercontent.com/assets/7148394/14846788/229c72c4-0c98-11e6-8c76-0926df34a701.png)

**Comment by ThomasMahon** [comment]
I thought the same thing initially (in the real example which was evaluating a list of dot products). I thought maybe the dot outputs inconsistently, i.e. int's and double's. However, when I used the code block with 1DP (i.e doubles) the AllIndicesOf node worked as expected which is what makes this issue so difficult to pin down. 

Your image throws up even more questions, for example, why is the number node a int? I would expect it to be a double. Maybe it casts, but either way I think we've stumbled upon a definite improvement request, namely a number node AND a integer node, notwithstanding my original issue. That said, if the number node is a double and only a doble then I believe that will resolve the issue - the output from the Vector.Dot node appears to be doubles, despite what the watch shows.

**Comment by ke-yu** [comment]
@ThomasMahon I think it is a bug. Interestingly, "1" from `Number Slider` node is a double.

@monikaprabhu @riteshchandawar @jnealb  FYI

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
