### ISSUE TITLE
Improvement (and possible bug): Number node and Integer node

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6543]
## Dynamo version

0.9.2
## Operating system

Win 10
## What did you do?

Number node object type registering as an int not a double. This causes equality errors when evaluating, for example, a list of doubles against the number node.

See #6529 for further details and an example
## What did you expect to see?

I expect a double from the number node. It's object classification is int32
## What did you see instead?

Equality using a number node fails when evaluating for equality against a double
## Improvement suggestion

Dynamo should have a number node AND an integer node, just like sliders. This, I expect, would resolve the issue reported in #6529

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
