### ISSUE TITLE
#Can't open file

### ISSUE THREAD

**Issue by dannysbentley** [DynamoDS/Dynamo#6552]
## Dynamo version
1.0.0

## Operating system
7.6 Windows 

## What did you do? 
Opened a file I've been working on in version 0.9.2

## What did you expect to see?
file open in version 1.0.0

## What did you see instead?
Error message:

Unknown error opening file:
W:\S\BIM\z-Dynamo\FRAMINGBYPOINTS_INTERMEDIATE.dyn

**Comment by QilongTang** [comment]
@dannysbentley Could you send us the file for us to investigate somehow? My email address is aaron.tang@autodesk.com

**Comment by dannysbentley** [comment]
Hi Qilong,

Here is my files.  It seems some of my packages have been removed after installing 1.0.0.  I installed them again, however, clockwork isn’t working in 9.2 after re-installing.

Thank you for your help.

**Comment by ParametricMonkey** [comment]
I'm having the same problem. Running 1.0.0 on windows 10 on bootcamp. Opens fine in v0.9.2

![dynamo error](https://cloud.githubusercontent.com/assets/10913639/14941644/5ebef0be-0fe6-11e6-802b-16836fc6f7b7.JPG)


[Example 2_Part 2 simple.zip](https://github.com/DynamoDS/Dynamo/files/244088/Example.2_Part.2.simple.zip)

**Comment by kronz** [comment]
@ParametricMonkey @dannysbentley I think the issue lies with either/both Flux or Lunchbox nodes.  @archinate is updating Lunchbox to 1.0, not sure about the Flux components.  As Flux uses it's own installer, they may need to create a new installation method now that we have reorganized our Dynamo Core installation process.
![2016-05-02_1228](https://cloud.githubusercontent.com/assets/3456818/14960184/5a48f59a-1061-11e6-8ef3-5575ee9f22e1.png)

**Comment by QilongTang** [comment]
@dannysbentley Could you attach your file again? It is not listed on this page somehow.
@ParametricMonkey Your file opens up fine on my machine and our QA's, but looks like Flux only 100% works with dynamo9.2 and dynamo Studio 2016.
![image](https://cloud.githubusercontent.com/assets/3942418/14960307/10ff2890-1062-11e6-8d0f-d7888b41a3fa.png)

**Comment by archinate** [comment]
@dannysbentley I am working on a 1.0 release for LB.  What is the red error on the LunchBox node? What version of Revit are you testing with?

Best,
-Nate

**Comment by kronz** [comment]
I'm looking at this with Revit 2016 and latest Lunchox.  I can't open the custom node to look any deeper in it.
![2016-05-02_1326](https://cloud.githubusercontent.com/assets/3456818/14961778/74a4d14a-1069-11e6-97a6-f01e3832d3ed.png)

**Comment by dannysbentley** [comment]
@archinate, Nate, I think it got fixed the Floor.SlabShapeByPoints wasn't updating the point.  I tried it this morning and it work perfectly.  
@kronz @QilongTang,  Thank you for looking into this.  The files that wont open are using Flux.  I will reach out to them and see when they will be read to update the install.

**Comment by archinate** [comment]
@kronz the only thing in the node is a Python script and you can't click into it?

That node is working for me in Revit 2016 w/ Dynamo 1.0

![image](https://cloud.githubusercontent.com/assets/1890663/14973481/e8896514-10ad-11e6-9e5d-33658b357221.png)

**Comment by ParametricMonkey** [comment]
@kronz  @QilongTang  so if it has Flux nodes in it, the file won't open at all? Qilong you said you can open the file but Danny says it doesn't open. I'm confused.

I've emailed Anthony from Flux, he has sent me a preview of Flux for Dynamo1.0.0. However....

I uninstalled my Dynamo WIP and reinstalled 1.0.0. But as you can see from the image below, it says 1.0.0 in the Revit menu, but 1.0.1.1115 in the about Dynamo section. Is this correct? Have I done something wrong? I uninstalled all the Dynamo programs first but when installing Dynamo 1.0.0 is said there was a later version of Dynamo core installed. Where can I find this to delete it because it doesn't appear in the add/remove programs.

![dynamo version](https://cloud.githubusercontent.com/assets/10913639/14978262/eaa2eb9e-115d-11e6-92bd-c9e5fe44bc9a.JPG)
.

**Comment by ParametricMonkey** [comment]
OK whats even stranger is in my add/remove programs it says 1.0.0.1180. Something is not right...

![dynamo version2](https://cloud.githubusercontent.com/assets/10913639/14978748/67dea302-1161-11e6-941c-0dc63e8c7866.JPG)

**Comment by sharadkjaiswal** [comment]
@ParametricMonkey, Dynamo 1.0.1.1115 has installed Dynamo Core 1.0.1.1115 and Dynamo Revit 1.0.1.1115, what you have uninstalled is Dynamo Revit 1.0.1.1115 whereas DynamoCore still exists on your system. Right now the version info in Dynamo->Help->About is shown from Dynamo Core hence you see the version of Dynamo as 1.0.1.1115 even if you have installed Dynamo Revit 1.0.0.1180

**Comment by sharadkjaiswal** [comment]
Flux for Dynamo 1.0 should work with Dynamo 1.0.1

**Comment by QilongTang** [comment]
@ParametricMonkey  What I meat was that I was able to open the file you attached with purely DynamoStudio1.0 installed, without the flux plugin for Dynamo0.9.2. I noticed no exception thrown in the  file open process which indicates that the problem lies on other 3rd party components.

Did you encounter the same problem with preview of flux for Dynamo 1.0?

**Comment by ParametricMonkey** [comment]
@sharadkjaiswal How can I uninstall DynamoCore? I can't find it anywhere. I am unable to install Flux 1.0.0 because of this.

**Comment by jnealb** [comment]
@ParametricMonkey Control Panel, Change, Remove?

**Comment by ParametricMonkey** [comment]
@jnealb It is not under Add or Remove Programs

**Comment by ParametricMonkey** [comment]
@kronz @QilongTang Uninstalling Dynamo 1.0.0 anjd tried reinstalling it and am getting this error so it won't open.

![dynamo error](https://cloud.githubusercontent.com/assets/10913639/15003588/9cf26b66-11f0-11e6-8719-06d5a83d81c6.JPG)

**Comment by sharadkjaiswal** [comment]
@ParametricMonkey, It seems that previous version of Dynamo 1.0.0 was not properly uninstalled. Which version of windows are you using? Can you please use https://support.microsoft.com/en-us/mats/program_install_and_uninstall to resolve the uninstallation issue?

**Comment by sharadkjaiswal** [comment]
@ParametricMonkey the error above is due to missing DynamoCore installation on the system. Can you please try to install the latest Dynamo installer from dynamobim.com and see if this error goes away?

**Comment by ParametricMonkey** [comment]
@sharadkjaiswal do you mean the latest WIP or latest stable (1.0.0). I've installed 1.0.0 several times and it hasn't fixed the issue. I'm on windows 7

**Comment by sharadkjaiswal** [comment]
If you are not able to install 1.0.0, then I'll suggest you to use FixIt tool from  https://support.microsoft.com/en-us/mats/program_install_and_uninstall to fix the registry issue. Do you have DynamoStudio installed on your system? Which version of studio it is?

If you install the latest WIP(1.0.1) build then what is the issue you are facing?

**Comment by QilongTang** [comment]
@ParametricMonkey It's been a while since we update the status, did updating to Flux 1.0 plugin fixed this issue? Could you share with me the progress?

**Comment by ParametricMonkey** [comment]
@QilongTang I updated Flux and I believe it worked. But I think Dynamo still needs to be addressed. One would expect that you could open the file but that just the Flux nodes didn't work. Rendering the whole script un-openable is not great.

**Comment by QilongTang** [comment]
@ParametricMonkey Yes, one improvement we made is that for file open errors, the actual call stacks will be displayed in the new Notification center from Dynamo v1.1 instead of just a dialog meaning nothing :) We hope this would help user identify component problems and also if necessary user can send the information to us to help diagnose. Hope this helps and thank you for letting us know, we will continue our effort which hopefully makes Dynamo better. Closing.
