### ISSUE TITLE
Curve.SplitByPoints discards segements of polycurves past the split point

### ISSUE THREAD

**Issue by mccrone** [DynamoDS/Dynamo#6581]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.
## Dynamo version

1.0
## Operating system

Windows 7
## What did you do?

![polycurvesplit](https://cloud.githubusercontent.com/assets/6430819/15056535/056b1a5e-12e0-11e6-93fb-ee3702de7dfe.PNG)
## What did you expect to see?

two poly curves should be returned which if joined back together would create the original polycuve
## What did you see instead?

All segments of the polycurve that are wholly past the split point (parameter values are greater) are discarded.

**Comment by dimven** [comment]
How about the following temporary workaround:

![2016-05-10_17-54-35](https://cloud.githubusercontent.com/assets/7148394/15142548/20268508-16d8-11e6-937e-c1df9ef84de1.png)

**Comment by mccrone** [comment]
@dimven nice!  My workaround was a little less elegant: I reversed the curve, split that, and took the first result

**Comment by kronz** [comment]
@mccrone @dimven @aparajit-pratap I think the bug is a little more subtle.  Curve.SplitByPoints is plural, it wants a set of splitting pointS.  The function returns the polycurve segments that occur BETWEEN split inputs.  So if you add a point at the end of your polycurve, you get the whole collection of Polycurve.  The weird thing in this appears to me that it will ALWAYS return the segments that occur between the start of the polycurve and the first point defined.   But the result is actually that you will ALWAYS get ALL the reulting polycurves if you add a point at the end of your polycurve
![2016-12-16_1025](https://cloud.githubusercontent.com/assets/3456818/21267869/363f006e-c37a-11e6-822e-b912fb7b6f98.png)
![2016-12-16_1020](https://cloud.githubusercontent.com/assets/3456818/21267868/36325eb8-c37a-11e6-9f7a-20324d0876df.png)

**Comment by kronz** [comment]
So, my question is should the proper behavior be that it ALWAYS assumes that you want the pieces between 0 and 1 parameters on the polycurve, or ONLY return the pieces that exist between defined splitting points

**Comment by dimven** [comment]
@kronz Seems like this has been improved in 1.2 :)

**Comment by dimven** [comment]
@kronz actually I take that back. Reran it again on a particular file that was failing for me, and I get the same issue as before. I've serialized the file for easy distribution. You can save as from the below link:

https://raw.githubusercontent.com/dimven/SpringNodes/master/Issues/6581%20polycurve%20split.dyn

I'm not sure if it's because the curve is closed or because of units but I'm getting the following warning on multiple parts of the curve:

![dynamosandbox_2016-12-17_00-09-09](https://cloud.githubusercontent.com/assets/7148394/21269281/170b1908-c3ed-11e6-85d3-cfaa9fc53d4f.png)

**Comment by mccrone** [comment]
@kronz the problem is that the behavior for polycurves is inconsistent with curves.  Just look to the behavior of curves proper to see how polycurves _should_ work.

![inconsistentsplitting](https://cloud.githubusercontent.com/assets/6430819/21271157/d05eda68-c387-11e6-9ac1-8d3ef117a724.png)

Dyn file here:
[https://www.dropbox.com/s/t33pbc12v96l1lb/polyCurveSplit.dyn?dl=0]

**Comment by mccrone** [comment]
@kronz @dimven splitting polyCurves should have the same behavior for splitting singular curves.  The problem is that it's not consistent now.

![inconsistentsplitting](https://cloud.githubusercontent.com/assets/6430819/21271879/c7a76202-c38a-11e6-85eb-eda6ef33cfef.png)

Dyn: https://www.dropbox.com/s/t33pbc12v96l1lb/polyCurveSplit.dyn?dl=0

**Comment by kronz** [comment]
thanks @mccrone , that's the clearest description of the issue yet.  @aparajit-pratap what do you think, any reason split of a polycurve should be any different than split of an arc, line, ellipse, nurbs?

**Comment by aparajit-pratap** [comment]
@mccrone @kronz I agree polycurves should behave like the rest of the curves. There are a number of issues with polycurves as a lot of the algorithms were implemented in Dynamo from scratch (ASM doesn't support them). Lev Lipkin had put in a lot of thought and effort to devise these algorithms. I have been tracking the issues and we'll need to allocate some time to revisit these methods.

**Comment by ParametricMonkey** [comment]
@aparajit-pratap any update on this? It would be good to get implemented.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by aparajit-pratap** [comment]
Fixed in polycurve feature branch.
