### ISSUE TITLE
Curve.SegmentLengthBetweenParameters not implemented for PolyCurves

### ISSUE THREAD

**Issue by mccrone** [DynamoDS/Dynamo#6582]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.
## Dynamo version

1.0
## Operating system

Windows 7
## What did you do?

![nopolycurves](https://cloud.githubusercontent.com/assets/6430819/15057605/a4575952-12e5-11e6-81a1-541ecc2c9168.png)
## What did you expect to see?

A result
## What did you see instead?

an error

**Comment by ikeough** [comment]
@mccrone Were you expecting to see a list of lengths corresponding to the distance between those parameters on each sub-curve of the polycurve?

**Comment by ksobon** [comment]
I think he wanted to see 170 as that would be a (0.2-0.1)*1700 (assuming that curve domain was unitized between 0-1)

**Comment by mccrone** [comment]
![expectedanswer](https://cloud.githubusercontent.com/assets/6430819/15086858/efcfb466-13b1-11e6-98f9-364d4ae7a249.png)

@ikeough

**Comment by riteshchandawar** [comment]
@aparajit-pratap Can you please take a look at it?

Thanks,
Ritesh

**Comment by aparajit-pratap** [comment]
Tracked - http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10102

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
