### ISSUE TITLE
Nested functions in CBN require restart to update

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6591]
## Dynamo version

1.0.1.1250
## Operating system

Windows 10
## What did you do?

Updated a function definition that was a nested within another function in a code block
## What did you expect to see?

The function to update, just as if now does when not nested
## What did you see instead?

The nested function doesn't update. But, if called directly, it does
Works fine on reopening the file.

In the example below _s_ and _ss_ should return the same result

![20160508-1](https://cloud.githubusercontent.com/assets/5621624/15096508/3f88429e-1519-11e6-9131-41be13cf14ec.png)

**Comment by kronz** [comment]
@keyu

**Comment by ke-yu** [comment]
@vykrum that is expected. Whether to trigger update or not is *undecidable*. For example,
```
def foo(x)
{
    return = [Imperative]
    {
        if (x)
        {
            return = bar();
        }
        else
        {
        }
    }
}
```
Here calling `bar()` or not in `foo()` is undecidable, this kind of update is not supported.

**Comment by vykrum** [comment]
@ke-yu As this used to be the behavior with even non nested functions earlier, I assumed this is something that could be resolved.
Ignorant of the technicalities and cost/possibility of doing so, but certainly would be good for nested functions to behave the same as non nested ones. Reopening the file to set right the issue doesn't seem right.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
