### ISSUE TITLE
Improvement: 'helper' inputs for closed curves using Curve.PointsAtEqualChordLength or Curve.PointsAtEqualSegmentLength

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6606]
## Dynamo version

1.0.0
## Operating system

Win 10
## Improvement Suggestion

The Curve.PointsAtEqualChordLength or Curve.PointsAtEqualSegmentLength nodes need a big improvement to deal with closed curves. 

I expect to see points arrayed equally between the curves parameter (t) space. Instead, both nodes place points one division before the end of the curve, leaving a big gaping gap in an otherwise perfect array! 

I think what would work really well would be two new boolean inputs for both nodes: includeStartPoint and includeEndPoint. The user can then decided which to keep or discard, especially where the overlap will occur at the start/end of the closed curve.

![curve pointsatequalchordlength or curve pointsatequalchordlength](https://cloud.githubusercontent.com/assets/18601851/15162758/87deecca-16fc-11e6-8656-5347540398da.jpg)

**Comment by kronz** [comment]
@aparajit-pratap this seems like an oversight, especially as our other similar tools include start and end points.  Any particular reason for the current implementation? Thanks

**Comment by riteshchandawar** [comment]
Here is the issue for tracking internally. http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10099

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by pinzart90** [comment]
Dynamo now handles closed curves properly (so one of the end points will be included)
