### ISSUE TITLE
Point At Parameter on Projected curve

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6612]
## Dynamo version

1.0.1.1311

## Operating system

Windows 10

## What did you do? 

Curve.PointAtParameter on a projected curve

## What did you expect to see?

Specified multiple parameters and expected multiple points (as it did on the original curve)

## What did you see instead?

Just one point

![20160511-2](https://cloud.githubusercontent.com/assets/5621624/15180696/c942bfe4-17a0-11e6-9840-24572cafa971.png)

**Comment by kronz** [comment]
Hi @vykrum.  I hate to say it, but everything here is behaving as designed.  First, Curve.Project, and really all of our intersection event operations, will return a list.  Imagine you are projecting a curve on a "c" shaped geometry, you will get 2 or more curves as a result.  These kinds of operations are set up to give consistent structures.  Second, lists are things, if you are passing a list of items to match with another list of items, and you have Shortest lacing, the first item on the list will match with the first item on the other list, second, and so on.  Just because you have a list with only one item in it doesn't mean that it isn't a list.

**Comment by vykrum** [comment]
@kronz Realized that lacing solves the problem, but it didn't feel right. No way to reduce single items to non lists? (Apologies in advance for my ignorance)
Also the points are not evenly spaced on the projected curve. But I suppose that is a separate issue.

**Comment by kronz** [comment]
All good questions.  If you know that you are always going to only get a single item, List.FirstItem is a good method. The points are evenly spaced for the parameter space of the curve.  If you want equal segment or chord length, use Curve.PointsAtEqualSegmentLength, Curve.PointsAtEqualChordLength
![2016-05-11_1323](https://cloud.githubusercontent.com/assets/3456818/15189966/881da8e6-177b-11e6-8eac-895a45a15dee.png)
