### ISSUE TITLE
Curve.PointAtChordLength problems

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#6617]
## Dynamo version

1.0.0.1180
## Operating system

Windows 7
## What did you do?

Used the "Curve.PointAtChordLength" to place points evenly on a curve.
1) It worked for an open curve.
2) It placed the points incorrectly on a closed curve
3) It outright fails for a Polycurve & Rectangle input types
## What did you expect to see?

![2016-05-12_11-52-22](https://cloud.githubusercontent.com/assets/7148394/15203805/c7e9bafa-1839-11e6-8ffa-3000d0da2339.png)
## What did you see instead?

![2016-05-12_11-53-48](https://cloud.githubusercontent.com/assets/7148394/15203807/cbc92e08-1839-11e6-99c2-a1a2a4ef50fc.png)

This also looks messed up:

![2016-05-12_12-01-02](https://cloud.githubusercontent.com/assets/7148394/15203813/d533a1ee-1839-11e6-9f77-b9bf227c5398.png)

**Comment by riteshchandawar** [comment]
@aparajit-pratap Can you please take a look at this?

Thanks,
Ritesh

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
