### ISSUE TITLE
Excel.WriteToFile node corrupts formulae in referencing worksheets

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6664]
## Dynamo version

1.0.0
## Operating system

Win 10
## What did you do?

Write data from Dynamo to an Excel (v2007) workbook. The Excel is a template which has two sheets: a data dump from Dynamo and sheet which processes the incoming data using ordinary Excel formulas.
## What did you expect to see?

Any new data being copied to the Excel from Dynamo to be processed by the formulas set up in the second worksheet
## What did you see instead?

Dynamo appears to corrupt all of the formulas in the second worksheet as they report #REF! once the incoming data is overwritten in the first worksheet. It appears that Dynamo is deleting and recreating the worksheet instead of simply writing to it. See images for example workflow and problem:

**Workflow**
**1. Create the graph and write some data to Excel worksheet:**
![update data to excel dynamo](https://cloud.githubusercontent.com/assets/18601851/15504738/4e86619e-21b8-11e6-940d-7cd15f6f3b0c.JPG)
![write data to excel in sheet1](https://cloud.githubusercontent.com/assets/18601851/15504666/fb984588-21b7-11e6-97da-1ce6cf79e78c.JPG)

**2.In the second worksheet write some formulas to process the incoming data from the first worksheet:** 
![process data using formulas in sheet2](https://cloud.githubusercontent.com/assets/18601851/15504668/fb990d4c-21b7-11e6-9d80-48c106208831.JPG)

**3. Update Dynamo and write the new data back to Excel:**
![write data to excel dynamo](https://cloud.githubusercontent.com/assets/18601851/15504667/fb985244-21b7-11e6-9936-bce384abf0b4.JPG)
**4. The formulas in the second worksheet are now corrupted:**
![corrupts formulae](https://cloud.githubusercontent.com/assets/18601851/15504772/7a05ed44-21b8-11e6-8154-ecc363f38dd5.JPG)

**Comment by aparajit-pratap** [comment]
Thanks @ThomasMahon for reporting this.

**Comment by aparajit-pratap** [comment]
Tracked as: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10215

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
