### ISSUE TITLE
Improvement: All sweep methods using a profile and path are limited and need an 'up' direction input 

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6694]
## Dynamo version

1.0.1.1421
## Operating system

Win 10
## Improvement Suggestion

I am finding the BySweep methods that use a path and profile, whether from the Curve, Surface or Solid category, very limited and really needing an additional 'up' direction to improve their functionality. 

For example, I am sweeping an ellipse profile along a path curve to create a handrail, but the profile rotates 90 degrees along the length of the path and there is no way to control it. If there was an optional 'up' vector which could constrain the profile along the Z axis while using the normals of the curve to calculate the X and Y then this wouldn't be an issue. 

In the example below, the profile rotates 90 degrees along the length of the path curve using the Surface.BySweep node. The same behaviour occurs using the Solid.BySweep and Curve.SweepAsSolid nodes:

![capture](https://cloud.githubusercontent.com/assets/18601851/15808292/132f0296-2b6c-11e6-9d72-e9880a06c836.JPG)

**Comment by dimven** [comment]
Sounds like a good addition. How about this work-around in the mean time:
![2016-06-06_10-06-59](https://cloud.githubusercontent.com/assets/7148394/15810145/5b2fe2e2-2bce-11e6-9553-e4674bcb79c6.png)

**Comment by ThomasMahon** [comment]
@dimven good suggestion but its not a solution as it doesn't honour the normals of the curve which in turn screws up the sweep. (Blue/highlighted curve is correct, the black are using planes derived from Curve.HorizontalFrameAtParameter): 

![capture2](https://cloud.githubusercontent.com/assets/18601851/15816538/1d82b79c-2bcb-11e6-99c5-1af86ec6b616.JPG)

**Comment by dimven** [comment]
Whoops. An alternative to the alternative then? :)

- generate a generic CS/plane
- get its "up" direction
- calculate an angle between that and the global Z axis
- rotate the CS/plane
- use that for the ellipse

**Comment by ThomasMahon** [comment]
@dimven Yep, that's the easy bit...but two profiles means using Solid.ByLoft to generate the handrail...and it always fails even when the planes are corrected. See #6692
Dynamo needs a serious upgrade to its geometry engine. This is effortless in Generative Components. I'm shocked it cant handle it! Appreciate your input nonetheless

**Comment by kronz** [comment]
@ThomasMahon Let me restate and see if I get what you are asking for. You want to be able to create a sweep that pins a Z vector for the profile, but follows a path X and Y normals?  Can you identify controls in another tool that result in the shape you are after?  I'm sure there are a few, I just want to make sure we understand your goals

**Comment by ThomasMahon** [comment]
@kronz thats correct, so if a plane is placed by parameter on the path curve, the normal of the plane should be coincident with the normal of the path, the X-axis of the plane should be parallel with world X and the planes Y-axis should be the cross-product of both (therefore following trajectory of the word Z axis). The order of the vectors to construct the plane is important as the orientation to Z shouldn't cause the coincidence of the planes normal and path curve normal from deviating. Therefore, to achieved the desired orientation, the normal should take precedent, the X-axis should be the secondary constraint and finally the cross product defines the plane Y-axis. The cross product should be pointing 'up' to eliminate any rotation which may occur as a result of the curvature of the path curve.

`Curve.PlaneAtParameter` seems to achieve the desired effect, but that leads to the next problem (which may be caused by a problem with my path curve) where the Solid.ByLoft method fails when providing the path curve and two profiles - one at t = 0.0 the other at t = 1.0

![image](https://cloud.githubusercontent.com/assets/18601851/17385718/5af34f30-59dc-11e6-87d7-6a572ccc2859.png)

**Comment by kronz** [comment]
@ThomasMahon Ok, sounds like you are probably using "roadlike top" in Rhino, or similar?   I think you will get the same results when you use Solid.BySweep2Rails offsetting the a centerline sweep to match the edges of the profile?
![2016-08-03_2118](https://cloud.githubusercontent.com/assets/3456818/17387248/de64b0ce-59bf-11e6-80e8-9796a9a9be6c.png)

**Comment by kronz** [comment]
BTW, the behavior is also very consistent between the 2 approaches if you are using a helix versus a nurbs curve, which naturally have less predictable normals.
![2016-08-03_2120](https://cloud.githubusercontent.com/assets/3456818/17387290/4a246d18-59c0-11e6-9cd8-1eef6785b0e7.png)

**Comment by ThomasMahon** [comment]
@kronz No, I'm using Dynamo throughout (though, the stair was originally modelled successfully in GenerativeComponents). The elliptical helix is generated by arraying points around an ellipse and projected the points onto a matching set of offset planes. Hence, I am not using the OTB helix node as it doesn't serve my needs. 

The example image in my previous post shows the overall path curve, built from nurbs curves and lines then joined to form one path curve using `PolyCurve.ByJoinedCurves`. As the path curve is not a single curve offsetting is not an option as it results in discontinuity errors. In addition, an offset using world Z isn't going to yield the right result, since the offset wont be 'perpendicular' to the original curve, or rather the resulting cross-section of the solid form will be sheared. I've attempted this anyway using the axes from the profile plane to circumvent this problem, but its still impossible to generate this form.

This is the result of the offset (geometry translate...Curve.Offset fails):
![image](https://cloud.githubusercontent.com/assets/18601851/17431983/9b6dc7fc-5af4-11e6-97ec-f8ddf239be89.png)

Here's the error:
![image](https://cloud.githubusercontent.com/assets/18601851/17432002/aeb8127c-5af4-11e6-9444-c22c08ee75d2.png)

This is basic stuff as far as computational design goes. Are there any upgrades to the Dynamo geometry engine in the pipeline that will be able to handle modelling tasks such as this?

**Comment by kronz** [comment]
@ThomasMahon Right, I see that you are using Dynamo throughout (awesome), what I was curious about with Rhino's "roadlike" sweep is to get a better sense of what comparable functionality you are looking for with simple property adjustments in your original approach, not your eventual attempts at workarounds.  That is, you WANT to just be able to supply a profile and a path, and be able to override the "natural" flow of the profile across the path with a Z-Axis over-ride, everything else is a workaround.  I'd like for us to be able to deal with the ideal functionality (ui and functional improvements) first, and look seperately at possible bugs in existing tools (G1 continuity issues)   

For the particular issue around G1 continuity, can you send me your graph at Dynamo@Autodesk.com so that we can trouble shoot it?

**Comment by ThomasMahon** [comment]
@kronz I've just emailed now. To reiterate, yes I would like to have the ability to override the 'natural flow' of the profile across the path (using a vector).

**Comment by aparajit-pratap** [comment]
@ThomasMahon I managed to loft the handrail over each curve segment of the polycurve individually. I know it is not a complete loft of the original polycurve since the `Solid.ByLoft` operation will fail for discontinuities in the guide curve. Is this the profile of the lofted handrail the one you’re expecting (or at least an approximation) from the Sweep node with `upvector` control? If so, this is one way you could get around doing it. At the same time we can try coming up with improvements for the Sweep method based on your feedback for the `upvector`. 
![image](https://cloud.githubusercontent.com/assets/5710686/17507330/a9b5fc30-5e41-11e6-86ba-133e2ff78562.png)

The way to get the `upvector` for a point on the curve is to use the `CoordinateSystem.AtParameter` node which, as the description says returns a CS with its Y-axis tangential to the curve, the X-axis in the direction of the curve normal and the Z-axis of the CS, here, is the `upvector` or `binormal` vector of the curve. That is why I have used the local ZX plane of the CS as the plane for the ellipse. Perhaps we should add the missing piece of information for the Z-axis in the node description.
![image](https://cloud.githubusercontent.com/assets/5710686/17507436/2e33753c-5e42-11e6-9d09-0c1f6e3b386a.png)

**Comment by aparajit-pratap** [comment]
@ThomasMahon i'm afraid we won't be able to deliver your "up vector" request for these methods as there is no immediate support for this functionality. The workaround suggested here will be the only way to accomplish this workflow. I'm closing this issue but we are open to other alternative suggestions from you.

**Comment by ThomasMahon** [comment]
@aparajit-pratap I found an alternative way to achieve my desired result using v1.3.1. Its inefficient and cumbersome but highlights my point about the need for Dynamo to start making in-roads into becoming a powerful computational design tool. The trick is to use `Curve.HorizontalFrameAtParameter`, then use the resultant X axes and corresponding tangents to compute the cross product, and use these vectors to create new planes using `Plane.ByOriginXAxisYAxis`:

![image](https://user-images.githubusercontent.com/18601851/29659336-d70c39ca-88b5-11e7-9ac7-699956a4d31a.png)

**Comment by asdasdad5464** [comment]
> @aparajit-pratap I found an alternative way to achieve my desired result using v1.3.1. Its inefficient and cumbersome but highlights my point about the need for Dynamo to start making in-roads into becoming a powerful computational design tool. The trick is to use `Curve.HorizontalFrameAtParameter`, then use the resultant X axes and corresponding tangents to compute the cross product, and use these vectors to create new planes using `Plane.ByOriginXAxisYAxis`:
> 
> ![image](https://user-images.githubusercontent.com/18601851/29659336-d70c39ca-88b5-11e7-9ac7-699956a4d31a.png)

Do you have the whole of this diagram? Thank you!
