### ISSUE TITLE
Mesh with large face renders offset from construction points

### ISSUE THREAD

**Issue by oderby** [DynamoDS/Dynamo#6715]
## Dynamo version

1.0.0.1180
## Operating system

Windows 7
## What did you do?

Open the attached dynamo file. [dynamo_mesh_bug_1.zip](https://github.com/DynamoDS/Dynamo/files/306250/dynamo_mesh_bug_1.zip)
## What did you expect to see?

Meshes rendered aligned with the construction vertices.
## What did you see instead?

Meshes offset by an arbitrary amount in the z direction.
![image](https://cloud.githubusercontent.com/assets/1351158/15920747/4e7fe6fa-2dd1-11e6-9941-2100dd8683a2.png)

Note, this doesn't seem to be an issue if the points are much closer to the origin.

**Comment by ThomasMahon** [comment]
I think you've answered your own question: if objects are a considerable distance from file centre then the behaviour you describe arises due to floating point tolerance issues. Its therefore a limitation of modern-day computer architecture rather than a problem exclusive to Revit and/or Dynamo. 
The solution, therefore, is to simply build your model closer to file centre/origin. If you need to use true OS coordinates, then update your Revit project Survey Point by acquiring coordinates from a DWG typomap.

**Comment by oderby** [comment]
I don't think that's the problem here. the points are nowhere near far enough away to have rounding issues due to floating point tolerance, and the offsets of the meshes are also not a tolerance/rounding issue. You can move the points closer together and still see the offset - in fact, the offset appears to be proportional to the area of the mesh face.

Further, reproducing this in Grasshopper or any other similar modelling tool does not produce this behavior. So even if this were due to floating point tolerance, it's clearly a solvable problem.

**Comment by mjkkirschner** [comment]
hey @oderby does this also occur when creating surfaces by points? or only meshes?

**Comment by oderby** [comment]
No, this does not occur if creating surfaces from the same points
![image](https://cloud.githubusercontent.com/assets/1351158/15939664/9f33d294-2e2d-11e6-91cc-289739bb1205.png)

**Comment by aparajit-pratap** [comment]
@ellensi could you confirm if your fix #7622 fixes this issue?

**Comment by ellensi** [comment]
Yes, PR #7622 should fix this issue!

![image](https://cloud.githubusercontent.com/assets/6386550/23244786/b48a275e-f9c2-11e6-959f-00164f5c9793.png)
