### ISSUE TITLE
Point Geometry in Imperative Block

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6751]
## Dynamo version
1.0.1.1683

## Operating system
Windows 10

## What did you do? 
Tried using _PointGeometry_ in an Imperative block

## What did you expect to see?
Results similar to those obtained using other approaches

## What did you see instead?
![20160619-2](https://cloud.githubusercontent.com/assets/5621624/16178010/08f0ff6a-365b-11e6-8b39-3be274aff791.png)

**Comment by dimven** [comment]
That's probably because v is a list and to get the point from each vertex, you have to iterate through the list. Lacing and replication guides still don't work in imperative mode:

![2016-06-21_10-29-34](https://cloud.githubusercontent.com/assets/7148394/16216145/f339dd68-379a-11e6-9807-bcd247bb812a.png)

**Comment by vykrum** [comment]
@dimven Makes sense 
No issue here then :-)
