### ISSUE TITLE
using enum as default value throws exception on library import

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#6783]
- will file internally when I can.
## Dynamo version

1.x
## Operating system

windows 7
## What did you do?

use a public enum also imported into the VM using ZT as a default value for a parameter to a static method 
## What did you expect to see?

can import the library
## What did you see instead?

instead the library importer throws exception because it can't build an AST input node using the enum (can't convert it to primitive type)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
