### ISSUE TITLE
Point.Project fails

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6831]
## Dynamo version

1.0.1.1757
## Operating system

Windows 10
## What did you do?

Attempted to use _Point.Project_
## What did you expect to see?

Results similar to those obtained using _Surface.ProjectOnto_
## What did you see instead?

![20160701-2a](https://cloud.githubusercontent.com/assets/5621624/16513594/8e84eca0-3f83-11e6-97cd-152b6c7d27ac.PNG)

**Comment by aparajit-pratap** [comment]
Tracked in: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7732

**Comment by aparajit-pratap** [comment]
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10348

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
