### ISSUE TITLE
Geometry.Scale - performed on Lines, returns Nurbs Curves, not Lines

### ISSUE THREAD

**Issue by Curty102** [DynamoDS/Dynamo#6845]
## Dynamo version

1.0.0.276
## Operating system

Windows 7 Enterprise
## What did you do?

Geometry.Scale  (Uses Geometry, Plane, X, Y, Z as inputs) --  when performing
 on lines (not curves or nurbs curves) this returns nurbs curves, not lines.

![nurbs_not_lines](https://cloud.githubusercontent.com/assets/13457861/16564440/14defbd8-41cd-11e6-99e8-0391e21ac79f.PNG)
## What did you expect to see?

Lines
## What did you see instead?

nurbs curves.

**Comment by johnpierson** [comment]
Still persists in 2.0.1

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
