### ISSUE TITLE
Help PolyCurve.ByThickeningCurve

### ISSUE THREAD

**Issue by paula0210** [DynamoDS/Dynamo#6966]
## Dynamo version

1.0.0.1180
## Operating system

(Windows 10
## What did you do?

I am trying to thicken a curve, but when i use PolyCurve.ByThickeningCurve and defined the normal vector, the direction that they take is not the same of  the vector that I have defined.
The normal vector was defined with help of the plane.

![01 08-5](https://cloud.githubusercontent.com/assets/20767423/17287922/b4ea99aa-57d2-11e6-99fb-80205f3037f3.png)

![01 08-2](https://cloud.githubusercontent.com/assets/20767423/17287928/bc42225e-57d2-11e6-90b5-03e68df24100.png)
## What did you expect to see?

![01 08-4](https://cloud.githubusercontent.com/assets/20767423/17287936/c4906272-57d2-11e6-90b9-e17d76c75e29.png)
## What did you see instead?

![01 08-1](https://cloud.githubusercontent.com/assets/20767423/17287941/cafecb62-57d2-11e6-80f0-6ed4d6782382.png)

![01 08-3](https://cloud.githubusercontent.com/assets/20767423/17287944/cf063790-57d2-11e6-9bb2-6d367739b163.png)

**Comment by vykrum** [comment]
Encountered the same problem ...
![thickencurve-error](https://cloud.githubusercontent.com/assets/5621624/17463276/fd5bc99a-5cdf-11e6-8bad-6109ede0a14f.png)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by aparajit-pratap** [comment]
This has been fixed. Refer to forum discussion: https://forum.dynamobim.com/t/help-polycurve-bythickeningcurve/5342/10.
Marking this as fixed.
