### ISSUE TITLE
Custom node library displaying nodes from Dynamo Revit backup folder

### ISSUE THREAD

**Issue by brianringley** [DynamoDS/Dynamo#6968]
## What did you do?

Look at my custom nodes in the Library panel.
## What did you expect to see?

Only custom nodes from my Dynamo Revit definitions folder:
C:\Users[username]\AppData\Roaming\Dynamo\Dynamo Revit\1.1\definitions
## What did you see instead?

Custom nodes from my Dynamo Revit backup folder:
C:\Users[username]\AppData\Roaming\Dynamo\Dynamo Revit\backup

![backup](https://cloud.githubusercontent.com/assets/6502496/17305135/1ce0c704-57f7-11e6-94ad-d3e7622664eb.png)

**Comment by brianringley** [comment]
FYI I have recently discovered that it is loading from other local drive locations, e.g. my locally synced Box.com backup of my custom nodes. This is really confusing - now I'm not sure where my nodes are actually linking to. **Is there a way to view the link path?**

**Comment by ke-yu** [comment]
@Randy-Ma ?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
