### ISSUE TITLE
Improvement: Rectangle and Polygon library confuses users

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6996]
## Dynamo version

1.1.0
## Operating system

Win 10
## Improvement Suggestion:

The Polygon and Rectangle library confuses users and I would like to suggest that they are consolidated. 

Here's a typical workflow which is inconsistent: 
1. Expand Rectangle library
2. Create a Rectangle by Plane, Width, Length
3. [user needs to extract corner points], so they navigate to the Action nodes under Rectangle...nothing
Instead, they have to be conscious that Rectangle and Polygons are essentially the same thing, so:
4. Expand Polygon library, and use `Polygon.Corners`

As the above example illustrates, the workflow is protracted and not necessarily obvious where really these actions are all related. Can the two libraries be consolidated?

![image](https://cloud.githubusercontent.com/assets/18601851/17435414/9970a5dc-5b08-11e6-9863-3aae461231ed.png)

![image](https://cloud.githubusercontent.com/assets/18601851/17435421/a50cee5a-5b08-11e6-966e-88678c7ec426.png)

![image](https://cloud.githubusercontent.com/assets/18601851/17435428/b1e6f5f8-5b08-11e6-804a-5c974c786fc8.png)

**Comment by kronz** [comment]
@aparajit-pratap Correct me if I have this wrong, but I think the hierarchy goes:  Curve>Polycurve>Polygon>Rectangle?  
That is everything you can do as an action or query to Polygon you can also do to Rectangle, but not the reverse.  Rectangle has the particular Queries of Height and Width, and is a subset of Polygon.  
All this to say that they are different, but that we need to do a better job of showing how the hierarchy and subsets are arranged.

**Comment by aparajit-pratap** [comment]
@kronz yes this is the hierarchy: Curve>Polycurve>Polygon>Rectangle with Curve being the top-most base class and Rectangle being the at the bottom.

**Comment by andydandy74** [comment]
I would rather like to see inherited methods in all categories than a node browser restructured according to entity hierarchy. I think the current browser structure is fairly flat - and that's a good thing.

**Comment by ThomasMahon** [comment]
I know Rectangle is a distinct class, and from a programmatic standpoint it makes sense to separate them into their own categories in the library. However, from a user perspective, I've observed that new users in particular find it very confusing, especially as Action nodes from one can be used with the other. Only the curve library has similar behaviour, but that's an abstract class that covers all curve types which is far easier to comprehend. If the libraries were consolidated, then the description or exception warning can be used to deal with the Height and Width Action node only working on Rectangles. It would also mean a 4 point polygon with 90 deg corners would cast automaically.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
