### ISSUE TITLE
Editing a Custom node instance does not give that instances inputs

### ISSUE THREAD

**Issue by cjm771** [DynamoDS/Dynamo#7011]
(Which version of Dynamo are you using? 
1.0
## Operating system

(e.g. Windows 7, Windows 8.1, etc)
Windows 7 
## What did you do?

Double click or Right click > edit custom node on a custom node Instance. 
## What did you expect to see?

Instead of seeing the input data from that specific instance, I get the input data from another instance (Im guessing the last one created). When double clicking a custom node instance, that specific instance's inputs should be the ones in the custom node workspace.

**Comment by ke-yu** [comment]
@cjm771 do you have a sample file?

**Comment by cjm771** [comment]
@ke-yu [http://imgur.com/a/g3mrb](url)


Download sample definition: [dynamo_issue.zip](https://github.com/DynamoDS/Dynamo/files/409947/dynamo_issue.zip)

**Comment by smangarole** [comment]
Thanks @cjm771 - I can reproduce.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
