### ISSUE TITLE
Sublists node issue

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7063]
## Dynamo version
1.1.1.2302

## Operating system
Windows 10

## What did you do? 
Used _List.Sublists_ node with lacing set to Longest

## What did you expect to see?
Results similar to that obtained in the code block as in the image below

## What did you see instead?
![20160820-i1](https://cloud.githubusercontent.com/assets/5621624/17829047/6cd7d664-66be-11e6-95a0-3e8efbaf6486.PNG)

**Comment by ke-yu** [comment]
hi @vykrum they are different...for the node that is using longest lacing, it is equivalent to the following code
```
List.Sublists(list<1L>, ranges<1L>, offset<1L>)
```
So it will do zip replication on these three inputs.

If your code block node, `<1>` is only after the first argument, so it means force iteration on the first input.

BTW,  we can't append replication guide to literal value like `1`, this is a bug.

**Comment by vykrum** [comment]
@ke-yu  My concern is actually with the node, not the code block
I would have expected the Sublists node with lacing set to Longest to generate a list similar to that in the code block (refer to the image in my original post).
Am I mistaken?

**Comment by ke-yu** [comment]
@vykrum , they won't generate same result - 

For code block node, it is `List.Sublists(list<1>, 0..1, 1)`
For node, as you apply longest lacing, it is equivalent to `List.Sublist(list<1L>, (0..1)<1L>, 1<1L>)` (a bug that we can't append `<1L>` to a literal value).

So for code block node, it is equivalent to 
```python
    for each x in list
        sublist(x, 0..1, 1)
```

For node, it is equivalent to
```python
    for each x, y, z in list, 0..1, 1
        List.Sublists(x, y, z)
```
Here `1` will be promoted to an array so that it could be iterated.

More details about lacing/replication/replication guide could refer to these wiki pages about replication and replication guide [1](https://github.com/DynamoDS/Dynamo/wiki/Replication-and-Replication-Guide-Part-1), [2](https://github.com/DynamoDS/Dynamo/wiki/Replication-and-Replication-Guide-Part-2) and [3](https://github.com/DynamoDS/Dynamo/wiki/Replication-and-Replication-Guide-Part-3).

**Comment by vykrum** [comment]
@ke-yu Thanks for explaining. 
Realize it wasn't really an issue.
