### ISSUE TITLE
Associative DesignScript functions returning different / inconsistent results 

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7169]
## Dynamo version

1.2.0
## Operating system

Win 10
## What did you do?

Wrote simple Associative function, one explicitly declared and one implied.
## What did you expect to see?

Both to return the same results following the Dynamo VM calculation
## What did you see instead?

Inconsistent results, the Associative code with an explicit declaration appears to behave like an Imperative block. Am I missing something?

![image](https://cloud.githubusercontent.com/assets/18601851/18610483/79d6b2b4-7d15-11e6-9eb9-2a1f9cae21cc.png)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
