### ISSUE TITLE
CefSharp not loading

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7170]
Is there a reason why this library would not load into Dynamo? When I try including it in my package it will make the whole package fail. 

I am not sure if this has anything to do with the fact that CefSharp can only be built for either x64 or x86 and not the recommended All CPU. I can't think of anything else. Ideas? 

https://github.com/cefsharp/CefSharp

**Comment by mjkkirschner** [comment]
@ksobon thats a good guess, have you tried targeting x64?

**Comment by ksobon** [comment]
Yeah i tried. The CefSharp.Core.dll just won't load into Dynamo. It seems like Wpf dll is loading just fine. Can someone else try this and confirm? What are my options here? Is this just not supported at all?

**Comment by mjkkirschner** [comment]
have you recompiled both the native and managed dlls for x64?

Try using fusion logger (google this) to find the native assembly bind error

**Comment by ksobon** [comment]
So positive on making sure that dlls are not marked as node libraries. 

I never heard of Fusion Logger but I will poke around on that and get back to you. 

Well, I have 4 dlls in my package but i only needed one to reference cefSharp so I built that against x64. I think that might have been a mistake because now, it could have been referencing dlls from my other 3 libraries (they share some references as well as reference each other) and I haven't built the other 3 dlls against x64. What you are saying is that I should build the whole project against x64, and hence make sure that all references used are compatible with that infrastructure?

**Comment by mjkkirschner** [comment]
my understanding is that native libraries cannot be compiled for x86 and x64 like managed libraries, as they are actually compiled to byte code, not IL which will then be jitted.

so what should happen is that depending on what kind of process they are actually imported into the correct version x86 or x64 is loaded, but thats up to the author of the library to figure out, not something .net does.

So check this answer out for some more info:
http://stackoverflow.com/questions/3787428/loading-x86-or-x64-assembly

If that native c++ core lib is compiled to x86 but Dynamo is running as x86 it won't be able to load with a platform exception.

Compiling for AnyCPU lets .net libraries get jitted into the correct process at load time (my understanding) so it's not clear what platform Dynamo is running on your machine, but I'll guess x64 since I believe the geometry library is only compiled for x64 as well.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
