### ISSUE TITLE
Custom Node inputs change order or are removed without honouring connected nodes

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7199]
## Dynamo version

1.2.0.2654
## Operating system

Win 10
## What did you do?

Built a custom node and removed or replaced the `Input`nodes. 
## What did you expect to see?

**When removing input nodes**
That any node(s) connected to the CN, honour (associate with) their input, and any node(s) connected to the input argument(s) that are removed get automatically disconnected

**When replacing input nodes**
Firstly, its worth stating that the inputs to the CN package are generated by the order that the `Input`nodes were created in the CN's graph.

I therefore expect to see any nodes connected to the CN honour (associate with) their input and automatically move should the CNs input shift due to the behaviour described above. 
## What did you see instead?

**When removing input nodes**
The nodes connected to the CN remain static and whichever node was connected to the final input gets disconnected - basically there is no association with the nodes connected and their input to the CN.

**When replacing input nodes**
Any nodes connected to the CN remain static, while the CN's inputs shift. This obviously throws an exception as datatypes invariably change, or if that doesn't happen, the output is erroneous as the inputs have unwittingly changed.

This animation shows the problem of replacing an `Input`node in the CN. If the `Input`node is deleted, the same behaviour is experienced, only that the node connected into the last input of the CN is disconnected:
![custom-node-input-changes](https://cloud.githubusercontent.com/assets/18601851/18834797/c8430d40-83ef-11e6-9654-a2ea875a7da3.gif)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
