### ISSUE TITLE
UI Slide out panel node descriptions show "var" for all custom objects

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7225]
## Dynamo version

Dynamo 1.2
## Operating system

Windows 7
## What did you do?

Creating a custom node in ZT that receives an input/returns a custom class object, will result in that input/output port description to always say "var" instead of the class name. Can that be corrected? 
## What did you expect to see?

Class Name
## What did you see instead?

var

![untitled-1](https://cloud.githubusercontent.com/assets/529781/18997919/81406da8-8704-11e6-9be9-1d8dfe879db8.jpg)

**Comment by ke-yu** [comment]
@ksobon is that class imported into Dynamo?

**Comment by ksobon** [comment]
DLL that houses it, is not defined as "node library" so technically no, its not imported into Dynamo. For cases as such we should allow for adding attributes or some sort of XML comment to set that value to something relevant. Don't you think?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
