### ISSUE TITLE
Convex hull not outputting as expected

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7229]
## Dynamo version

1.1.0
## Operating system

Win 10
## What did you do?

Convex Hull with 1D list of points (about 600)
## What did you expect to see?

A Convex hull
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/18601851/19015251/a9904e6e-87f8-11e6-8bf1-5cb4b05cf7fe.png)

**Comment by dimven** [comment]
It's not very intuitive but that's how Dynamo's CH implementation has worked since forever. If you'd like to create face triplets, just chop the list. If you want to visualize the faces, you can feed those triplets into a surface.byperimeterpoints

**Comment by ThomasMahon** [comment]
I think it needs a big overhaul if that is the case. A convex hull function - as I'm sure you would agree - should do this:
![10pointshull1](https://cloud.githubusercontent.com/assets/18601851/19020002/ebc6b5fc-8893-11e6-9204-82522ba44cc7.png)

**Comment by dimven** [comment]
Hmm, I didn't notice that in your picture it didn't encapsulate all the points, it looks like a bug. Are your points flat? That might be causing some issue. It works as expected for 3d sets of points:

![revit_2016-10-02_18-41-03](https://cloud.githubusercontent.com/assets/7148394/19020039/0860449e-88d0-11e6-9674-0316916146a2.png)

Clockwork has a node that works for 2d data sets called "UV.ConvexHull2D".

**Comment by ThomasMahon** [comment]
Yep, 2D points created using `Point.ByCoordinates`

![image](https://cloud.githubusercontent.com/assets/18601851/19020060/dfd95b8a-8895-11e6-83ec-a912c5649d09.png)

**Comment by dimven** [comment]
Hmm the question then should be, does the built-in convex hull even work with 2d points?

**Comment by andydandy74** [comment]
It's a 3D algorithm, see discussion in #5194

**Comment by ThomasMahon** [comment]
@dimven @andydandy74 3D only! I'm a bit surprised. Would have thought it would be split into 2D and 3D versions.

Hi @ikeough in ref to #5194 is this likely to be implemented in future Dynamo releases or should this be a community-driven initiative maybe building on the great work @dimven has started with UV.ConvexHull2D?

**Comment by dimven** [comment]
It's actually the great work of @andydandy74 and Wikipedia :)

**Comment by ThomasMahon** [comment]
Thanks for point that out! Great work @andydandy74 !

**Comment by mccrone** [comment]
@ThomasMahon @andydandy74 @dimven @kronz And here's another approach for any set of planar points. Input is a polycurve just to keep things organized. All in Design Script.
![convexhull](https://user-images.githubusercontent.com/6430819/32208704-5dee9920-bdc1-11e7-9f14-09e00b98dfa6.PNG)

**Comment by jnealb** [comment]
@mccrone Nice.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
