### ISSUE TITLE
Is there a way to know if an input to a particular port has changed?

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7230]
This is more of a question than an issue, but I would like to know if a specific input on one of the ports for a Variable Input node has changed. Basically I want to avoid a situation when my node has to re-process al of the inputs again, instead I would like to know that a new value is present for input 5 and then I can have a routine that will collect the value from that input and do something with it. Is that kind of routine possible? Any examples? 

Cheers!

**Comment by mjkkirschner** [comment]
AFAIK ports don't have values, nodes do.... unless using default values and thats another story entirely.

SO...
There might be a better way, but what comes to mind first is to walk all your ports, subscribe to the propertyChange notification on the nodeModels attached to those ports:

NodeModel's raise this event when their stored value changes - 
RaisePropertyChanged("CachedValue");

You can then do something with that knowledge, but you'll need to unsubscribe from those events when the upstream nodes are disconnected from the ports, you can do that by subscribing to the ports connected and disconnected events.

This all has to be done using a NodeModel node.

**Comment by mjkkirschner** [comment]
Another thought... Dynamo is going to figure this out for you as part of the live runner and execute that node again when any of it's inputs change, ... why not build that logic into your main execution method directly, IE, save the previous value of the input (you can use trace for this) and then check it against the new value to determine what to do.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
