### ISSUE TITLE
Associate one `Watch3DViewModel` with each `HomeWorkspaceViewModel`.

### ISSUE THREAD

**Issue by ikeough** [DynamoDS/Dynamo#7311]
Currently there is one `HomeWorkspaceViewModel` that acts as the Data Context for the `HelixWatch3DViewModel` which is the data context for the background preview. When we switch the data model to having multiple home workspaces, we need to make one background preview per home workspace model. This might also be the case for selection.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
