### ISSUE TITLE
Move Background Previews selection for workspace views onto the view (context menu?).

### ISSUE THREAD

**Issue by ikeough** [DynamoDS/Dynamo#7312]
Keep Background Previews selection for Revit (and other contexts) in the main menu. This will require some consolation with @Racel, to make sure it's not completely crazy.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
