### ISSUE TITLE
Anonymous DesignScript Imperative block with an internal unassigned parameter doesn't throw an exception and freezes the graph

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7317]
## Dynamo version

1.2

## Operating system

Win 10

## What did you do? 

Declared a variable in an anonymous Imperative block but didn't assign any value to it.

## What did you expect to see?

For it to throw an exception, or give some warning that anonymous functions can't take external inputs.
OR
For the block to treat internal variables as new inputs then execute

## What did you see instead?

The entire graph will freeze. Nothing executes, whether in the Imperative block or other nodes on the graph. Only once the unassigned variable has an object assigned to it, does the graph start working again. The main issue is, no exception is thrown, when really it should (just like the new `@-#` and replications guides do) and this needs to be made more robust (imagine this on a big graph; everything would stop working and for the uninitiated user, it would be like trying to find a needle in a haystack!):

![image](https://cloud.githubusercontent.com/assets/18601851/19925417/c8c840b8-a0e7-11e6-8fac-d5f3ee5df4eb.png)

![image](https://cloud.githubusercontent.com/assets/18601851/19925430/d570874e-a0e7-11e6-9158-8ad727993fd7.png)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
