### ISSUE TITLE
Known issue with the background 3D preview for Intel+AMD/Nvidia setup

### ISSUE THREAD

**Issue by geoicons** [DynamoDS/Dynamo#7410]
## Dynamo version

Dynamo Studio 1.2.0.2690

## Operating system

Windows 7 Enterprise 64 Bit (6.1) running on HP Elitebook 840

## What did you do? What did you expect to see? What did you see instead?

There is a known issue with the background 3D preview not being available to people who have both integrated and external graphics cards. A work-around presented in the following FAQ. https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

However some users who work in a restricted enterprise environment are unable to change advanced profile settings relating to the graphics cards, nor able to (after installation) apply fixes to the registry keys. 

**_Please keep this card open until an effective software solution is developed and issued as a patch._**

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
