### ISSUE TITLE
Losing panel points with DeconstructSurface / DeconstructPolycurve 

### ISSUE THREAD

**Issue by cjm771** [DynamoDS/Dynamo#7437]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

1.2 
## Operating system

(e.g. Windows 7, Windows 8.1, etc)

Windows 7
## What did you do? 

I have a tool to extract curtian panel points. I get boundary curves and then deconstruct polycurve to get the points. when doing this on quite a number of curtian panels (516), out of the deconstruct polycurve comes out 514 panels (as points) . so two just vanish. same thing with deconstruct polysurface. I have worked around this by using the face vertices command.

**Comment by mjkkirschner** [comment]
will need the geometry - (rvt and dynamo file) guess this is failure for a specific geometry type - were there 516 polycurves - or did element.Geometry fail to extract those boundary curves?

**Comment by cjm771** [comment]
hmm Im wondering if I should remove this, turns out deconstruct polycurve is lunchbox specific. But to answer your question @mjkkirschner, all boundaries are extracted. this specific node for whatever reason fails on two of them, and even more so, flattens the list, completeley removing the original structure that it came in as.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
