### ISSUE TITLE
BUG WITH Surface.PointAtParameter

### ISSUE THREAD

**Issue by dingzhihua** [DynamoDS/Dynamo#7448]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.2.0
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
win10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
set points on a surface with parameter
(Fill in here)

## What did you expect to see?
points shown as cross product
(Fill in here)

## What did you see instead?
points shown the same as shortest no matter which lacing selected
(Fill in here)

**Comment by riteshchandawar** [comment]
@dingzhihua Will it be possible for you to share a picture of your graph? What do you mean by "p[oints shown as a cross product" in your comment on expected result?

- Ritesh

**Comment by dingzhihua** [comment]
Hi, nice to meet you.

Of course. Look at the following pictures. I use the cross product to get the result, it should be 110 points, but I only got 10 points. And no matter I change the selection to the longest and the shortest, the result is not affected at all.

I don't know whether it's affected by chinesization.

The attached is the program, maybe it's useful I think.



 

 

发件人: riteshchandawar [mailto:notifications@github.com] 
发送时间: 2017年1月16日 15:23
收件人: DynamoDS/Dynamo
抄送: dingzhihua; Mention
主题: Re: [DynamoDS/Dynamo] BUG WITH Surface.PointAtParameter (#7448)

 

@dingzhihua <https://github.com/dingzhihua>  Will it be possible for you to share a picture of your graph? What do you mean by "p[oints shown as a cross product" in your comment on expected result?

*	Ritesh

**Comment by riteshchandawar** [comment]
Somehow I am not able to see the pictures you are attaching to the post, can you please email me those to ritesh.chandawar@autodesk.com

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
