### ISSUE TITLE
.dll Xaml User Interface Node causing conflict with Dynamo

### ISSUE THREAD

**Issue by dannysbentley** [DynamoDS/Dynamo#7487]
## Not finding AppData/Roming/Dynamo
The Dynamo package after I published online I downloaded it on a virtual machine to test.   My nodes didn't find the correct .dll file and are still pointing to the folder where I developed it on my computer. 
 
![blob](https://cloud.githubusercontent.com/assets/6655476/21436093/acfe758e-c831-11e6-9039-3b22ae606437.png)

## Graphics problem on other machines. 
I then tried testing it on a couple other people's machine in my office and some of them had the graphic dump when they opened Dynamo.

![error](https://cloud.githubusercontent.com/assets/6655476/21436122/cbf6f0f6-c831-11e6-9d8c-6d64aaf923a8.png)

## What I should see. 
I'm using xaml WPF to create a Dynamo user interface.  The package which I'm using is to style is MahApps.  The displays should look like this and they work on my computer when I use my Dynamo nodes.

![slapsui](https://cloud.githubusercontent.com/assets/6655476/21436181/1600ab7e-c832-11e6-861a-2825c8bdb4ac.png)

## Source code
Here is my github 
https://github.com/dannysbentley/SlapUI

**Comment by mjkkirschner** [comment]
@kronz I'm pretty sure this is a bug... kinda... bug and feature!?  My guess is the zero touch assembly was loaded via the import .dll option, then @dannysbentley made some custom nodes using his imported library. The custom node has serialized the relative path to his library and is trying to resolve it from that location...

This is not usually an issue for two reasons:
* usually if someone is writing a zero touch library they can simply write another zero touch node which calls those functions instead of writing a custom node, that is what I would suggest as the workaround here.
* If the node is imported from a package instead of via the library import the serialized relative path should be correct. If it's an absolute path it will still be wrong...

**Comment by kronz** [comment]
@mjkkirschner so is this a problem that should be solved by better documentation or by changing the behavior of the application?

**Comment by dannysbentley** [comment]
@mjkkirschner, thank you for taking the time to look at this.  I'm importing a package via library import in Dynamo.  I'm unsure what extra steps I would need to ensure that my node is serialized with a relative path and not hard path.

**Comment by dannysbentley** [comment]
@kronz @mjkkirschner,  Hi, I have had another node only finding the relative path.  Some users have posted this issue with my Etabs formatting node.  

![missing path](https://cloud.githubusercontent.com/assets/6655476/22601186/a14bc588-e9f2-11e6-9ebc-d3fcfdeb11cc.jpg)

Here is our conversation on the dynamobim form: 
https://forum.dynamobim.com/t/etabs-to-revit-node/6467/5

**Comment by mjkkirschner** [comment]
Have you tried as a workaround not creating custom nodes like this? and instead creating other zero touch nodes that use your zero touch functions?

Another potential workaround is to edit the .dyf xml and get rid of the <hintPath> string inside the .dyf files.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
