### ISSUE TITLE
The tutorials are outdated files for Version 1.2 and will not open

### ISSUE THREAD

**Issue by Bumi2ush** [DynamoDS/Dynamo#7498]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
 1.2

## Operating system -
 Windows 7

## What did you do? 
Try to load a tutorial

(Fill in here) 
Getting started with Dynamo

## What did you expect to see? 
The tutorial

## What did you see instead?
The tutorial is outdated.

**Comment by riteshchandawar** [comment]
@Bumi2ush Do you mean sample file which we deliver with Dynamo?

- Ritesh

**Comment by Bumi2ush** [comment]
Yes.

With the update I cannot load all the Dynamo lessons from this link 
http://dynamobim.org/learn/#161.
When I try to load the Getting Started file I get this message - 




We have another issue with this version which has deleted the path/node 
for ListWorksetsNames which has caused much of our previous work to stop 
functioning at the List.Transpose node which means we may have to go 
rewrite and entire project. We are trying to find a work around.
 
Walter Kirkpatrick l FLUOR l Principal Architect | NCARB | LEED BD+C l 
864.517.1671 l IODC 8 20 1671| 100 Fluor Daniel Dr. l Greenville, SC 29607

**Comment by riteshchandawar** [comment]
Hello @Bumi2ush,

We need to update those Sample files at our end so that those can be open on new versions of Dynamo, and you are getting that message because we have stopped support of 0.7 file version of Dynamo since our last release 1.1.0

The workaround for the above issue is, open those files in 0.9.2 version of Dynamo and save them with that version, then you should be able to open all those files on 1.2 and later versions.

I hope that will help you to get proceed with your learning of Dynamo.

I will make to fix the issue of those Sample files at our end.

BTW, you talked about your another problem with "ListWorksetsNames", can you please elaborate more on that and if possible send me the file to reproduce that issue at my end.

Thanks,
Ritesh
