### ISSUE TITLE
If a polycurve gets split by same points as it was created with it skips a few

### ISSUE THREAD

**Issue by GielvanLanen** [DynamoDS/Dynamo#7669]
## Dynamo version
1.2.1

## Operating system
Windows 7

## What did you do? 
Tried to split a polycurve by the same points as it was created with. It skips a few when i tried to split it. 

## What did you expect to see?
The polycurve being split in 10 lines (if 11 points used).

## What did you see instead?
It splitted in 9 different line in stead of 10 because it skipped one random point.

![vraag dynamo forum](https://cloud.githubusercontent.com/assets/26225756/23614225/84449dc2-0282-11e7-994c-e4b8423ba4e0.PNG)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by aparajit-pratap** [comment]
Fixed in polycurve feature branch, will be available in Dynamo 2.16+.
