### ISSUE TITLE
List@Level functionality not available for custom node inputs in migrated graphs

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#7737]
## Dynamo version

1.2.3.592

## Operating system

Win 7

## What did you do? 

Opened a graph that was created in Dynamo 1.0.0.1180

## What did you expect to see?

All custom nodes to have list@level functionality available

## What did you see instead?

![nolistatlevel](https://cloud.githubusercontent.com/assets/3014437/24387723/10cff4d0-1377-11e7-992e-bfcc6ec3a0be.PNG)
- Inputs of existing custom nodes are **not** converted (left node)
- Only inputs of newly placed nodes custom work fine (right node)
- Inputs of existing OOTB nodes also work fine

This behaviour is caused by the fact that that the lacing of the existing custom nodes seems to be set to ```Disabled``` on conversion to 1.2.3
Please fix this this ASAP. In fact, I think this should not happen in 1.3 ....
CC @kronz

**Comment by riteshchandawar** [comment]
@andydandy74 I have created the file in 1.0.0.1180 with few Custom nodes from Lunch Box package, and I opened that in 1.2.3.592, I am getting list@level functionality on those old custom node after migration.
Here is the graph 
![image](https://cloud.githubusercontent.com/assets/5109531/24490189/1a191d80-1554-11e7-8c69-dbc35c9edd03.png)

I have also tested opening 1.0.0.1180 file in 1.3.0.875 (internal build), and it is working properly with list@level.

Is it possible for you to share you DYN which you had created in 1.0.0.1180? Also, let me know which package you are working with?

Thanks,
Ritesh

**Comment by andydandy74** [comment]
@riteshchandawar - I tried it on a couple of the Clockwork for Dynamo 1.x sample files.
The one I used for the screenshot is this one:
https://github.com/andydandy74/ClockworkForDynamo/blob/master/package_samples/1.x/dynamo/Core.Time.dyn
I can consistently reproduce the phenomenon on multiple machines, btw.
Under which circumstances would a custom node's Lacing be disabled? Maybe that is the key to finding the cuase here.

**Comment by riteshchandawar** [comment]
@andydandy74 I am able to reproduce the issue with your file, let me do more investigation what is the special about those nodes.

I will get back to you tomorrow.

Thanks,
Ritesh

**Comment by riteshchandawar** [comment]
Hello @andydandy74 I have downloaded the file from the location you suggested but I think the format is not the one which I get when I will create the file with same nodes. 

Is it possible for you to email me the file which is on your machine?

Thanks,
Ritesh

**Comment by andydandy74** [comment]
@riteshchandawar  - I uploaded the file here - just rename extension to *.dyn ...
[Core.Time.txt](https://github.com/DynamoDS/Dynamo/files/884338/Core.Time.txt)

**Comment by riteshchandawar** [comment]
@andydandy74 Sorry for the late reply on this, this is happening because the lacing of the custom node is disabled, one possible cause of that would be the custom node was too old. (which means when we were not having support for Lacing on Custom node, look at this PR which enables custom node lacing  #3233). 

I have manually changed Lacing to **Shortest** in your file and then opened in 1.3.0, and the problem got fixed.

![image](https://cloud.githubusercontent.com/assets/5109531/25321275/c6bc9780-28df-11e7-8582-14e9a86271a1.png)

We will find out a way how to fix this in next release.

**Comment by andydandy74** [comment]
If anyone else runs into this issue, here's a graph that will find all custom nodes with disabled lacing in all the graphs within a given directory: https://raw.githubusercontent.com/andydandy74/ClockworkForDynamo/master/maintenance/FindNodesWithDisabledLacing.dyn

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
