### ISSUE TITLE
CubicMillimeter - CubicMeter-UnitConversion WRONG By 10 times

### ISSUE THREAD

**Issue by torkuen** [DynamoDS/Dynamo#7741]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 1.2.1.3083

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows7

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Unit conversion between Cubic Millimeter and Cubic Meter

## What did you expect to see?

1E9 Cubic Millitmeter are converted to 1 Cubic Meter
![cubicmillimetercubicmeter-unitconversion](https://cloud.githubusercontent.com/assets/7558042/24508922/40f10470-1565-11e7-9b2b-b31709a958bd.JPG)

## What did you see instead?
****
1E9 Cubic Millimeter are converted to 10 Cubic Meter

**Comment by ikeough** [comment]
@ikeough

**Comment by dimven** [comment]
bump, this is still broken in 1.32 and will most likely remain broken in 2.0, since there haven't been any changes to the units class: https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/DynamoUnits/Units.cs

not sure exactly why this is failing. The internal value is 1E9:
https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/DynamoUnits/Units.cs#L1135

**Comment by jnealb** [comment]
@torkuen Thank you. This is tracked with QNTM-1304.

**Comment by jnealb** [comment]
@torkuen This is fixed in the latest daily builds.
