### ISSUE TITLE
Curve.PointsAtChordLengthFromPoint not working in Revit 2016

### ISSUE THREAD

**Issue by dmac76** [DynamoDS/Dynamo#7758]
Node: Curve.PointsAtChordLengthFromPoint works fine in Revit 2017.1 - returns results as expected.
but when running same graph in Revit 2016 - it returns only single point, lacing has no affect still single point displayed

## Windows Version:

Windows 7 Enterprise SP1

## What did you do? 

Ran same script in both Revit 2017.1 and 2016

## What did you expect to see?

Revit 2017.1 saw results as expected (no lacing) - Multiple points at chord lengths on curve
Revit 2016 expected same as in 2017.1 Revit

## What did you see instead?

Revit 2016 failed to return multiple point along curve

![Uploading Image.jpg…]()

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
