### ISSUE TITLE
WISH: UDP sender

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#777]
Hi, is UDP sender in dynamo? I found only listener, it would be great to have 2 way connection. Thanks

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
