### ISSUE TITLE
Scaling Untrims Surfaces

### ISSUE THREAD

**Issue by AskBid** [DynamoDS/Dynamo#7838]
## Dynamo version
1.2.2.373 - Dynamo Studio

## Operating system

Windows 7, AMD FirePro W5100, Precision T5810, Intel Xeon 3.50GHz

## What did you do? 

I created paneling surfaces with a LunchBox node (Panel.PanelTriangleC).
This Nodes creates many triangular faces which are nothing but planar surfaces trimmed to a triangle face.
I then scaled each triangle face with Geometry.Scale

## What did you expect to see?

I expected to see traingular faces scaled.

## What did you see instead?

The triangular faces did scale, but also turned into planar faces.
It seems that during scaling the triangular faces have been untrimmed going back to their original shape.
![untrimbug](https://cloud.githubusercontent.com/assets/28275923/25596940/e517d176-2e99-11e7-919b-1266be15b8f0.jpg)

**Comment by aparajit-pratap** [comment]
@AskBid I think you're using the `Geometry.Scale` node with individual scale inputs in each direction. You're right there is a bug with the node. For the time being you could try using the `Geometry.Scale` node with single scale factor input if that serves your purpose.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
