### ISSUE TITLE
List.MinimumItem converts Integer to Double

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7851]
## Dynamo version
1.3.0.875

## Operating system
Windows 10

## What did you do? 
Got the minimum values from a list(with two sub lists) of integers
Then tried to determine the index of these values in the the original list

## What did you expect to see?
The indices

## What did you see instead?
-1/Empty List

![20170505-1](https://cloud.githubusercontent.com/assets/5621624/25749056/ce706116-31ca-11e7-83b5-8d47a62d496f.png)

**Comment by alfarok** [comment]
@vykrum I think the issue is that `List.AllIndicesOf` doesn't actually take a list but rather an array of arbitrary ranks so replication does not work.  You should be able to change the lacing or use list at level to get the expected results. @Racel

![image](https://user-images.githubusercontent.com/13341935/32513211-856ef24a-c3c7-11e7-92cd-8811558f3589.png)

Example 1 = List at Level
Example 2 = Lacing - Longest
Example 3 = Lacing - Shortest

**Comment by Racel** [comment]
@vykrum @alfarok - Please note, this is why "Auto" lacing was added in 2.0. With the introduction of list@level in 1.x, you weren't able to technically apply shortest lacing to a node (which enables replication).  @alfarok's images appear to be from 2.0.

**Comment by alfarok** [comment]
@vykrum Yes, I should have mentioned that I was using 2.0 and the second example is using cross product lacing.  Thanks @Racel

**Comment by vykrum** [comment]
@alfarok  Your examples would have behaved differently in 1.3...
![minitem2](https://user-images.githubusercontent.com/5621624/32527897-2aaadfa6-c456-11e7-936e-e5ab5c32eb18.png)

However, Lacing is irrelevant here as the issue wasn't about `List.AllIndicesOf`, it was `List.MinimumItem` converting _integer_ to _double_
However, that seems to have been sorted out in 2.0
![minitem](https://user-images.githubusercontent.com/5621624/32527644-1f837896-c455-11e7-9774-17bcf458d951.png)

**Comment by alfarok** [comment]
@vykrum Sorry for the confusion! I was looking at 2.0 Release issues previously, but it does indeed appear the conversion has been corrected.
