### ISSUE TITLE
math.round looks like a bug

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7858]
https://forum.dynamobim.com/t/problem-with-math-round/8256/2

**Comment by mjkkirschner** [comment]
Expected behavior, maybe not!
but I'm not sure about a bug, it's using system.Math Round(double)
https://msdn.microsoft.com/en-us/library/wyk4d9cy(v=vs.110).aspx

checkout this interesting note:
`The integer nearest a. If the fractional component of a is halfway between two integers, one of which is even and the other odd, then the even number is returned. Note that this method returns a Double instead of an integral type.`

**Comment by mjkkirschner** [comment]
hmm, the example shown on that page actually describes the issue with midpoints... thanks for reporting, perhaps we can't use this method.

**Comment by mjkkirschner** [comment]
we can use https://msdn.microsoft.com/en-us/library/ef48waz8(v=vs.110).aspx I think.

**Comment by ksobon** [comment]
I didn't know that was expected behavior. I always thought that `round()` would round up for anything from *.5, and down for anything less than that. This is interesting, but kind of makes me want to reconsider use of that method.

**Comment by jnealb** [comment]
@mjkkirschner @ksobon This is tracked with DYN-849.

**Comment by QilongTang** [comment]
More details and description in https://forum.dynamobim.com/t/problem-with-math-round/8256/2. Closing
