### ISSUE TITLE
Curve offset direction is inconsistent

### ISSUE THREAD

**Issue by kronz** [DynamoDS/Dynamo#7876]
The offset direction of curves (lines in particular) is not consistent with the curve's normal. Instead offsets appear to respond to their orientation relative to the world coordinate system - this is confusing and unpredictable.

This is related to this request 6585 -
but I would propose that rather than (or in addition to) a manually specified offset side, the default behavior of the function should be consistent relative to the curve direction.

Original report from @AndrewHeumann
https://github.com/DynamoDS/DynamoRevit/issues/1661#issuecomment-300672003
tracked internally: https://jira.autodesk.com/browse/DYN-826

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by aparajit-pratap** [comment]
Fixed in Dynamo 2.10. Removing `didnotfix` label.
