### ISSUE TITLE
Length of conditional return in function curtailed

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7914]
## Dynamo version
1.3.0.875

## Operating system
Windows 7

## What did you do? 
Defined a function which is expected to return a different list based on the value of an independent/unrelated input
![20170531-1](https://cloud.githubusercontent.com/assets/5621624/26634291/c90765a8-4633-11e7-99cc-95e9050636c4.png)

## What did you expect to see?
Don't understand the output as there isn't any comparison between items in the concerned lists.
The expected length of the list for different values isn't the same.

## What did you see instead?
The items in the longer list whose indices lie beyond that of the length of the shorter list are eliminated.
Hope this isn't expected behavior.

**Comment by andydandy74** [comment]
See #6491

**Comment by vykrum** [comment]
Thanks @andydandy74 
Would need to use an Imperative code block then. 

![20170531-2](https://cloud.githubusercontent.com/assets/5621624/26642641/2076a5b6-464c-11e7-92c5-33193a3fef7d.png)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
