### ISSUE TITLE
Frozen Freeze

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7965]
## Dynamo version
1.3.0.875

## Operating system
Windows 7, Windows 10

## What did you do? 
Tried to unfreeze a codeblock

## What did you expect to see?
Ability to uncheck the Freeze option

## What did you see instead?
The status of Freeze cannot be altered
![unfreeze](https://user-images.githubusercontent.com/5621624/27144795-da256d62-5150-11e7-907f-b0ff0a05b453.png)

**Comment by ramramps** [comment]
can you go the XML and unfreeze the node?  I think this is a circular dependency....

**Comment by vykrum** [comment]
@ramramps 
> can you go the XML and unfreeze the node?
Wouldn't know how to do that  :-)

I just copied the code to a fresh code block. Was very inconvenient.

**Comment by mjkkirschner** [comment]
I'm not sure what the fix is here besides disallowing circular dependencies - the algorithm for frozen state calculation depends on the graph having no cycles AFAIK.

**Comment by ramramps** [comment]
@Racel do we need to cover this for 2.0? I remember from the initial discussion that freeze will not work for graphs with cycles (circular dep).

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
