### ISSUE TITLE
Add "Append" Input to WriteText node

### ISSUE THREAD

**Issue by DavePlumb** [DynamoDS/Dynamo#7977]
Could we get an additional Input for the Core WriteText node that would allow us to Append to a file in addition to overwriting the file?
I envision this as a simple Boolean after the filePath and text Inputs:
   filePath: string
   text: string
   **append: boolean**
Inside the node, it would simply use the "a" parameter at the file open instead of the "w" option.
default if it the input isn't wired would be false so any existing graphs would still work as is without any changes

Yes, I know this could be done in Python, but rather than have a custom node that almost duplicate a Core node it seems like this would be a simple addition to the existing Core node. 
(I hate it when people say that)
Further discussion on the DynamoBIM forum here:
https://forum.dynamobim.com/t/wish-add-append-option-to-writetext-node/12489

**Comment by radumg** [comment]
Hi Dave,

I've submitted a PR to introduce a node that can `AppendText`. 

You'll notice I opted for adding a node instead of providing that switch to mitigate against inexperienced users not knowing what that does and potentially overwriting files.
I believe this is much clearer, but doesn't overload core library with too many nodes, let's see what Dynamo team thinks.

Radu
