### ISSUE TITLE
Session Log Missing Information

### ISSUE THREAD

**Issue by kronz** [DynamoDS/Dynamo#7985]
Originally filed by @paoloemilioserra 
https://github.com/DynamoDS/DynamoRevit/issues/1715
## Dynamo version

1.3.0.875

## Revit version

2017.2
## Operating system

W7

## What did you do? 

I monitored the Log file in a Dynamo session, loading DYN files from the hard drive both in automatic and manual mode. 

## What did you expect to see?

 "Original file " with the name of the graph for each file. A way to calculate the exact duration of the execution (not just the file opened in the Dynamo Application).

## What did you see instead?

The same file called "corridor.dyn" has been opened in multiple occasions but the log trace was different from the one called "readCSV.dyn"

![image](https://user-images.githubusercontent.com/14221455/27251858-8795eda4-5350-11e7-88a7-fe2d267fdcf1.png)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
