### ISSUE TITLE
Uniform Scale | API_Failed

### ISSUE THREAD

**Issue by crwinchester** [DynamoDS/Dynamo#8005]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 1.3

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 7

(e.g. Windows 7, Windows 8.1, etc)

## Applying uniform scale factor to list of cuboid geometry in Dynamo Sandbox.

(Fill in here)

## Expected cuboids to scale uniformly about their local origins per the input.

(Fill in here)

## Geometry.Scale node reported API_Failure and cuboids scaled incorrectly relative to their local origins (i.e. origin points appear to have scaled as well when they should not be).
![dynamo api_failure](https://user-images.githubusercontent.com/29491492/27501541-e779fda6-5822-11e7-8fd8-ec4870574f5d.PNG)

(Fill in here)

**Comment by jnealb** [comment]
@aparajit-pratap Is this filed in JIRA?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
