### ISSUE TITLE
Build 0.6.2.14024: error message not really helpful

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#806]
the new message when something goes wrong is "....see console for details". and the result is for coders only. before it was more for "Dynamers". container and lists etc... 

not really an improvement IMHO....

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
