### ISSUE TITLE
Improvement: ToRevitType() limitation with converting Degree-1 NurbsCurves

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8087]
## Dynamo version

1.3.1

## Operating system

Win 10

## Improvement Suggestion

I notice that the ToRevitType() method doesn't handle Degree 1 nurbs curves. I'm currently using the workaround shown below, however, I think it is better if the ToRevitType() did this automatically:

![image](https://user-images.githubusercontent.com/18601851/29004767-4801056a-7ac5-11e7-95ac-4129edbefed4.png)

Workaround:
```
def CurveConversion(tLine):
	if type(tLine) == NurbsCurve and tLine.Degree == 1:
		crv = Line.CreateBound(tLine.StartPoint.ToXyz(), tLine.EndPoint.ToXyz())

	else:
		crv = tLine.ToRevitType()
	
	return crv

```

**Comment by dimven** [comment]
There might be cases where the nurbs curve has multiple control points. In those cases, it might be a better idea to extract the points and either create a line for each pair or create a PolyCurve and use its ToRevitType method. That would however result in a curve loop.

Also it might be a good idea to mode this issue to DynamoRevit, since it's dealing with Revit matters.

**Comment by ThomasMahon** [comment]
Good point, I was only considering nurbs created using Revit tools which I think only allows one type of D1 nurbs to be created, and it only has two points. I overlooked the Dynamo approach!

I normally post these in the correct github, so I'll close this one and repost on the Revit Dynamo github
