### ISSUE TITLE
Split Closed Curve

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8150]
## Dynamo version
1.3.1

## Operating system
Windows 7

## What did you do? 
Split a closed curve using _Curve.SplitByParameter_ (parameters)
The list of parameters did not include 0/1

## What did you expect to see?
Expected the curve t be split into as many divisions as the specified parameters

## What did you see instead?
An addition curve is obtained as the curve is split at parameter 0/1
![sp1](https://user-images.githubusercontent.com/5621624/30012947-0b6bea0e-9161-11e7-94bf-9d5b527bda2f.png)

**Comment by jnealb** [comment]
@aparajit-pratap Is this as designed?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
