### ISSUE TITLE
Mesh.FaceIndices fails when first input item is empty list

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8190]
## Dynamo version

1.3.1 stable

## Operating system

Windows 7

## What did you do? 

Fed a filtered list of geometry into the ```Mesh.FaceIndices``` node

## What did you expect to see?

The node working correctly

## What did you see instead?

The node returning ```null``` and the following error:
```
Warning: Internal error, please report: Dereferencing a non-pointer.
```
![grafik](https://user-images.githubusercontent.com/3014437/30589077-4fd01efc-9d39-11e7-88c5-4db6a0818a50.png)

This only happens when the first element of the list is an ```Empty List```. If the first element is a mesh I get the expected result:
![grafik](https://user-images.githubusercontent.com/3014437/30589008-39a8bdbe-9d39-11e7-9dd9-7496537aa443.png)

**Comment by dimven** [comment]
This has been an ongoing issue since the introduction of DS. Whenever the first item in the list is an empty list or a null, the DS interpreter fails. I've reported on this once in https://github.com/DynamoDS/Dynamo/issues/5238 .

https://github.com/DynamoDS/Dynamo/issues/7153 is also somewhat related because it fails in a similar manner and for similar reasons. 

@ke-yu  did a PR that was supposed to mitigate this but I still see this issue occurring regularly. I know that treating empty lists will be a lot more challenging than treating nulls, because a new list will automatically initiate replication techniques. Maybe when evaluating the input, the interpreter should ignore and pass empty lists and nulls at the head of the list till a "true" object instance is reached.

**Comment by ikeough** [comment]
Thanks @dimven @andydandy74. I'm closing this in favor of #5238.
