### ISSUE TITLE
AppDomain issue with Xceed.Wpf.Toolkit.dll

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#8269]
So this is a little bit weird. It has to do with the Revit's AppDomain. It's been a while since I ran into this issue, but recently I have been working on a little Dynamo WPF node and I used a control from Xceed.Wpf.Toolkit. It's all hunky dory, I can debug the project, and it all works fine. Then I decide to publish my package, and drop the Xceed.Wpf.Toolkit.dll into Dynamo's package folder, only to find out that it's clashing with something that is already loaded into Revit. I went looking and it seems that Revit itself, and out of the box has this toolkit loaded into the AppDomain, hence the clashes. It's a little weird, because they have been using it as far back as 2016 and it basically means that I cannot load it into my package. Latest version of that dll is 3.2.0 while Revit rolls in with 5 year old 2.0.0. Luckily for me the control that I was using is still there, but this just reinforces the dynamo/revit appdomain issues etc. I am not sure there is a fix to that though unless we want to manage our own app domain for Dynamo only, and then route all appropriate calls through that....what do you think Mike cc: @mjkkirschner

**Comment by mjkkirschner** [comment]
we now also have a dependency on xceed for the color palette node which is in the core library. The creation of an appDomain for Dynamo seems like a very large change. We are continuing to find issues with dll conflicts with other addins, packages etc, so we're going to start an investigation here soon, will try to followup on possible solutions we find.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by sonomirco** [comment]
Hi @ksobon, @Amoursol and @johnpierson 
We created a node that uses a combo box with multiple selectors; we used the solution developed in Archilab, which relies on `Xceed.Wpf.Toolkit.dll`, now causing this dependency error to some users.
![image](https://github.com/DynamoDS/Dynamo/assets/57708659/008af309-4aba-4735-945b-78a3f6f1aad0)

I saw Archilab is referencing Xceed.Wpf.Toolkit.dll version 3.0 which is not available as a [nuget](https://www.nuget.org/packages/Extended.Wpf.Toolkit/4.5.0#versions-body-tab) and from their [GitHub](https://github.com/xceedsoftware/wpftoolkit/tags)

What is the current version used in Revit?
Thanks for the help!

**Comment by johnpierson** [comment]
You're going to want to directly reference whatever is being used in the Dynamo for Revit version you are using.
Eg.
"C:\Program Files\Autodesk\Revit 2024\AddIns\DynamoForRevit\nodes\Xceed.Wpf.Toolkit.dll"

Also, it would be better to abandon that toolkit altogether because you are 100% going to have issues for the remained of your development cycle.

**Comment by mjkkirschner** [comment]
Also be careful - the license has changed in newer versions.

**Comment by sonomirco** [comment]
Thanks, @johnpierson and @mjkkirschner, for your comments.
I will move and use another framework, probably https://mahapps.com
