### ISSUE TITLE
Dynamo Align Selection

### ISSUE THREAD

**Issue by Rfahren** [DynamoDS/Dynamo#8454]
## Dynamo version
Dynamo Studio 1.3.0.946

## Operating system
Windows 10

## What did you do? 

Right click-->Align Selection

## What did you expect to see?

Align Selection on right side and to be able to select an option.

## What did you see instead?

menu opens on left side and will 9 times out of 10 disappear when you move to make a selection.

![dynamo issue](https://user-images.githubusercontent.com/33635461/34832212-247d385a-f6e1-11e7-9108-e0cbf66d63f3.png)

**Comment by ColinDayOrg** [comment]
This issue has been previously seen in some circumstances. It is not currently clear what specifically is causing the issue, as the appearance of the issue seems to vary from system to system. 

As a workaround for this issue you can right-click to bring up the menu on the left side of the (3D display area) screen so that the sub-menu comes up on the right side of the main right-click menu. With the sub-menu on the right side of the main menu you should be able to select an alignment option without the sub-menu disappearing.
