### ISSUE TITLE
documentation needed on new library organization schema

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#8466]
Since we are switching to JSON based file type, we need clear guidelines on how the libraries are going to be organized. It appears to me that the old ZT namespace>class>method is still in, but also they are not applied the same way for custom node model packages. Take the old UI++ package that had the datetime picker and color picker. To make finding these nodes easier, we just slipped them right into the Core section of the OOTB library. It appears to me that this no longer works for that package as its being slotted with the Add-ons (and rightfully so). I would really appreciate documentation for how we customize this for 2.0 for both ZT and NodeModels. Is there a way to slide our packages into OOTB sections? All that stuff would be good to know before 2.0 comes out so we can prep. 

![image](https://user-images.githubusercontent.com/529781/34909154-ba4e09a2-f869-11e7-9a6c-129e37250e5d.png)

@kronz @mjkkirschner @Racel 

## Dynamo version

2.0.0

## Operating system

Win10

**Comment by mjkkirschner** [comment]
some of this info can be found on the librarieJS repo in the docs folder - but I'm afraid they are a bit out of date -still worth checking out though.
https://github.com/DynamoDS/librarie.js/tree/master/docs

**Comment by andydandy74** [comment]
@mjkkirschner - Didn't find any info there on how to set up customization XML files. My (packaged) ZT nodes now end up in the Miscellaneous section - I would expect to find them in the Add-Ons section instead.

**Comment by mjkkirschner** [comment]
@alfarok @Racel ☝️

**Comment by radumg** [comment]
+1 for this.

**Comment by mjkkirschner** [comment]
@andydandy74 can you help us repro the nodes being moved to the misc category - which package?

**Comment by andydandy74** [comment]
DynamoAutomation

**Comment by andydandy74** [comment]
@mjkkirschner Disregard that. I don't know what I was smoking when I wrote that.
The ZT package **does** appear in the Add-Ons section.
However, I noticed that mixing ZT and custom nodes in one package may have an undesired side effect:
![grafik](https://user-images.githubusercontent.com/3014437/35142835-e277df6c-fcff-11e7-8c04-c974fca16ef6.png)
Notice how there are two categories of the same name (one for ZT nodes, one for custom nodes of category "DynamoAutomation.Journal"?
I think this behaviour would affect a number of packages that include both ZT and custom nodes.

**Comment by alfarok** [comment]
@mjkkirschner @jnealb tracking with [QNTM-3306](https://jira.autodesk.com/browse/QNTM-3306)

**Comment by alfarok** [comment]
@ksobon @andydandy74 @mjkkirschner Hey guys, I am taking a look at the library organization for Add-ons now.  Konrad  the original issue you raised is because you can no longer add nodes to the OOTB categories so your view customization file is creating that same category you specified in the Add-ons section.  Andy the issue you are seeing is related to the naming of the Custom Nodes I believe.

![image](https://user-images.githubusercontent.com/13341935/36861247-610a3fd4-1d51-11e8-87e0-2b5e80b943ef.png)

`.`'s are being used as a delimiter to determine the hierarchy.  If you expand `Journal` or `JournalFiles` on the lower right in the 2.0 image you will see the names have been chopped down to `RevitStartupArguments` and `Cleanup`.  The naming before the `.` creates additional nested categories.

I will continue to test the behavior and provide some documentation based on my findings.

**Comment by alfarok** [comment]
Removing the dot-notation from the node names seems to resolve the issue.  The placement is then strictly based on the specified category.

```Json
{
  "Uuid": "85066088-1616-40b1-96e1-c33e685c6948",
  "IsCustomNode": true,
  "Category": "DynamoAutomation.Journal.Actions",
  "Description": "Moves all journal files created during a batch-processing operation to a specified directory",
  "Name": "Cleanup",
  "ElementResolver": {
    "ResolutionMap": {}
  },
```
![image](https://user-images.githubusercontent.com/13341935/36862468-e0ea51aa-1d54-11e8-8ba9-339eb922cbdc.png)

**Comment by alfarok** [comment]
@ksobon @andydandy74 @radumg I created a new Wiki page for [Library 2.0 Add-ons Organization](https://github.com/DynamoDS/Dynamo/wiki/Library-2.0-Add-ons-Organization).  Please feel free to let me know if additions or modifications are required.

**Comment by andydandy74** [comment]
@alfarok Perhaps the documentation for custom nodes should show more clearly which combination of node categorization and naming has which effect:
![grafik](https://user-images.githubusercontent.com/3014437/37177185-029f83ae-231f-11e8-9719-cfb60ad701f6.png)

**Comment by alfarok** [comment]
Hey @andydandy74, thanks for taking a look back at this.  I agree it can be confusing because the same results can now be achieved by various combinations of the `Category` and `Name`.  I would keep all the desired hierarchy logic in the `Category` and just the node name in the `Name` property (as shown in the second example above).  If the desire is to display more of the hierarchy on the node itself you can go with the top solution but we need to be clear in messaging that this dot-notion will create additional nesting which was not the 1.3 behavior.  Would you mind me adding the example above to the docs?

**Comment by andydandy74** [comment]
Sure, use it if you like. I think for migrating existing packages that already use dot notation in the node names (e.g. Clockwork) recategorization is the less painful approach. Otherwise it would be file renaming *and* changing the node name in the dyf.
