### ISSUE TITLE
Library collapsing after placing custom node

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8478]
## Dynamo version

2.0.0.3484

## Operating system

Windows 10

## What did you do? 

Placed a custom node from the library

## What did you expect to see?

The state of the library **not** changing

## What did you see instead?

The entire Add-Ons section collapsing

Note that this is only happening with custom nodes that haven't been touched in 2.0 yet. If a node or its properties dialog has already been opened, the library state does not change. 
(So I guess that means if there's a JSON-based DYF for a node in the backup folder the library works as expected.)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
