### ISSUE TITLE
Loadcase GetParameterValueByName not working.

### ISSUE THREAD

**Issue by NoOne2246** [DynamoDS/Dynamo#8484]
## Dynamo version

1.3.2.2480

## Operating system

Windows 7 Enterprise

## What did you do? 

Tried to retrieve the name of each loadcase.

## What did you expect to see?

The result of the Python Script

## What did you see instead?

The result in the string from object

Code in python:
```
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *


output = list()

for i in IN[0]:
	output.append(UnwrapElement(i).Name)

OUT = output
```

![image](https://user-images.githubusercontent.com/8730604/35258142-a30638f6-0051-11e8-93bf-fd89ca6f4c8a.png)

**Comment by dimven** [comment]
The example you've posted is not comparable. In the python script you're getting the instance object's "Name" property, where as in the graph you're reading a parameter.

There is a known issue with parameters, where a revit element can have multiple parameters with the same user visible name. That's because revit has three different parameter types - builtin, project internal and shared. The best way to check the element's parameters through the Revit Lookup.
