### ISSUE TITLE
[Query] - Can you not use Integers/Doubles as 'Keys' ?

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8497]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.0.0 Daily Build

## Operating system

Windows 10

## What did you do? 

Please refer to the attached image:

![dict_issue_04](https://user-images.githubusercontent.com/12857357/35457745-e3110cf0-02d1-11e8-9a2d-dbb251f4e1d3.png)

## What did you expect to see?

Doubles/Integers being allowed to be used as keys.

Because it works with string keys: 

![dict_issue_05](https://user-images.githubusercontent.com/12857357/35457794-0697f698-02d2-11e8-9722-758dfce64193.png)

**Comment by ramramps** [comment]
@aparajit-pratap @pboyer

**Comment by pboyer** [comment]
Hi @Amoursol,

Thank you very much for the query. It's very helpful to us.

At present, as you've discovered, we do not support non-string keys for `Dictionary`.

Importantly, saying we only support string keys today doesn't prevent us from extending it in the future. If we generalize now, however, we risk introducing "dark confusing corners" that we can never retract.

Here is our thinking. **Doing a dictionary lookup requires doing key equality comparisons. Thinking about string equality comparison is easy.** If they _look_ the same, they _are_ the same.

<img width="403" alt="screen shot 2018-01-29 at 12 10 24 pm" src="https://user-images.githubusercontent.com/916345/35523683-650a5ff0-04ed-11e8-9fb4-ea7f9e35a486.png">

<img width="380" alt="screen shot 2018-01-29 at 12 45 45 pm" src="https://user-images.githubusercontent.com/916345/35525389-57518dc0-04f2-11e8-9e63-cc4a93d333d9.png">

Equality of non-string types (other than integers) is _not easy_:

<img width="544" alt="screen shot 2018-01-29 at 12 57 45 pm" src="https://user-images.githubusercontent.com/916345/35525992-28e353fe-04f4-11e8-9452-34cc35c83fc5.png">

These _look_ exactly the same, but they are _not equal_. Huh? Understanding why these are not equal requires understanding reference equality and pointers. There are no training wheels in our system for this - you either understand why these are different or you don't.

Floating point number (e.g. `double`) equality is not easy. Historically, DesignScript attempts to hide this from you:

<img width="535" alt="screen shot 2018-01-29 at 12 22 40 pm" src="https://user-images.githubusercontent.com/916345/35524343-490c1170-04ef-11e8-8c19-bbbabfd70d40.png">

I look at these two code blocks and they show two _different_ numbers - why does it say they're equal? If I remove one zero, magically they are not equal:

<img width="414" alt="screen shot 2018-01-29 at 12 27 59 pm" src="https://user-images.githubusercontent.com/916345/35524545-e57ea1da-04ef-11e8-9265-9572aef65dc5.png">

We have purposely omitted this kind of "magic" (i.e. `a == b` actually means `abs(a-b) < tolerance`) from the `Dictionary` type because we wanted to remove any possibility of confusing corner cases.

**There's an escape hatch. You can easily make a string from any type.**:

<img width="376" alt="screen shot 2018-01-29 at 12 37 29 pm" src="https://user-images.githubusercontent.com/916345/35524988-2e430aa4-04f1-11e8-885b-2d86ab1afa03.png">

Then you can do: 

<img width="662" alt="screen shot 2018-01-29 at 12 33 20 pm" src="https://user-images.githubusercontent.com/916345/35524994-355b70ba-04f1-11e8-81c7-4719166e52e6.png">

This is a tiny bit more work, but in exchange, there is no magic, there is no dark corner. 

This isn't all set in stone. Maybe we'll extend it in the future (e.g. for `integer` keys). Maybe we'll add the ability to automatically convert the arguments to a string. For now, it's simple and somewhat limited but, in exchange, it's easy to reason about.

**Comment by Amoursol** [comment]
Hello @pboyer,

Thank you for the very detailed explanation, its appreciated. Fully understand and am on board with the reasoning. Strings are enough.

**Comment by kronz** [comment]
Also, you can do a similar end run around limitations like with Dimension over-rides like this
![2018-01-29_1409](https://user-images.githubusercontent.com/3456818/35531529-4616763e-0505-11e8-9c77-dbee7320621c.png)

Not recommended!
