### ISSUE TITLE
Point.Project effiency

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#8501]
[Point.Project.zip](https://github.com/DynamoDS/Dynamo/files/1673166/Point.Project.zip)
## Dynamo version

1.3.1

## Operating system

Win 7

## What did you do? 
Projected points to a complex(ish) PolySurface.
See thread here: https://forum.dynamobim.com/t/point-project-slowed-down-in-revit-2018/17514 

## What did you expect to see?

A more efficient projection of points.

## What did you see instead?

The original points themselves originate in a discretization of a curve. If I project the curve to the surface first and then project the points to that resulting curve it provides a significant effiency gain. From what I've experienced the Point.Project node also ran better with Revit 2017, but haven't been able to reproduce at the moment. I'll see if I can dig something up.

**Comment by dimven** [comment]
Some additional observations - extruding the polycurve and intersecting that with the topo PS produces near-instant results at the possible loss of some accuracy:
![image](https://user-images.githubusercontent.com/7148394/35545260-3660913a-05a9-11e8-8686-81aa7b96b762.png)

and intersecting lines with the topo PS produces times about half way between curve/point projections:
![image](https://user-images.githubusercontent.com/7148394/35545310-6dc1321a-05a9-11e8-84f0-d91992d1c122.png)

My personal favorite way of creating these types of intersections is by actually using the mesh toolkit which is usually both faster and just as accurate:
![image](https://user-images.githubusercontent.com/7148394/35545482-39e6a53c-05aa-11e8-8f41-75e68d50281e.png)

[test graph](https://github.com/DynamoDS/Dynamo/files/1676200/PointProject_additional.tests.zip)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team

**Comment by aparajit-pratap** [comment]
Performance is better in 2.15 after a fix. While the workflow reported took ~2min 45 sec, it now takes about ~33 sec.
