### ISSUE TITLE
Nested multiline comment error

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8543]
## Dynamo version
2.0.0.3934

## Operating system
Windows 10

## What did you do? 
Attempted to comment out lines that also included some lines that already were commented out

## What did you expect to see?
The selected lines to be commented out

## What did you see instead?
![error-20180207-1](https://user-images.githubusercontent.com/5621624/35925145-fbfc3a0a-0c4a-11e8-8534-9fe799fe6a56.png)

**Comment by pboyer** [comment]
Thanks for your comment @vykrum.

This is not bug. This is the expected behavior of this kind of comment syntax. It is the same behavior as C, C++, C#, JavaScript, Java and many other C descendants. 

We don't plan on changing this. It's good to be the same here as a programmer has no new syntax behavior to learn as she moves between DesignScript and other languages.
