### ISSUE TITLE
Surface.TrimWithEdgeLoops not working as expected

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#8600]
## Dynamo version

1.3.2 stable

## Operating system

Windows 7

## What did you do? 

Tried to cut holes in a planar surface with a list of planar loops

## What did you expect to see?

The outer boundary being preserved and new holes being added to the surface (holes at the darker squares):

![image](https://user-images.githubusercontent.com/7148394/36706893-eabc737a-1ba6-11e8-8cd9-3111150dda00.png)

## What did you see instead?

the holes got patched:

![image](https://user-images.githubusercontent.com/7148394/36706906-f8072c00-1ba6-11e8-9380-1a3bec3c9e90.png)

Previously I could circumvent this unexpected behavior by flipping the primary surface or by reversing the loops but that doesn't seem to be the case any more :(

Here's the code from the image:

```
s1 = Rectangle.ByWidthLength(50, 50).Patch();
n = -22..22..#12;
p1 = Point.ByCoordinates(n<1>, n<2>);
pl1 = Plane.ByOriginNormal(p1, Autodesk.Vector.ByCoordinates(0, 0, 1));
r2 = Flatten(Rectangle.ByWidthLength(pl1, 1, 1));
s2 = flip ? s1.FlipNormalDirection() : s1;
s2.TrimWithEdgeLoops(reverse ? r2.Reverse() : r2);

```
Changing the geometry range doesn't seem to have any effect either. The only way I can get the desired behavior is by using the Surface.SubtractFrom method instead. However generating all the intermediate solids and iterating with all of them or unioning them is a prohibitively expensive operation.

![image](https://user-images.githubusercontent.com/7148394/36707135-f6fcec04-1ba7-11e8-9eb8-5f8bfaa81e89.png)

**Comment by vykrum** [comment]
I've always handled this by including the perimeter curve within the list of loops. Still seems to work.
![trim](https://user-images.githubusercontent.com/5621624/36931482-5a6ffe8e-1edc-11e8-826a-ae2b12a9f9ca.png)

**Comment by dimven** [comment]
Good to know it's not broken, but that a very counter-intiutive workaround :)

**Comment by vykrum** [comment]
True, ideally, including the perimeter curves should produce the results we now obtain (without the perimeter curves) and vice versa.

Wasn't aware of the flip/reverse work around though :-)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
