### ISSUE TITLE
Surface.PerimeterCurves Not Returning the Perimeter Curves

### ISSUE THREAD

**Issue by MarkThorley** [DynamoDS/Dynamo#8637]
## Dynamo version
Dynamo Core 1.3.2.2480 | Dynamo Studio 1.3.0.881

## Operating system
Windows 10

## What did you do? 
Using Dynamo Studio, I am building a simple surface by lofting to parallel curves. I then want to extract the perimeter curves of the new surface.

## What did you expect to see?
I set of perimeter curves following the shape of the surface created.

## What did you see instead?
One single curve on the side of the surface.

![capture](https://user-images.githubusercontent.com/6421438/37205110-6b172dbc-238b-11e8-8a1f-7afa4b46217a.JPG)

**Comment by mjkkirschner** [comment]
@aparajit-pratap @pboyer thoughts?

**Comment by mjkkirschner** [comment]
Is this object exactly square?

**Comment by MarkThorley** [comment]
@mjkkirschner just following up on this. A similar issue with surface.perimetercurves when run on a polysurface that has been created by joining two surfaces together, returns the perimeter curves for each surface rather than only the perimeter curves of the new polysurface. 
![capture](https://user-images.githubusercontent.com/6421438/43457584-4380f6ac-94bf-11e8-97c6-a5e93bc54dc5.JPG)

**Comment by mjkkirschner** [comment]
@aparajit-pratap FYI

**Comment by Amoursol** [comment]
@mjkkirschner @aparajit-pratap Our workaround for the above issue is as follows:

![polycurve issue](https://user-images.githubusercontent.com/12857357/43518512-3ced395c-9584-11e8-856a-094d30473fdc.jpg)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
