### ISSUE TITLE
Disconnecting Ports in Custom Node

### ISSUE THREAD

**Issue by Voulz** [DynamoDS/Dynamo#8712]
Hi!

I am creating my own Custom Node with Custom UI in C# and I need to have a variable number of inputs and outputs. I am able to make that part works but I am unable to remove the connectors when I remove one port in my node; the connectors all move to the first port (that I keep).

I checked the source code and I saw that the class [VariableInputNode](https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Graph/Nodes/VariableInputNode.cs) does something similar (but not the way I need). Nevertheless, I saw that the class was calling [PortModel.DestroyConnectors](https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Graph/Nodes/PortModel.cs#L344) to remove the Connectors, calling itself [ConnectorModel.Delete()](https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Graph/Connectors/ConnectorModel.cs#L189) on each Connector.
Both of these methods [PortModel.DestroyConnectors](https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Graph/Nodes/PortModel.cs#L344) and [ConnectorModel.Delete()](https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Graph/Connectors/ConnectorModel.cs#L189) are `internal`, thus not allowing my Custom Node to call them.

I'd like to know first what is the reason why these 2 functions are `internal`, if they could be made `public` or what are the alternatives to disconnects the Ports.

Thanks!

### Dynamo version
Dynamo Core 1.3.2.2480

**Comment by ramramps** [comment]
can you send the file? did you check this method `RemoveInputFromModel` ?

**Comment by mjkkirschner** [comment]
seems like a good approach might be to create a new nodeModel type that inherits from `variableInputNode` - `variableInputOutputNodeModel`.

methods are internal when we do consider them external - usually they are just to facilitate some implementation of an API method.

**Comment by Vlok2018** [comment]
What about variableOutputNode?
A couple people have asked for this already but I don't think there is one currently while it is a very important feature to create efficient nodes.

**Comment by Voulz** [comment]
After double checking the code, I guess I could make a variable input works by using the `VariableInputNodeController`. I don't really like that class because it looks like it was made exclusively for Nodes that have a variable number of typical/similar inputs which is quite limiting.
The biggest problem for my case, as @Vlok2018 said, is that there is no `VariableOutputNode` or `VariableOutputNodeController` and my node need to have both variable inputs and outputs.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
