### ISSUE TITLE
Removing all ZT Node inputs using +/- input buttons and adding them back doesn't restore the declared input names

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8741]
## Dynamo version

1.3.2

## Operating system

Win 10

## What did you do? 

Removed all inputs from the String.Join node using the +/- UI node buttons. Added them back to the node using the + button

## What did you expect to see?

![image](https://user-images.githubusercontent.com/18601851/38564433-0b8a040e-3cd7-11e8-9f52-ba17aa1741d9.png)

## What did you see instead?
![image](https://user-images.githubusercontent.com/18601851/38564453-17d694f2-3cd7-11e8-9f3a-a186d21ffbae.png)

So the output is correct, but the name of the input is lost. I would expect the node to be developed such that the minus button deactivates once the last string input is remove (so only the 'separator' input remains).

cc @mjkkirschner

**Comment by jnealb** [comment]
@ThomasMahon Thanks for the report: this is tracked with QNTM-3968.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
