### ISSUE TITLE
Removing all ZT node inputs using +/- UI buttons causes graph to become unresponsive

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8742]
## Dynamo version

1.3.2

## Operating system

Win 10

## What did you do? 

Removed all inputs from a ZT node which implements the IU +/- buttons using the param input modifier. In my test-case I used the OOTB String.Join node and my own custom node

## What did you see instead?

The graph becomes unresponsive until at least one input is added back to the node

cc @mjkkirschner

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
