### ISSUE TITLE
Dynamo 2.0.0 Library scroll 

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#8780]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0 stable

## Operating system

Win 7

## What did you do? 

Search after OOTB-nodes and clicking the library link
![searchlib2](https://user-images.githubusercontent.com/7080648/39039701-48bcd0de-4486-11e8-8e5d-f4e5998b94aa.gif)
 

## What did you expect to see?

the library to scroll down to the correct place.

## What did you see instead?

The library scrolls down to the addon-packages. If I search for an addon node the library scrolls to the correct place.

Additionally the library sometimes default scrolls to the bottom of the library when deleting a search item. Default should be to the top?( see last section of gif)

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
