### ISSUE TITLE
Dynamo 2.0 keyboard inputs don't work at all

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#8785]
I know you guys mentioned that CTR+C might not be working but I can't get any keyboard input to work. That includes DELETE button, and with lack of substitutes for deleting (no context menu), that's a little difficult to work.

**Comment by QilongTang** [comment]
@ksobon Assuming you are working with Revit 2019 but not sandbox alone, this issue will be fixed by itself once user has upgraded to R2019.0.1. Any hotkeys have been taken by Revit host will be swallowed there and not working in DynamoRevit 2019 currently.

**Comment by ksobon** [comment]
Yeah i am in R2019. Was there a patch released already? 2019.0.1?

**Comment by ksobon** [comment]
Oh...May, my bad. OK. I will chill then.

**Comment by QilongTang** [comment]
@ksobon Not yet, this issue was found after R2019 release frozen so the fix was put into R2019.0.1. Stay tuned and update when it pops out 😉 And if you do not mind, I will close the issue for now because 1) Dynamo Sandbox still works 2) There is not need to adjust your Dynamo at that point, this is actually a Revit issue
