### ISSUE TITLE
DesignScript is unusable and desperately needs a debugger and made more robust

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8889]
## Dynamo version

1.3.2

## Operating system

Win10

## What did you do? 

Editing an old DS definiton

## What did you expect to see?

Doesn't work

## What did you see instead?

How about a DEBUGGER. Its agonizing; a script this basic which currently outputs null with no exceptions. It would normally take 5 seconds to fix a script this simple. Instead, I have to resort to cutting and pasting tiny snippets of code to establish where the problem is...which I'm not going to do, so I'd rather just make the improvement suggestion and dump this script altogether. 

Using DS is like a lottery, and the problem caused below could be:
1. Poorly written 3rd party package affecting DS List class?
2. Rank declaration incompatible with input list?
3. Some other inexplicable reason; ternary operator inside a imperative block??

No exceptions are thrown, all I see ist null.

What is being done to improve DS? Without a debugger its unusable.

```
def randomiseMaterials(occurancePercentage:double, materialList:Material[])
{
    //If the occurancePercentage, which is a percentage between 0 and 1 is less than the Math.Rand result, then a random is picked
    indexList = 0..materialCount;
    return = [Imperative]
    {
        materialCount = List.Count(materialList);

        panelMaterial;
        randomNumber = Math.Rand();
        randomNumber2 = Math.Rand();

        if(randomNumber < occurancePercentage && randomNumber2 < occurancePercentage) //Performs a randomisation of the familyTypeList, to randomise the facade based on the occurancePercentage
        {
            i = List.Shuffle(indexList);
            panelMaterial = materialList[i];
        }
        else
        {
            panelMaterial = materialList[0];
        }
        return = panelMaterial;
    }
}

def proximityBooleans(materialList:Material[], proximityDistances:double[], facadeDistances:double[], occurancePercentage:double)
{
    return = [Imperative]
    {
        panelMaterial = {};
        for (i in 0..List.Count(facadeDistances)-1)
        {
            panelMaterial[i] = randomiseMaterials(occurancePercentage, materialList);
        }
        return = panelMaterial;
    }
};

```

**Comment by ThomasMahon** [comment]
@mjkkirschner the script had been bastardised by the time I posted it, it was to demonstrate how a really basic bit of code can waste so much of my time. I've dropped the use of DS completely - there are just too many problems with it to justify using it. I haven't seen any noticeable improvements since my last excruciating foray into using it for something worthwhile, and that was back at the start of 2016...
https://github.com/DynamoDS/Dynamo/issues/6513

Also, checkout the gif I added in the thread - it shows the GenerativeComponents debugger. It was brilliant and essential. I'm really surprised that such a critical feature can be omitted from a programming tool.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
