### ISSUE TITLE
could we add topo pts in dynamo?

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#903]
could we add topo pts in dynamo?

**Comment by rbosborne** [comment]
See this post on the Dynamo User Forum:
http://dynamobim.org/forums/topic/topo-add-points-api-guru-help-needed/

TopographyEditScope does not work via PythonScript within Dynamo (verified by Dimitar). It is possible to create a topo using PythonScript, but it does not appear that one can add points to the topo after creation because of this limitation.
