### ISSUE TITLE
Zero Touch XML comments not displaying correctly - is there a limit to the number of tags?

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#9063]
## Dynamo version

1.3.3

## Operating system

Win 10

## What did you do? 

Built a ZT library with XML comments. Note that every single class, field, property, method and namespace includes a summary tag. Its a large library, but only four methods are public/visible in the Dynamo library. XML is approx 1200 lines

## What did you expect to see?

The summary and input port hints displaying for the nodes in the library. 

## What did you see instead?

One of the nodes shows the summary of a private method from a completely different namespace and class.

If I delete all the tags with the exception of the public methods, everything works as expected.

I also noticed that the XML comments for the nodes was always at the bottom of the file, so I cut them and pasted them to the top. Now, the summary for the private method the public node calls (from the same class) shows. It seems very inconsistent.

I've validated the XML and its valid. There are no other classes in the library which share the same name, or methods which share the same name so it cant be a namespace clash. 

I cant share the project publicly as its a confidential project.

**Comment by ThomasMahon** [comment]
I've done more tests and it seems Dynamo consumes the XML by querying each line of the XML and indiscriminately finds the first matching reference to the node and delivers whatever comment is in the summary tag. 

So I have the public class with no declared namespace (to avoid unnecessary sub categories in the Dynamo library):
`MyClass.MyMethod`

Elsewhere I have a namespace with private classes and methods called (pay careful attention to the 's' on the inner namespace):
MyNamespace.MyMethods

The private method includes a input signature with a reference to a class from `MyNamespace.MyMethods` namespace.

In the XML then, Dynamo finds, `MyMethod` in this input signature, and delivers the summary erroneously to the node in the library! WTF?

Why doesn't it do an exact match? So I have to either rename the namespace OR only comment public methods or properties (not an option) or remove all the XML tags for private methods.

Can this be improved

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
