### ISSUE TITLE
Migrations.XML is not working

### ISSUE THREAD

**Issue by aliasguru** [DynamoDS/Dynamo#9076]
## Dynamo version

2.1.0.5903

## Operating system

Windows 10

## What did you do? 
I've posted the question already here in the Forum, but got no answer so far:
https://forum.dynamobim.com/t/how-to-properly-use-migrations-xml-with-a-zerotouch-nodes-package/25199

Basically, I have followed the steps in https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development#migrations to set up a migrations.xml file. But even though the file name, the file location, and the given package paths are correct, the nodes in question in the node tree are being shown as "Unresolved" when I open the Dynamo file.

## What did you expect to see?

no errors, node tree should continue to work

## What did you see instead?

unresolved nodes

**Comment by erfajo** [comment]
And the assembly name is the same!?

If you rename the assembly, then this must also be added the migration

example

      <priorNameHint>
        <oldName>Orchid.Core.Directory.ContentsAll</oldName>
        <newName>Orchid.Generic.Core.Directory.ContentsAll</newName>
        <additionalAttributes>
          <attribute>
            <name>assembly</name>
            <value>OrchidGeneric.dll</value>
          </attribute>
        </additionalAttributes>
      </priorNameHint>

**Comment by mjkkirschner** [comment]
@aliasguru can you confirm what type of file you are trying to migrate - a json or xml based file?
I'm not sure JSON files will be able to migrate at this point. I think it was an oversight that remained when we transitioned to json that migration was not required because we only had one released version of dynamo that would create json files.

But this does not take into account packages which might migrate between dynamo versions. 😬 .
@Racel @QilongTang

**Comment by aliasguru** [comment]
@mjkkirschner Hm that would start to make sense. I'm **not** trying to migrate from an old Dynamo version. In fact, I only want to change a namespace. I had placed a node in a certain package, and now want to move it to a different one. My understanding of the migration was that it would be evaluated any time I open a node tree, instead of only if the Dynamo version which the node tree was created in differs from the version that it is opened with. It's just because the node trees I'm testing my nodes with can become complex, and it's tedious to re-hook all those unresolved nodes.

**Comment by johnpierson** [comment]
Tracked internally as [QNTM-5547](https://jira.autodesk.com/browse/QNTM-5547)

**Comment by erfajo** [comment]
I have got feedback at the forum, which lead me to dive into the problem
the issue can be followed from here...
https://forum.dynamobim.com/t/is-it-possible-to-have-multiple-versions-of-node-packages/31437/7

My findings goes as this (@mjkkirschner )

It seems that migration doesn't work internally in the 2.0.x version. It work fine between versions. I tried to find old 1.3.x graphs and they migrated perfectly into 2.0.2. Graphs from 2.0.x, where nodes need migration, is failing!

The two nodes left are both named &quot;List.Clean&quot;, but that node changed its &quot;namespace&quot; at some point. The two nodes right are the same, but the node name changed from &quot;Directory.ContentsAll&quot; to &quot;Directory.Contents&quot;. If I tried the same with a 1.3.x graph they migrated perfectly!

[TestGraph.dyn.txt](https://github.com/DynamoDS/Dynamo/files/2822560/TestGraph.dyn.txt) remove ".txt"
![capture](https://user-images.githubusercontent.com/2844374/52138238-ddad4180-264c-11e9-9661-809d320c9d7d.png)

my migration file
[OrchidGeneric.Migrations.xml.txt](https://github.com/DynamoDS/Dynamo/files/2822569/OrchidGeneric.Migrations.xml.txt) remove ".txt"

**Comment by mjkkirschner** [comment]
@erfajo this sounds correct - but should be fixed in next release:
https://github.com/DynamoDS/Dynamo/pull/9306

**Comment by erfajo** [comment]
sounds good but when are you planing to release a new 2.0.x version then. This could end as a major issue for many users.
If I knew this issue in advance I would not move nodes around (change namespaces, change names etc.). Since I didn't have the issue myself I might have changed 20 nodes +/-. I did only test between 1.3.x and 2.0.x versions, not internally in 2.0.x versions... maybe other package authors has done the same not knowing this issue...

**Comment by mjkkirschner** [comment]
please reopen if this is not fixed for you in 2.1.

**Comment by vinnividivicci** [comment]
So I've followed the instructions in [here](https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development#migrations) but no dice either. 
My nodes and script were created for 2.0.2. Then I renamed some classes and created the migration.xml file. However, when I open it in Dynamo 2.1 (with Revit 2020) the nodes in the script do not migrate and are unresolved.

Furthermore, the documentation is confusing, since this [Wiki](https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development#migrations) says:
> Migration files should be named in the following format: **BaseDLLName**.Migrations.xml. 

while [this page](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Package-Organization-and-Migration) says:

> ZeroTouch nodes use a **Namespace**.Migrations.XML file located in the packages bin folder such as

So which one is it: the **name of the DLL** or the **Namespace**?

Thanks ahead of time for your help.

**Comment by mjkkirschner** [comment]
looks like it uses the library name:
https://github.com/DynamoDS/Dynamo/blob/5bafc553476cd7efa1b37c31d35925754538617a/src/DynamoCore/Library/LibraryServices.cs#L659

I would use the filename of the dll - for a lot of our internal migrations it's not super clear because they are the same - but glancing at the code looks like dll name to me -

can you post your migration file? Are you making a package? Where is your migration when you load your dll? How are you loading your dll etc.

**Comment by vinnividivicci** [comment]
Thanks for the reply @mjkkirschner .

I'm making a ZeroTouch node and loading it by simply having it in `%appdata%/Dynamo/Dynamo Revit/2.0/packages` with a pkg.json file.

My migration file is in exactly the same folder as my dll:
![image](https://user-images.githubusercontent.com/591242/62896937-14f95b00-bd20-11e9-88b3-465363b3e4f7.png)

My migration file looks something like this:
![image](https://user-images.githubusercontent.com/591242/62897159-a4067300-bd20-11e9-943e-14195d2365da.png)

Do you think that it's because I'm loading it directly by putting it in "packages" that it's not migrating?

**Comment by mjkkirschner** [comment]
try this - 
1. make sure that your dll is not being loaded from the node and package path settings dialog. Remove it from that set of paths if it's there.
2. I can't tell from your image, but make sure your node dll and the migrations are in the /bin folder of your package, and that you have a package.json that points to that dll etc.

**Comment by vinnividivicci** [comment]
Thanks @mjkkirschner , my dll and migration.xml are both in the /bin folder.
I am indeed loading the package by having the path in "Manage Nodes and Package paths":
![image](https://user-images.githubusercontent.com/591242/62943542-b62bf400-bda8-11e9-94cc-2c74eb275dde.png)

I was doing it this way to facilitate & expedite debugging and deployment of the ZeroTouch node.
But are you are saying that migrations will not work if we are loading the package this way? I thought this was the official way to load them?
