### ISSUE TITLE
Node to code creating duplicate variables

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#9228]
## Dynamo version

2.0.1 stable

## Operating system

Windows 10

## What did you do? 

Ran node-to-code

## What did you expect to see?

A working code block

## What did you see instead?

A code block with a warning:
```
Variable num10 has been defined in this code block node. 
You cannot define a variable more than once.
```
I've seen this in a number of graphs, but couldn't see a pattern, so no idea what is causing this.

## Steps to reproduce
* Open any of the following sample files that ship with Dynamo
   * Core_CodeBlocks.dyn
   * Geometry_Solids.dyn
   * ImportExport_CSV to Stuff.dyn
* Select all 
* Run node to code

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
