### ISSUE TITLE
BUG: Ternary operator in DS def if statement busts compiler

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#9244]
## Dynamo version

1.3.3

## Operating system

Win 10

## What did you do? 

A simple def in DS with some if statements and a ternary operator.

## What did you expect to see?

For DS to break without any rhyme or reason, like it usually does.

## What did you see instead?

I saw exactly what I expected, another busted feature of the language. No warnings. No exceptions. Where's the bin?...

Try it for yourself:

```
def MyDef(x : double)
{
	return = [Imperative]
	{
		if (x <= 100.0)
		{
			divisor = 10.0;
			number = Math.Ceiling(x / divisor) * divisor;
			return = number < 20.0 ? 20.0 : number;
		}
		else if (x <= 250.0) // No need to check if its greater than 100 otherwise it would pass the first if statement
		{
			divisor = 25.0;
		}
		else // Greater than 300.0
		{
			divisor = 100.0;
		}

		return = Math.Ceiling(x / divisor) * divisor;
	}
};
```

**Comment by dimven** [comment]
The ternary syntax seems to only work in associative mode. Whenever you put it inside of an imperative scope, the VM fails to compile the DS function.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
