### ISSUE TITLE
Wish: Set subcategory for geometry elements

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#931]
It would be extremely helpful if we could set the subcategory for the curves or forms we create.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
