### ISSUE TITLE
Get family location returns incorrect Z value

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#945]
returns 0 value for Z location.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
