### ISSUE TITLE
AnalysisData Nodes seems obsolete and is not visible

### ISSUE THREAD

**Issue by ZiyunShang** [DynamoDS/Dynamo#9591]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.1.0

## Operating system

Windows 10

## What did you do? 

I opened 3 dyn file in Revit: PointAnalysisDisplay_ByViewAndPointAnalysisData.dyn, SurfaceAnalysisDisplay_ByViewAndPointAnalysisData.dyn, VectorAnalysisDisplay_ByViewAndPointAnalysisData.dyn, which are from DynamoRevit test\System\AnalysisDisplay folder.
![PointAnalysisDisplay_ByViewAndPointAnalysisData](https://user-images.githubusercontent.com/33445445/54808417-21badb00-4cbb-11e9-8cce-97d16b3a5f48.png)
![SurfaceAnalysisDisplay_ByViewAndPointAnalysisData](https://user-images.githubusercontent.com/33445445/54808437-31d2ba80-4cbb-11e9-9631-f5d58a245faa.png)
![VectorAnalysisDisplay_ByViewAndPointAnalysisData](https://user-images.githubusercontent.com/33445445/54808442-35fed800-4cbb-11e9-9ccd-397faa485aae.png)

## What did you expect to see?

I want to see all the nodes with no warning and error.

## What did you see instead?

The nodes PointData.ByPointsAndValues, SurfaceData.BySurfacePointsAndValues, VectorData.ByPointsAndValues display with yellow warning.

**Comment by mjkkirschner** [comment]
@ZiyunShang what are the errors in the graph?

**Comment by ZiyunShang** [comment]
@mjkkirschner I'm sorry for missing the warning message.
![PointDataNode](https://user-images.githubusercontent.com/33445445/54889456-af771000-4edf-11e9-94d8-9993f649d514.png)
![SurfaceData](https://user-images.githubusercontent.com/33445445/54889458-b3a32d80-4edf-11e9-9204-51f4419a5ba6.png)
![VectorData](https://user-images.githubusercontent.com/33445445/54889461-b736b480-4edf-11e9-82f1-1035c63b3a83.png)

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/Dynamo/blob/ec10f936824152e7dd7d6d019efdcda0d78a5264/src/Libraries/Analysis/PointData.cs#L40

indeed the nodes are marked obsolete but still work - The error message is telling you, you can pass geometry objects and number data directly to the downstream nodes instead of using these nodes... ie users can use this node instead:
https://github.com/DynamoDS/DynamoRevit/blob/4cc183fb6eb7db13e29cf2d04192df499961a8b9/src/Libraries/RevitNodes/AnalysisDisplay/PointAnalysisDisplay.cs#L159

in the case of the PointAnalysisDisplay - I have no idea when these were obsoleted but it appears to be atleast 2015...
https://github.com/DynamoDS/Dynamo/commit/ce6eb8ad3c4ef2f043bfbb7be122bb15ab42988a#diff-3a0b5526e2f763cfbb5d6560fae4db1c

**Comment by ZiyunShang** [comment]
Thank you for your reply @mjkkirschner !  Do you think these three nodes, ByViewAndPointAnalysisData, should be made invisible?

**Comment by mjkkirschner** [comment]
I think they should also be made `NodeObsolete` and point users to the new nodes that don't require the `Data` classes.
