### ISSUE TITLE
Some ideas for the package manager stats

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#974]
I just noticed that we can now click on a package or author name on the package manager website. Looks awesome!
Some ideas for the author stats page:
- Order packages alphabetically
- ~~Show deprecated packages in a separate list (alternatively different text colour)~~ (not visible any more)
- Don't let deprecated packages count towards the packages total

Some ideas for the package stats page:
- ~~Mark deprecated packages as deprecated~~ (not visible any more)
- Respect line breaks in package description (previously requested for the package manager search page in #888)
- Insert line breaks between packages for "Used By"

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
