### ISSUE TITLE
Display analysis points node - needs manual display style created, gives no error

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#981]
When using a display analysis points node, nothing will display within Revit unless you manually create a point based analysis display style.  There will be no error reported in dynamo.

In addition the Analysis Display Style node creates a Surface based display style only, maybe this node could take a type style type argument / other options.

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
