### ISSUE TITLE
Daylight Cloud Render returns all black points when sample points are above model bounds

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#982]
![screen shot 2014-01-08 at 4 33 35 pm](https://f.cloud.github.com/assets/508936/1872822/8f48a2bc-78ac-11e3-8b42-f07a2325f95d.png)

above screen shots shows points at 30'

![screen shot 2014-01-08 at 1 49 42 pm](https://f.cloud.github.com/assets/508936/1872825/975cedf0-78ac-11e3-9f4c-b7e0c3e20402.png)

above shot shows points at 50'  - above walls at 40'

I'm unclear if this data is illuminance data or a ratio.  Apparently it depends on sky model type - http://sustainabilityworkshop.autodesk.com/buildings/revit-illuminance-simulations

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
