### ISSUE TITLE
CanvasCreated event?

### ISSUE THREAD

**Issue by epignatelli** [DynamoDS/Dynamo#9830]
Is there any event that represents the startup, or UI initialisation, or anything that happens before the user starts to do something?

**Comment by mjkkirschner** [comment]
you can probably use the DynamoVew.loaded event.

**Comment by epignatelli** [comment]
Thanks @mjkkirschner - how exactly do I subscribe to it?

**Comment by mjkkirschner** [comment]
depends on your context - what are you writing? A node? A viewExtension? A Dynamo integration?

**Comment by epignatelli** [comment]
An external plugin - not sure how that fits in your options. 
How is subscribing to an event object dependent on that anyway?

**Comment by mjkkirschner** [comment]
to subscribe to an event in .net successfully you need a few things.
* a reference to the event
* a handler (could be made on the fly using an anonymous method)
* to subscribe the event before it fires, or you'll simply miss the event, and that's not useful (let's assume it's an event that only fires once)


So - The context is important because it changes how you get a reference, and at what time you have the opportunity to subscribe.

I don't really know what an external plugin means, are you using the Dynamo extensions framework/interfaces or are you writing something where you create your own DynamoModel directly?


If you're using extensions you can get a reference to the DynamoView from here:
https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/Extensions/ViewLoadedParams.cs#L56

which will be passed as an argument to the `Loaded` method on the extension - Dynamo will call this method here:

https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/Views/Core/DynamoView.xaml.cs#L604

this is write **AFTER** the DynamoView.Loaded framework event is called - so it's too late - in that case you don't need the event just put some logic in the `Loaded` method of your extension (if you were using viewExtensions).

You could also try some other wpf framework event that is triggered more frequently, like layoutUpdated etc.

if you are writing you own integration where you construct a dynamoModel and view, you already have what you need - just do `DynamoView.Loaded += () => {yada yada}`

**Comment by mjkkirschner** [comment]
@epignatelli were you able to resolve this or are you still looking for a solution?
